#!/usr/local/bin/php -q
<?php

function _do_query_upload($sqlfile, $connection = null, $ignoreErrors = false) {
	echo "+++ $sqlfile\n";
	ob_start();
	query_upload($sqlfile, $connection, $ignoreErrors);
	$output = ob_get_contents();
	ob_end_clean();
	$output = strip_tags($output);
	if (!empty($output) && preg_match("/\[NOTE:/", $output)) {
		echo "\n$output\n";
	}
}

if (isset($argv[1]) && $argv[1] == 'help') {
	echo <<<OUT
Usage: $argv[0] [option1] [option2]

where:
  option1 - one of the following: demo (install all demo data), standalone (only demo data for LC standalone distributive), drupal (install only demo data for distributive and enable DrupalConnector module; uses by default).
  option2 - if has a value 'all' then all modules will be enabled (only if option1=demo)

Examples:
  $argv[0]
  $argv[0] demo
  $argv[0] demo all
  $argv[0] standalone

OUT;
	exit;
}

chdir(dirname(__FILE__));

include "includes/functions.php";

set_time_limit(0);
error_reporting(E_ALL ^ E_NOTICE);
$config = parse_ini_file("etc/config.local.php");

$config['hostspec'] .= empty($config['socket'])
	? (empty($config['port']) ? '' : ':' . $config['port'])
	: ':' . $config['socket'];
$connection = mysql_connect($config["hostspec"], $config["username"], $config["password"]);
mysql_select_db($config["database"]);

_do_query_upload("sql/xlite_tables.sql", $connection, true);
_do_query_upload("sql/xlite_data.sql", $connection, true);
_do_query_upload("sql/states_US.sql", $connection, true);
_do_query_upload("sql/states_GB.sql", $connection, true);
_do_query_upload("sql/states_CA.sql", $connection, true);

require_once 'classes/XLite/Base.php';
require_once 'classes/XLite/Model/Abstract.php';
require_once 'classes/XLite/Model/Module.php';
require_once 'classes/XLite/Module/Abstract.php';

// modules
$modules = opendir("classes/XLite/Module");

while (($dir = readdir($modules)) !== false) {
	if ($dir{0}!='.' && is_dir("classes/XLite/Module/$dir")) {

		require_once 'classes/XLite/Module/' . $dir . '/Main.php';
		$class = 'XLite_Module_' . $dir . '_Main';

		mysql_query('REPLACE INTO xlite_modules SET name = \'' . $dir . '\', mutual_modules = \'' . implode(',', call_user_func(array($class, 'getMutualModules'))) . '\', type = \'' . call_user_func(array($class, 'getType')). '\'');

		!file_exists($sqlFile = 'classes/XLite/Module/' . $dir . '/install.sql') || _do_query_upload($sqlFile, $connection, true);
	}
}

closedir($modules);

_do_query_upload("sql/xlite_demo.sql", $connection, true);
_do_query_upload("sql/xlite_demo_user.sql", $connection, true);

if (isset($argv[1]) && $argv[1] == "demo") {

    _do_query_upload("sql/xlite_demo_data.sql", $connection, true);
	_do_query_upload("sql/xlite_demo_store.sql", $connection, true);
	_do_query_upload("sql/xlite_test_accounts.sql", $connection, true);

	if (isset($argv[2]) && $argv[2] == 'all') {
		_do_query_upload("sql/xlite_all_modules.sql", $connection, true);
	}

} elseif (isset($argv[1]) && in_array($argv[1], array('standalone', 'st', 's', 'stand'))) {
	_do_query_upload("sql/xlite_modules_standalone.sql", $connection, true);
} else {
	_do_query_upload("sql/xlite_modules_drupal.sql", $connection, true);
}

if (file_exists('sql/xlite_local_demo.sql')) {
	_do_query_upload('sql/xlite_local_demo.sql', $connection, true);
}

echo "Remove directory var/run\n\n";

unlinkRecursive('var/run');

mysql_close($connection);

