#!/usr/local/bin/php -q
<?php

include "includes/functions.php";

set_time_limit(0);
error_reporting(E_ALL ^ E_NOTICE);
$config = parse_ini_file("etc/config.local.php");

$config['hostspec'] .= empty($config['socket'])
	? (empty($config['port']) ? '' : ':' . $config['port'])
	: ':' . $config['socket'];
$connection = mysql_connect($config["hostspec"],$config["username"],$config["password"]);
mysql_select_db($config["database"]);

print "dbclear.sql\n";
query_upload("sql/dbclear.sql", $connection, true);
print "xlite_tables.sql\n";
query_upload("sql/xlite_tables.sql", $connection, true);
print "xlite_data.sql\n";
query_upload("sql/xlite_data.sql", $connection, true);
print "states_US.sql\n";
query_upload("sql/states_US.sql", $connection, true);

require_once 'classes/XLite/Base.php';
require_once 'classes/XLite/Model/Abstract.php';
require_once 'classes/XLite/Model/Module.php';
require_once 'classes/XLite/Module/Abstract.php';

// modules
$modules = opendir("classes/XLite/Module");
while (($dir = readdir($modules)) !== false) {
	if ($dir{0}!='.' && is_dir("classes/XLite/Module/$dir")) {

		require_once 'classes/XLite/Module/' . $dir . '/Main.php';
		$class = 'XLite_Module_' . $dir . '_Main';

		mysql_query('REPLACE INTO xlite_modules SET name = \'' . $dir . '\', mutual_modules = \'' . implode(',', call_user_func(array($class, 'getMutualModules'))) . '\', type = \'' . call_user_func(array($class, 'getType')). '\'');

		!file_exists($sqlFile = 'classes/XLite/Module/' . $dir . '/install.sql') || query_upload($sqlFile, $connection, true);
	}
}
closedir($modules);
print "xlite_modules.sql\n";
query_upload("sql/xlite_modules.sql", $connection, true);
print "xlite_demo.sql\n";
query_upload("sql/xlite_demo.sql", $connection, true);

if (isset($argv[1]) && $argv[1] == "demo") {
    echo "xlite_demo_store.sql\n";
	query_upload("sql/xlite_demo_store.sql", $connection, true);

	if (isset($argv[2]) && $argv[2] == 'all') {
	    echo "xlite_all_modules.sql\n";
		query_upload("sql/xlite_all_modules.sql", $connection, true);
	}

} else {
    mysql_query("REPLACE INTO xlite_profiles (profile_id, login, password, access_level, billing_title, billing_firstname, billing_lastname, billing_phone, billing_address, billing_city, billing_state, billing_country, billing_zipcode, shipping_title, shipping_firstname, shipping_lastname, shipping_phone, shipping_address, shipping_city, shipping_state, shipping_country, shipping_zipcode, first_login, last_login, status) VALUES (1,'vvs@cdev.ru','eb0a191797624dd3a48fa681d3061212',100,'Mr.','Bit','Bucket','0123456789','Billing street, 1','Edmond',38,'US','73003','Mr.','Bit','Bucket','9876543210','Shipping street, 1','Edmond',38,'US','73003',1053689339,1058449247,'E')");
}

unlinkRecursive('var/run');

mysql_close($connection);

