ALTER TABLE xlite_modules CHANGE version version varchar(12) NOT NULL DEFAULT '0';
INSERT IGNORE INTO xlite_config VALUES ('current_currency', 'Current currency', 'USD', 'CardinalCommerce', 10, 'select');
INSERT IGNORE INTO xlite_config(name,category,comment,orderby,type) VALUES ('processor_id','CardinalCommerce','Processor ID',20,'text');
INSERT IGNORE INTO xlite_config(name,category,comment,orderby,type) VALUES ('merchant_id','CardinalCommerce','Merchant ID',30,'text');
INSERT IGNORE INTO xlite_config VALUES ('transaction_url', 'Transaction URL', 'https://centineltest.cardinalcommerce.com:443/maps/txns.asp', 'CardinalCommerce', 40, 'text');

CREATE TABLE xlite_currencies 
(
  code CHAR(3) NOT NULL DEFAULT '',
  code_int INT(3) NOT NULL DEFAULT '0',
  name varchar(128) NOT NULL DEFAULT '',
  symbol varchar(16) NOT NULL DEFAULT '',
  UNIQUE KEY code (code),
  KEY code_int (code_int)
);

INSERT IGNORE INTO xlite_currencies VALUES('ADP','20','Andorran Pesseta','');
INSERT IGNORE INTO xlite_currencies VALUES('AED','784','UAE Dirtham','');
INSERT IGNORE INTO xlite_currencies VALUES('AFA','4','Afghani','');
INSERT IGNORE INTO xlite_currencies VALUES('ALL','8','Lek','');
INSERT IGNORE INTO xlite_currencies VALUES('AMD','51','Armenian Dram','');
INSERT IGNORE INTO xlite_currencies VALUES('ANG','532','Netherlands Antillian Guilder','&#402;');
INSERT IGNORE INTO xlite_currencies VALUES('AON','24','Kwanza','');
INSERT IGNORE INTO xlite_currencies VALUES('ARS','32','Argentine Peso','&#8369;');
INSERT IGNORE INTO xlite_currencies VALUES('ATS','40','Austrian Shilling','');
INSERT IGNORE INTO xlite_currencies VALUES('AUD','36','Austrilian Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('AWG','533','Aruban Guilder','&#402;');
INSERT IGNORE INTO xlite_currencies VALUES('AZM','31','Azerbaijanian Manat','');
INSERT IGNORE INTO xlite_currencies VALUES('BAM','977','Convertible Marks','');
INSERT IGNORE INTO xlite_currencies VALUES('BBD','52','Barbados Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('BDT','50','Bangladesh Taka','');
INSERT IGNORE INTO xlite_currencies VALUES('BEF','56','Belgium Franc','&#8355;');
INSERT IGNORE INTO xlite_currencies VALUES('BGL','100','Bulgarian Lev','');
INSERT IGNORE INTO xlite_currencies VALUES('BHD','48','Belgium Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('BIF','108','Burundi Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('BMD','60','Bermudian Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('BND','96','Brunei Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('BOB','68','Boliviano','');
INSERT IGNORE INTO xlite_currencies VALUES('BRL','986','Brazilian Real','');
INSERT IGNORE INTO xlite_currencies VALUES('BSD','986','Brazilian Real','$');
INSERT IGNORE INTO xlite_currencies VALUES('BTN','64','Ngultrum','');
INSERT IGNORE INTO xlite_currencies VALUES('BWP','72','Botswana Pula','');
INSERT IGNORE INTO xlite_currencies VALUES('BYR','974','Belarussian Rouble','');
INSERT IGNORE INTO xlite_currencies VALUES('BZD','84','Belize Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('CAD','124','Canadian Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('CDF','976','Franc Congolais','');
INSERT IGNORE INTO xlite_currencies VALUES('CHF','756','Swiss Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('CLP','152','Chilean Peso','&#8369;');
INSERT IGNORE INTO xlite_currencies VALUES('CNY','156','Chinese Renminbi Yuan','&#20803;');
INSERT IGNORE INTO xlite_currencies VALUES('COP','170','Colombian Peso','&#8369;');
INSERT IGNORE INTO xlite_currencies VALUES('CRC','188','Cost Rican Colon','&#8353;');
INSERT IGNORE INTO xlite_currencies VALUES('CUP','192','Cuban Peso','&#8369;');
INSERT IGNORE INTO xlite_currencies VALUES('CVE','132','Cape Verde Escudo','');
INSERT IGNORE INTO xlite_currencies VALUES('CYP','196','Cypprus Pound','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('CZK','203','Czech Koruna','');
INSERT IGNORE INTO xlite_currencies VALUES('DEM','276','Deutsche Mark','');
INSERT IGNORE INTO xlite_currencies VALUES('DJF','262','Djibouti Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('DKK','208','Danish Krone','');
INSERT IGNORE INTO xlite_currencies VALUES('DOP','214','Dominican Peso','&#8369;');
INSERT IGNORE INTO xlite_currencies VALUES('DZD','12','Algerian Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('EEK','233','Kroon','');
INSERT IGNORE INTO xlite_currencies VALUES('EGP','818','Egyptian Pound','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('ERN','232','Nakfa','');
INSERT IGNORE INTO xlite_currencies VALUES('ETB','230','Ethiopian Birr','');
INSERT IGNORE INTO xlite_currencies VALUES('EUR','978','EURO','&#8364;');
INSERT IGNORE INTO xlite_currencies VALUES('FIM','246','Finnish Markka','');
INSERT IGNORE INTO xlite_currencies VALUES('FJD','242','Fiji Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('FKP','238','Falkland Islands Pound','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('FRF','250','French Franc','&#8355;');
INSERT IGNORE INTO xlite_currencies VALUES('GBP','826','Sterling','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('GEL','981','Lari','');
INSERT IGNORE INTO xlite_currencies VALUES('GHC','288','Ghana Cedi','');
INSERT IGNORE INTO xlite_currencies VALUES('GIP','292','Gilbraltar Pound','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('GMD','270','Dalasi','');
INSERT IGNORE INTO xlite_currencies VALUES('GNF','324','Guinea Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('GTQ','320','Quetzal','');
INSERT IGNORE INTO xlite_currencies VALUES('GWP','624','Guinea-Bissau Peso','');
INSERT IGNORE INTO xlite_currencies VALUES('GYD','328','Guyana Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('HKD','344','Hong Kong Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('HNL','340','Lempira','');
INSERT IGNORE INTO xlite_currencies VALUES('HRK','191','Croatian Kuna','');
INSERT IGNORE INTO xlite_currencies VALUES('HTG','332','Gourde','');
INSERT IGNORE INTO xlite_currencies VALUES('HUF','348','Hungary Forint','');
INSERT IGNORE INTO xlite_currencies VALUES('IDR','360','Rupiah','');
INSERT IGNORE INTO xlite_currencies VALUES('IEP','372','Irish Punt','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('ILS','376','New Israeli Sheqel','&#8362;');
INSERT IGNORE INTO xlite_currencies VALUES('INR','356','Indian Ruppe','&#8360;');
INSERT IGNORE INTO xlite_currencies VALUES('IQD','368','Iraqi Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('IRR','364','Iranian Rial','&#65020;');
INSERT IGNORE INTO xlite_currencies VALUES('ISK','352','Iceland Krona','');
INSERT IGNORE INTO xlite_currencies VALUES('ITL','380','Italian Lira','&#8356;');
INSERT IGNORE INTO xlite_currencies VALUES('JMD','388','Jamaican Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('JOD','400','Jordanian Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('JPY','392','Japanese Yen','&#165;');
INSERT IGNORE INTO xlite_currencies VALUES('KES','404','Kenyan Shilling','');
INSERT IGNORE INTO xlite_currencies VALUES('KGS','417','Son','');
INSERT IGNORE INTO xlite_currencies VALUES('SHR','116','Riel','');
INSERT IGNORE INTO xlite_currencies VALUES('KMF','174','Comoro Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('KPW','408','North Korean Won','&#8361;');
INSERT IGNORE INTO xlite_currencies VALUES('KRW','410','South Korean Won','&#8361;');
INSERT IGNORE INTO xlite_currencies VALUES('KWD','414','Kuwaiti Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('KYD','136','Cayman Islands Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('KZT','398','Tenge','');
INSERT IGNORE INTO xlite_currencies VALUES('LAK','418','Kip','&#8365;');
INSERT IGNORE INTO xlite_currencies VALUES('LBP','422','Lebanese Pound','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('LKR','144','Sri Lanka Rupee','&#3065;');
INSERT IGNORE INTO xlite_currencies VALUES('LRD','430','Liberian Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('LSL','426','Loti','');
INSERT IGNORE INTO xlite_currencies VALUES('LTL','440','Lithuanian Litus','');
INSERT IGNORE INTO xlite_currencies VALUES('LUF','442','Luxembourg Franc','&#8355;');
INSERT IGNORE INTO xlite_currencies VALUES('LVL','428','Latvian Lats','');
INSERT IGNORE INTO xlite_currencies VALUES('LYD','434','Libyan Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('MAD','504','Moroccan Dirtham','');
INSERT IGNORE INTO xlite_currencies VALUES('MDL','498','Moldovan Leu','');
INSERT IGNORE INTO xlite_currencies VALUES('MGF','450','Malagasy Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('MKD','807','Denar','');
INSERT IGNORE INTO xlite_currencies VALUES('MMK','104','Kyat','');
INSERT IGNORE INTO xlite_currencies VALUES('MNT','496','Tugrik','&#8366;');
INSERT IGNORE INTO xlite_currencies VALUES('MOP','446','Pataca','');
INSERT IGNORE INTO xlite_currencies VALUES('MRO','478','Ouguiya','');
INSERT IGNORE INTO xlite_currencies VALUES('MTL','470','Maltese Lira','&#8356;');
INSERT IGNORE INTO xlite_currencies VALUES('MUR','480','Mauritius Rupee','&#8360;');
INSERT IGNORE INTO xlite_currencies VALUES('MVR','462','Rufiyaa','');
INSERT IGNORE INTO xlite_currencies VALUES('MWK','454','Kwacha','');
INSERT IGNORE INTO xlite_currencies VALUES('MXN','484','Mexican Peso','$');
INSERT IGNORE INTO xlite_currencies VALUES('MYR','458','Malasian Ringgit','');
INSERT IGNORE INTO xlite_currencies VALUES('MZM','508','Mozambique Metical','');
INSERT IGNORE INTO xlite_currencies VALUES('NAD','516','Namibia Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('NGN','566','Naira','&#8358;');
INSERT IGNORE INTO xlite_currencies VALUES('NIO','558','Cordoba Oro','');
INSERT IGNORE INTO xlite_currencies VALUES('NLG','528','Dutch Guilder','&#402;');
INSERT IGNORE INTO xlite_currencies VALUES('NOK','578','Norwegian Krone','');
INSERT IGNORE INTO xlite_currencies VALUES('NPR','524','Nepalese Rupee','&#8360;');
INSERT IGNORE INTO xlite_currencies VALUES('NZD','554','New Zealand Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('OMR','512','Rial Omani','&#65020;');
INSERT IGNORE INTO xlite_currencies VALUES('PAB','590','Balboa','');
INSERT IGNORE INTO xlite_currencies VALUES('PEN','604','Nuevo Sol','');
INSERT IGNORE INTO xlite_currencies VALUES('PGK','598','Kina','');
INSERT IGNORE INTO xlite_currencies VALUES('PHP','608','Philippine Peso','&#8369;');
INSERT IGNORE INTO xlite_currencies VALUES('PKR','586','Pakistan Rupee','&#8360;');
INSERT IGNORE INTO xlite_currencies VALUES('PLN','985','Zloty','');
INSERT IGNORE INTO xlite_currencies VALUES('PTE','620','Portuguese Escudo','');
INSERT IGNORE INTO xlite_currencies VALUES('PYG','600','Guarani','');
INSERT IGNORE INTO xlite_currencies VALUES('QAR','634','Qatari Rial','&#65020;');
INSERT IGNORE INTO xlite_currencies VALUES('ROL','642','Leu','');
INSERT IGNORE INTO xlite_currencies VALUES('RUB','643','Russian Ruble','');
INSERT IGNORE INTO xlite_currencies VALUES('RUR','810','Russian Ruble','');
INSERT IGNORE INTO xlite_currencies VALUES('RWF','646','Rwanda Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('SAR','682','Saudi Riyal','&#65020;');
INSERT IGNORE INTO xlite_currencies VALUES('SBD','90','Solomon Islands Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('SCR','690','Seychelles Rupee','&#8360;');
INSERT IGNORE INTO xlite_currencies VALUES('SDD','736','Sudanese Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('SEK','752','Swedish Krona','');
INSERT IGNORE INTO xlite_currencies VALUES('SGD','702','Singapore Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('SHP','654','Saint Helena Pound','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('SIT','705','Tolar','');
INSERT IGNORE INTO xlite_currencies VALUES('SKK','703','Slovak Koruna','');
INSERT IGNORE INTO xlite_currencies VALUES('SLL','694','Leone','');
INSERT IGNORE INTO xlite_currencies VALUES('SOS','706','Somali Shilling','');
INSERT IGNORE INTO xlite_currencies VALUES('SRG','740','Suriname Guilder','');
INSERT IGNORE INTO xlite_currencies VALUES('STD','678','Dobra','');
INSERT IGNORE INTO xlite_currencies VALUES('SVC','222','El Salvador Colon','&#8353;');
INSERT IGNORE INTO xlite_currencies VALUES('SYP','760','Syrian Pound','&#163;');
INSERT IGNORE INTO xlite_currencies VALUES('SZL','748','Lilangeni','');
INSERT IGNORE INTO xlite_currencies VALUES('THB','764','Thailand Baht','&#3647;');
INSERT IGNORE INTO xlite_currencies VALUES('TJS','972','Somoni','');
INSERT IGNORE INTO xlite_currencies VALUES('TMM','795','Manat','');
INSERT IGNORE INTO xlite_currencies VALUES('TND','788','Tunisian Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('TOP','776','Pa\'anga','');
INSERT IGNORE INTO xlite_currencies VALUES('TPE','626','Timor Escudo','');
INSERT IGNORE INTO xlite_currencies VALUES('TRL','792','Turkish Lira','&#8356;');
INSERT IGNORE INTO xlite_currencies VALUES('TTD','780','Trinidad and Tobago Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('TWD','901','New Taiwan Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('TZS','834','Tanzanian Shilling','');
INSERT IGNORE INTO xlite_currencies VALUES('UAH','980','Hryvnia','');
INSERT IGNORE INTO xlite_currencies VALUES('UGX','800','Uganda Shilling','');
INSERT IGNORE INTO xlite_currencies VALUES('USD','840','US Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('UYU','858','Peso Uruguayo','');
INSERT IGNORE INTO xlite_currencies VALUES('UZS','860','Tanzanian Shilling','');
INSERT IGNORE INTO xlite_currencies VALUES('VEB','862','Bolivar','');
INSERT IGNORE INTO xlite_currencies VALUES('VND','704','Dong','&#8363;');
INSERT IGNORE INTO xlite_currencies VALUES('VUV','548','Vatu','');
INSERT IGNORE INTO xlite_currencies VALUES('WST','882','Tala','');
INSERT IGNORE INTO xlite_currencies VALUES('XAF','950','CFA Franc BEAC','');
INSERT IGNORE INTO xlite_currencies VALUES('XCD','951','East Caribbean Dollar','$');
INSERT IGNORE INTO xlite_currencies VALUES('XOF','952','CFA Franc BCEAO','');
INSERT IGNORE INTO xlite_currencies VALUES('XPF','953','CFP Franc','');
INSERT IGNORE INTO xlite_currencies VALUES('YER','886','Yemeni Rial','&#65020;');
INSERT IGNORE INTO xlite_currencies VALUES('YUM','891','Yugoslavian Dinar','');
INSERT IGNORE INTO xlite_currencies VALUES('ZAR','710','South Africa Rand','&#82;');
INSERT IGNORE INTO xlite_currencies VALUES('ZMK','894','Kwacha','');
INSERT IGNORE INTO xlite_currencies VALUES('ZWD','716','Zimbabwe Dollar','$');
