<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);

return array(
    'Zend\\Validator' => $vendorDir . '/zendframework/zend-validator/php/',
    'Zend\\Uri' => $vendorDir . '/zendframework/zend-uri/php/',
    'Zend\\Stdlib' => $vendorDir . '/zendframework/zend-stdlib/php/',
    'Zend\\Registry' => $vendorDir . '/zendframework/zend-registry/php/',
    'Zend\\Loader' => $vendorDir . '/zendframework/zend-loader/php/',
    'Zend\\Http' => $vendorDir . '/zendframework/zend-http/php/',
    'WebDriverSimpleItem' => $vendorDir . '/facebook/php-webdriver/.',
    'WebDriverSession' => $vendorDir . '/facebook/php-webdriver/.',
    'WebDriverEnvironment' => $vendorDir . '/facebook/php-webdriver/.',
    'WebDriverElement' => $vendorDir . '/facebook/php-webdriver/.',
    'WebDriverContainer' => $vendorDir . '/facebook/php-webdriver/.',
    'WebDriverBase' => $vendorDir . '/facebook/php-webdriver/.',
    'WebDriver' => $vendorDir . '/facebook/php-webdriver/.',
    'Symfony\\Component\\Yaml' => $vendorDir . '/symfony/yaml/',
    'Symfony\\Component\\Translation' => $vendorDir . '/symfony/translation/',
    'Symfony\\Component\\Process' => $vendorDir . '/symfony/process/',
    'Symfony\\Component\\Finder' => $vendorDir . '/symfony/finder/',
    'Symfony\\Component\\EventDispatcher' => $vendorDir . '/symfony/event-dispatcher/',
    'Symfony\\Component\\DomCrawler' => $vendorDir . '/symfony/dom-crawler/',
    'Symfony\\Component\\DependencyInjection' => $vendorDir . '/symfony/dependency-injection/',
    'Symfony\\Component\\CssSelector' => $vendorDir . '/symfony/css-selector/',
    'Symfony\\Component\\Console' => $vendorDir . '/symfony/console/',
    'Symfony\\Component\\Config' => $vendorDir . '/symfony/config/',
    'Symfony\\Component\\BrowserKit' => $vendorDir . '/symfony/browser-kit/',
    'Selenium' => $vendorDir . '/alexandresalome/php-selenium/src/',
    'Goutte' => $vendorDir . '/fabpot/goutte/src/',
    'Buzz' => $vendorDir . '/kriswallsmith/buzz/lib/',
    'Behat\\SahiClient' => $vendorDir . '/behat/sahi-client/src/',
    'Behat\\Mink' => $vendorDir . '/behat/mink/src/',
    'Behat\\Gherkin' => $vendorDir . '/behat/gherkin/src/',
    'Behat\\Behat' => $vendorDir . '/behat/behat/src/',
);
