


INSERT INTO xlite_states VALUES (1,'Alabama','AL',0,'US');
INSERT INTO xlite_states VALUES (2,'Alaska','AK',0,'US');
INSERT INTO xlite_states VALUES (3,'Arizona','AZ',0,'US');
INSERT INTO xlite_states VALUES (4,'Arkansas','AR',0,'US');
INSERT INTO xlite_states VALUES (5,'California','CA',0,'US');
INSERT INTO xlite_states VALUES (6,'Colorado','CO',0,'US');
INSERT INTO xlite_states VALUES (7,'Connecticut','CT',0,'US');
INSERT INTO xlite_states VALUES (8,'Delaware','DE',0,'US');
INSERT INTO xlite_states VALUES (9,'District of Columbia','DC',0,'US');
INSERT INTO xlite_states VALUES (10,'Florida','FL',0,'US');
INSERT INTO xlite_states VALUES (11,'Georgia','GA',0,'US');
INSERT INTO xlite_states VALUES (12,'Guam','GU',0,'US');
INSERT INTO xlite_states VALUES (13,'Hawaii','HI',0,'US');
INSERT INTO xlite_states VALUES (14,'Idaho','ID',0,'US');
INSERT INTO xlite_states VALUES (15,'Illinois','IL',0,'US');
INSERT INTO xlite_states VALUES (16,'Indiana','IN',0,'US');
INSERT INTO xlite_states VALUES (17,'Iowa','IA',0,'US');
INSERT INTO xlite_states VALUES (18,'Kansas','KS',0,'US');
INSERT INTO xlite_states VALUES (19,'Kentucky','KY',0,'US');
INSERT INTO xlite_states VALUES (20,'Louisiana','LA',0,'US');
INSERT INTO xlite_states VALUES (21,'Maine','ME',0,'US');
INSERT INTO xlite_states VALUES (22,'Maryland','MD',0,'US');
INSERT INTO xlite_states VALUES (23,'Massachusetts','MA',0,'US');
INSERT INTO xlite_states VALUES (24,'Michigan','MI',0,'US');
INSERT INTO xlite_states VALUES (25,'Minnesota','MN',0,'US');
INSERT INTO xlite_states VALUES (26,'Mississippi','MS',0,'US');
INSERT INTO xlite_states VALUES (27,'Missouri','MO',0,'US');
INSERT INTO xlite_states VALUES (28,'Montana','MT',0,'US');
INSERT INTO xlite_states VALUES (29,'Nebraska','NE',0,'US');
INSERT INTO xlite_states VALUES (30,'Nevada','NV',0,'US');
INSERT INTO xlite_states VALUES (31,'New Hampshire','NH',0,'US');
INSERT INTO xlite_states VALUES (32,'New Jersey','NJ',0,'US');
INSERT INTO xlite_states VALUES (33,'New Mexico','NM',0,'US');
INSERT INTO xlite_states VALUES (34,'New York','NY',0,'US');
INSERT INTO xlite_states VALUES (35,'North Carolina','NC',0,'US');
INSERT INTO xlite_states VALUES (36,'North Dakota','ND',0,'US');
INSERT INTO xlite_states VALUES (37,'Ohio','OH',0,'US');
INSERT INTO xlite_states VALUES (38,'Oklahoma','OK',0,'US');
INSERT INTO xlite_states VALUES (39,'Oregon','OR',0,'US');
INSERT INTO xlite_states VALUES (40,'Pennsylvania','PA',0,'US');
INSERT INTO xlite_states VALUES (41,'Puerto Rico','PR',0,'US');
INSERT INTO xlite_states VALUES (42,'Rhode Island','RI',0,'US');
INSERT INTO xlite_states VALUES (43,'South Carolina','SC',0,'US');
INSERT INTO xlite_states VALUES (44,'South Dakota','SD',0,'US');
INSERT INTO xlite_states VALUES (45,'Tennessee','TN',0,'US');
INSERT INTO xlite_states VALUES (46,'Texas','TX',0,'US');
INSERT INTO xlite_states VALUES (47,'Utah','UT',0,'US');
INSERT INTO xlite_states VALUES (48,'Vermont','VT',0,'US');
INSERT INTO xlite_states VALUES (49,'Virgin Islands','VI',0,'US');
INSERT INTO xlite_states VALUES (50,'Virginia','VA',0,'US');
INSERT INTO xlite_states VALUES (51,'Washington','WA',0,'US');
INSERT INTO xlite_states VALUES (52,'West Virginia','WV',0,'US');
INSERT INTO xlite_states VALUES (53,'Wisconsin','WI',0,'US');
INSERT INTO xlite_states VALUES (54,'Wyoming','WY',0,'US');

