INSERT INTO xlite_card_types VALUES ('VISA','Visa',1,10,1);
INSERT INTO xlite_card_types VALUES ('MC','MasterCard',1,20,1);
INSERT INTO xlite_card_types VALUES ('AMEX','American Express',1,30,1);
INSERT INTO xlite_card_types VALUES ('SW','Maestro/Switch',1,40,1);
INSERT INTO xlite_card_types VALUES ('SO','Solo',1,50,1);
--  INSERT INTO xlite_card_types VALUES ('JCB','JCB',0,60,0);
--  INSERT INTO xlite_card_types VALUES ('UKE','Visa Electron',1,70,0);
--  INSERT INTO xlite_card_types VALUES ('DICL','Diners Club',0,70,0);

INSERT INTO xlite_config VALUES ('include_tax_message','Includes tax message',', including VAT','Taxes',0,'text');
INSERT INTO xlite_config VALUES ('tax_rates','Tax rates','a:3:{i:0;s:6:\"Tax:=0\";i:1;a:2:{s:9:\"condition\";s:30:\"product class=shipping service\";s:6:\"action\";s:6:\"Tax:=0\";}i:2;a:2:{s:9:\"condition\";s:22:\"product class=Tax free\";s:6:\"action\";s:6:\"Tax:=0\";}}','Taxes',20,'');
INSERT INTO xlite_config VALUES ('use_billing_info','Use billing info to calculate taxes','N','Taxes',10,'checkbox');
INSERT INTO xlite_config VALUES ('taxes','','a:1:{i:0;a:2:{s:4:\"name\";s:3:\"Tax\";s:13:\"display_label\";s:3:\"Tax\";}}','Taxes',0,'text');
INSERT INTO xlite_config VALUES ('prices_include_tax','Prices include tax','N','Taxes',200,'checkbox');
INSERT INTO xlite_config VALUES ('version','','3.0.0','Version',0,'');
INSERT INTO xlite_config VALUES ('memberships','Membership levels','a:0:{}','Memberships',0,'serialized');
INSERT INTO xlite_config VALUES ('membershipsCollection','Membership levels','a:0:{}','Memberships',0,'serialized');
INSERT INTO xlite_config VALUES ('product_layout','','sku,name,category,brief_description,description,thumbnail,image,price,tax_class,weight,order_by,enabled,NULL','ImportExport',0,NULL);
INSERT INTO xlite_config VALUES ('user_layout','','login, password, billing_firstname, billing_lastname','ImportExport',0,NULL);
INSERT INTO xlite_config VALUES ('params','','a:0:{}','XCartImport',0,'serialized');
INSERT INTO xlite_config VALUES ('shipping_code','','1702936249','Shipping',0,'text');
INSERT INTO xlite_config VALUES ('callback_code','','','Shipping',0,'text');
INSERT INTO xlite_config VALUES ('callback_status','','','Shipping',0,'text');
INSERT INTO xlite_config VALUES ('license','','','License',0,'text');
INSERT INTO xlite_config VALUES ('defaultSources','','','Images',0,'serialized');
INSERT INTO xlite_config VALUES ('default_offline_payment','Payment method to be assumed in case of zero order totals','','Payments',0,'text');
INSERT INTO xlite_config VALUES ('default_select_payment','Default payment method','','Payments',0,'text');

--  General

-- Maintenance and operation

INSERT INTO xlite_config VALUES ('operation_presentation','Maintenance and operation','','General', 100, 'separator');
INSERT INTO xlite_config VALUES ('developer_mode','Developer\'s mode (force to re-generate cache)','','General', 105, 'checkbox');
INSERT INTO xlite_config VALUES ('shop_closed','Maintenance mode (close the store for maintenance)','N','General',110,'checkbox');
-- UPDATE xlite_config SET orderby = 110, comment='Maintenance mode (close the store for maintenance)' WHERE category = 'General' AND name = 'shop_closed';
INSERT INTO xlite_config VALUES ('add_on_mode','Checkout desk operation mode','N','General',120,'checkbox');
-- UPDATE xlite_config SET orderby = 120, comment='Checkout desk operation mode' WHERE category = 'General' AND name = 'add_on_mode';
INSERT INTO xlite_config VALUES ('add_on_mode_page','Checkout desk operation mode main page','cart.php?target=cart','General',125,'select');
INSERT INTO xlite_config VALUES ('safe_mode','Safe mode (do not initialize modules)','N','General',130,'checkbox');
-- UPDATE xlite_config SET orderby = 130, comment='Safe mode (do not initialize modules)' WHERE category = 'General' AND name = 'safe_mode';

--  Customer Zone Settings 	

INSERT INTO xlite_config VALUES ('customer_presentation','Customer Zone settings','','General', 200, 'separator');
-- UPDATE xlite_config SET orderby = 200 WHERE category = 'General' AND name = 'customer_presentation';
INSERT INTO xlite_config VALUES ('enable_credit_card_validation','Validate credit cards','Y','General',210,'checkbox');
INSERT INTO xlite_config VALUES ('display_check_number','Display check number for eCheck payment method','Y','General',215,'checkbox');
-- UPDATE xlite_config SET orderby = 210, comment='Validate credit cards' WHERE category = 'General' AND name = 'enable_credit_card_validation';
INSERT INTO xlite_config VALUES ('subcategories_look','Category listings format','icons','General',220,'select');
-- UPDATE xlite_config SET orderby = 220, comment='Category listings format' WHERE category = 'General' AND name = 'subcategories_look';
INSERT INTO xlite_config VALUES ('show_thumbnails','Show thumbnails in product list','Y','General',230,'checkbox');
-- UPDATE xlite_config SET orderby = 230 WHERE category = 'General' AND name = 'show_thumbnails';
INSERT INTO xlite_config VALUES ('buynow_button_enabled','Enable \"Buy Now\" button in the product list','Y','General',240,'checkbox');
-- UPDATE xlite_config SET orderby = 240 WHERE category = 'General' AND name = 'buynow_button_enabled';
INSERT INTO xlite_config VALUES ('products_per_page','Products per category listing page','10','General',250,'text');
-- UPDATE xlite_config SET orderby = 250, comment='Products per category listing page' WHERE category = 'General' AND name = 'products_per_page';
INSERT INTO xlite_config VALUES ('direct_product_url','Allow direct URL access to products from disabled categories','N','General',255,'checkbox');
-- UPDATE xlite_config SET comment='Allow direct URL access to products from disabled categories' WHERE name='direct_product_url' AND category='General';
INSERT INTO xlite_config VALUES ('def_calc_shippings_taxes','Show shipping rates & taxes to unregistered customers<br>(presuming that a customer comes from the default country)','N','General',260,'checkbox');
-- UPDATE xlite_config SET orderby = 260 WHERE category = 'General' AND name = 'def_calc_shippings_taxes';
INSERT INTO xlite_config VALUES ('enable_anon_checkout','Enable anonymous checkout','Y','General',270,'checkbox');
-- UPDATE xlite_config SET orderby = 270 WHERE category = 'General' AND name = 'enable_anon_checkout';
INSERT INTO xlite_config VALUES ('minimal_order_amount','Minimum allowed order total','10','General',280,'text');
-- UPDATE xlite_config SET orderby = 280 WHERE category = 'General' AND name = 'minimal_order_amount';
INSERT INTO xlite_config VALUES ('maximal_order_amount','Maximum allowed order total','99999','General',290,'text');
-- UPDATE xlite_config SET orderby = 290 WHERE category = 'General' AND name = 'maximal_order_amount';
INSERT INTO xlite_config VALUES ('default_purchase_limit','Default purchase limit','9999','General',293,'text');
INSERT INTO xlite_config VALUES ('enable_sale_price','Enable \"Market price\" feature','N','General',295,'checkbox');
INSERT INTO xlite_config VALUES ('you_save','Enable \"save\" label (for Market Price)','N','General',296,'select');
-- UPDATE xlite_config SET orderby = 295 WHERE category = 'General' AND name = 'enable_sale_price';
INSERT INTO xlite_config VALUES ('redirect_to_cart','Redirect customer to cart when adding a product','Y','General',300,'checkbox');
-- UPDATE xlite_config SET orderby = 300, comment='Redirect customer to cart when adding a product' WHERE category = 'General' AND name = 'redirect_to_cart';
INSERT INTO xlite_config VALUES ('default_country','Default country in the registration form','US','General',310,'country');
-- UPDATE xlite_config SET orderby = 310 WHERE category = 'General' AND name = 'default_country';
INSERT INTO xlite_config VALUES ('default_zipcode','Default zip/postal code in the registration form','10000','General',320,'text');
-- UPDATE xlite_config SET orderby = 320 WHERE category = 'General' AND name = 'default_zipcode';

--  Administrator Zone settings

INSERT INTO xlite_config VALUES ('admin_presentation','Administrator Zone settings','','General', 400, 'separator');
-- UPDATE xlite_config SET orderby = 400 WHERE category = 'General' AND name = 'admin_presentation';
INSERT INTO xlite_config VALUES ('products_per_page_admin','Products per page','30','General',410,'text');
-- UPDATE xlite_config SET orderby = 410, comment='Products per page' WHERE category = 'General' AND name = 'products_per_page_admin';
INSERT INTO xlite_config VALUES ('users_per_page','Users per page','30','General',420,'text');
-- UPDATE xlite_config SET orderby = 420, comment='Users per page' WHERE category = 'General' AND name = 'users_per_page';
INSERT INTO xlite_config VALUES ('orders_per_page','Orders per page','30','General',430,'text');
-- UPDATE xlite_config SET orderby = 430, comment='Orders per page' WHERE category = 'General' AND name = 'orders_per_page';
INSERT INTO xlite_config VALUES ('recent_orders','Amount of orders in the recent orders list','10','General',440,'text');
-- UPDATE xlite_config SET orderby = 440, comment='Amount of orders in the recent orders list' WHERE category = 'General' AND name = 'recent_orders';
INSERT INTO xlite_config VALUES ('login_lifetime','Days to store last login data','3','General',450,'text');
-- UPDATE xlite_config SET orderby = 450, comment='Days to store last login data' WHERE category = 'General' AND name = 'login_lifetime';
INSERT INTO xlite_config VALUES ('order_starting_number','Initial order number','1','General',460,'text');
-- UPDATE xlite_config SET orderby = 460, comment='Initial order number' WHERE category = 'General' AND name = 'order_starting_number';
INSERT INTO xlite_config VALUES ('enable_categories_extra_fields','Enable extra fields in the category management dialogue','Y','General',470,'checkbox');
-- UPDATE xlite_config SET orderby = 470 WHERE category = 'General' AND name = 'enable_categories_extra_fields';
INSERT INTO xlite_config VALUES ('enable_extra_fields_inherit','Enable products to inherit extra fields from disabled categories (for MultiCategories)','Y','General',480,'checkbox');
-- UPDATE xlite_config SET orderby = 480, comment='Enable products to inherit extra fields from disabled categories (for MultiCategories)' WHERE category = 'General' AND name = 'enable_extra_fields_inherit';
INSERT INTO xlite_config VALUES ('admin_zone_sbbe_enabled','Enable folding sidebar menus','Y','General',490,'checkbox');
-- UPDATE xlite_config SET orderby = 490, comment='Enable folding sidebar menus' WHERE category = 'General' AND name = 'admin_zone_sbbe_enabled';
INSERT INTO xlite_config VALUES ('clear_cc_info','Clear credit cards info from the database on order status change','N','General',500,'select');

--  Units of measurement

INSERT INTO xlite_config VALUES ('unit_presentation','Units of measurement','','General', 600, 'separator');
-- UPDATE xlite_config SET orderby = 600 WHERE category = 'General' AND name = 'unit_presentation';
INSERT INTO xlite_config VALUES ('weight_unit','Weight unit','lbs','General',610,'select');
-- UPDATE xlite_config SET orderby = 610 WHERE category = 'General' AND name = 'weight_unit';
INSERT INTO xlite_config VALUES ('weight_symbol','Weight symbol','lbs','General',620,'text');
-- UPDATE xlite_config SET orderby = 620 WHERE category = 'General' AND name = 'weight_symbol';
INSERT INTO xlite_config VALUES ('price_format','Currency format','$ %s','General',630,'text');
-- UPDATE xlite_config SET orderby = 630 WHERE category = 'General' AND name = 'price_format';
INSERT INTO xlite_config VALUES ('thousand_delim','Currency thousands delimiter',',','General',640,'select');
-- UPDATE xlite_config SET orderby = 640 WHERE category = 'General' AND name = 'thousand_delim';
INSERT INTO xlite_config VALUES ('decimal_delim','Currency decimal delimiter','.','General',650,'select');
-- UPDATE xlite_config SET orderby = 650 WHERE category = 'General' AND name = 'decimal_delim';
INSERT INTO xlite_config VALUES ('date_format','Date format','%m/%d/%Y','General',660,'select');
-- UPDATE xlite_config SET orderby = 660 WHERE category = 'General' AND name = 'date_format';
INSERT INTO xlite_config VALUES ('time_format','Time format','%H:%M','General',670,'select');
-- UPDATE xlite_config SET orderby = 670 WHERE category = 'General' AND name = 'time_format';
INSERT INTO xlite_config VALUES ('time_zone','Time zone','','General',680,'select');

-- Company


INSERT INTO xlite_config VALUES ('company_identity','Identity','','Company',350,'separator');
INSERT INTO xlite_config VALUES ('company_name','Company name','*Your company name*','Company',360,'text');
-- UPDATE xlite_config SET orderby='360' WHERE category='Company' AND name='company_name';
INSERT INTO xlite_config VALUES ('company_website','Company website','http://','Company',370,'text');
-- UPDATE xlite_config SET orderby='370' WHERE category='Company' AND name='company_website';
INSERT INTO xlite_config VALUES ('start_year','Year when store started its operation','2009','Company',380,'text');
-- UPDATE xlite_config SET orderby='380' WHERE category='Company' AND name='start_year';

INSERT INTO xlite_config VALUES ('company_address','Address','','Company',385,'separator');
INSERT INTO xlite_config VALUES ('location_address','Street address','*Your company address*','Company',390,'text');
-- UPDATE xlite_config SET orderby='390', comment="Street address" WHERE category='Company' AND name='location_address';
INSERT INTO xlite_config VALUES ('location_city','City','*You company city*','Company',400,'text');
-- UPDATE xlite_config SET orderby='400', comment="City" WHERE category='Company' AND name='location_city';
INSERT INTO xlite_config VALUES ('company_phone','Phone','(555) 555-5555','Company',410,'text');
-- UPDATE xlite_config SET orderby='410', comment="Phone" WHERE category='Company' AND name='company_phone';
INSERT INTO xlite_config VALUES ('company_fax','Fax','(555) 555-5555','Company',420,'text');
-- UPDATE xlite_config SET orderby='420', comment="Fax" WHERE category='Company' AND name='company_fax';
INSERT INTO xlite_config VALUES ('location_state','State','0','Company',430,'state');
-- UPDATE xlite_config SET orderby='430', comment="State" WHERE category='Company' AND name='location_state';
INSERT INTO xlite_config VALUES ('custom_location_state','Other state (specify)','','Company',435,'text');
INSERT INTO xlite_config VALUES ('location_zipcode','Zip/postal code','50001','Company',440,'text');
-- UPDATE xlite_config SET orderby='440', comment="Zip/postal code" WHERE category='Company' AND name='location_zipcode';
INSERT INTO xlite_config VALUES ('location_country','Country','US','Company',450,'country');
-- UPDATE xlite_config SET orderby='450', comment="Country" WHERE category='Company' AND name='location_country';

INSERT INTO xlite_config VALUES ('company_contacts','Contacts','','Company',455,'separator');
INSERT INTO xlite_config VALUES ('site_administrator','Site administrator e-mail','bit-bucket@x-cart.com','Company',460,'text');
-- UPDATE xlite_config SET orderby='460', comment="Site administrator e-mail" WHERE category='Company' AND name='site_administrator';
INSERT INTO xlite_config VALUES ('users_department','Customer relations e-mail','bit-bucket@x-cart.com','Company',470,'text');
-- UPDATE xlite_config SET orderby='470', comment="Customer relations e-mail" WHERE category='Company' AND name='users_department';
INSERT INTO xlite_config VALUES ('orders_department','Sales department e-mail','bit-bucket@x-cart.com','Company',480,'text');
-- UPDATE xlite_config SET orderby='480', comment="Sales department e-mail" WHERE category='Company' AND name='orders_department';
INSERT INTO xlite_config VALUES ('support_department','HelpDesk/Support service e-mail','bit-bucket@x-cart.com','Company',490,'text');
-- UPDATE xlite_config SET orderby='490', comment="HelpDesk/Support service e-mail" WHERE category='Company' AND name='support_department';
-- DELETE FROM xlite_config WHERE category='Company' AND name='newsletter_email';

-- Security

INSERT INTO xlite_config VALUES ('customer_security','Use HTTPS in the Customer Zone (for login, checkout and profile pages)','N','Security',0,'checkbox');
-- UPDATE xlite_config SET comment='Use HTTPS in the Customer Zone (for login, checkout and profile pages)' WHERE name = 'customer_security' AND category = 'Security';
INSERT INTO xlite_config VALUES ('admin_security','Use HTTPS in the Administrator Zone','N','Security',10,'checkbox');
-- UPDATE xlite_config SET orderby='10', comment='Use HTTPS in the Administrator Zone' WHERE name = 'admin_security' AND category = 'Security';
INSERT INTO xlite_config VALUES ('full_customer_security','Customer Zone fully on HTTPS','N','Security',5,'checkbox');
INSERT INTO xlite_config VALUES ('logoff_clear_cart','Clear cart on customer logoff','N','Security',10,'checkbox');
INSERT INTO xlite_config VALUES ('httpsClient','HTTPS client to use (for integration with secure payment/shipping services)','autodetect','Security',20,'select');
INSERT INTO xlite_config VALUES ('proxy','HTTPS proxy','','Security',25,'text');
-- UPDATE xlite_config SET orderby='20', comment='HTTPS client to use (for integration with secure payment/shipping services)' WHERE name = 'httpsClient' AND category = 'Security';
-- INSERT INTO xlite_config VALUES ('customer_password_hint','Use password hint to help customers recall forgotten passwords','N','Security',5,'checkbox');
INSERT INTO xlite_config VALUES ('allow_admin_ip','Allow admin IP','','SecurityIP',40,'');
INSERT INTO xlite_config VALUES ('form_id_protection','Enable admin forms protection system','Y','Security',90,'checkbox');
INSERT INTO xlite_config VALUES ('admin_ip_protection','Enable admin IP protection system','N','Security',100,'checkbox');
INSERT INTO xlite_config VALUES ('captcha_protection_system','Enable Captcha protection system','N','Security',110,'checkbox');
INSERT INTO xlite_config VALUES ('last_date','','0','Htaccess',0,'');
INSERT INTO xlite_config VALUES ('htaccess_protection','Enable .htaccess verification system','Y','Security',110,'checkbox');
-- Email

-- DELETE FROM xlite_config WHERE category='Email' AND name='show_cc_info';
INSERT INTO xlite_config VALUES ('enable_init_order_notif_customer','E-mail order details to customers after order placement','N','Email',0,'checkbox');
-- UPDATE xlite_config SET orderby='0', comment="E-mail order details to customers after order placement" WHERE category='Email' AND name='enable_init_order_notif_customer';
INSERT INTO xlite_config VALUES ('enable_init_order_notif','E-mail order details to the sales department after order placement','N','Email',10,'checkbox');
-- UPDATE xlite_config SET orderby='10', comment="E-mail order details to the sales department after order placement" WHERE category='Email' AND name='enable_init_order_notif';
INSERT INTO xlite_config VALUES ('valid_email_domains','Valid domain names for email','com;net;edu;mil;gov;org;biz','Email',30,'text');
-- UPDATE xlite_config SET orderby='30', comment='Valid domain names for email', value='com;net;edu;mil;gov;org;biz' WHERE category='Email' AND name='valid_email_domains';
INSERT INTO xlite_config VALUES ('show_cc_info','Include order details (credit card or eCheck information) into admin order notification message','N','Email',40,'checkbox');

--  SMTP server
INSERT INTO xlite_config VALUES('smtp_server','SMTP server','','Email',100,'separator');
INSERT INTO xlite_config VALUES('use_smtp','Use SMTP server','N','Email',110,'checkbox');
INSERT INTO xlite_config VALUES('smtp_server_url','SMTP server','','Email',120,'text');
INSERT INTO xlite_config VALUES('smtp_server_port','SMTP port','25','Email',130,'text');
INSERT INTO xlite_config VALUES('use_smtp_auth','Use authentication','N','Email',140,'checkbox');
INSERT INTO xlite_config VALUES('smtp_username','Username','','Email',150,'text');
INSERT INTO xlite_config VALUES('smtp_password','Password','','Email',160,'text');
INSERT INTO xlite_config VALUES('smtp_security','Secure connection','no','Email',170,'select');

-- Captcha
INSERT INTO xlite_config VALUES ('captcha_protection','Image generator options','','Captcha',0,'separator');
INSERT INTO xlite_config VALUES ('captcha_type','Type of string that should be used for the image','all','Captcha',10,'select');
INSERT INTO xlite_config VALUES ('captcha_length','Length of string','5','Captcha',20,'text');
INSERT INTO xlite_config VALUES ('captcha_separator_pages','Where to display','','Captcha',30,'separator');
INSERT INTO xlite_config VALUES ('active_captcha_pages','active_captcha_pages','','Captcha',30,'serialized');

INSERT INTO xlite_countries VALUES ('Afghanistan','AF','Dari, Pushtu','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Albania','AL','Albanian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Algeria','DZ','Arabic','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('American Samoa','AS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Andorra','AD','Catalan','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Angola','AO','Portuguese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Anguilla','AI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Antarctica','AQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Antigua and Barbuda','AG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Argentina','AR','Spanish','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Armenia','AM','Armenian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Aruba','AW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Australia','AU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Austria','AT','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Azerbaijan','AZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bahamas','BS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bahrain','BH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bangladesh','BD','Bengali','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Barbados','BB','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Belarus','BY','Belarussian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Belgium','BE','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Belize','BZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Benin','BJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bermuda','BM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bhutan','BT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bolivia','BO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bosnia and Herzegowina','BA','Bosnian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Botswana','BW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bouvet Island','BV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Brazil','BR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('British Indian Ocean Territory','IO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('British Virgin Islands','VG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Brunei Darussalam','BN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bulgaria','BG','Bulgarian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='BG';
INSERT INTO xlite_countries VALUES ('Burkina Faso','BF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Burundi','BI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cambodia','KH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cameroon','CM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Canada','CA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cape Verde','CV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cayman Islands','KY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Central African Republic','CF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Chad','TD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Chile','CL','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('China','CN','Chinese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Christmas Island','CX','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cocos (Keeling) Islands','CC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Colombia','CO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Comoros','KM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Congo, Democratic Republic of','CD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cook Islands','CK','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Costa Rica','CR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cote D\'ivoire','CI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Croatia','HR','Croatian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cuba','CU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cyprus','CY','Greek','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='CY';
INSERT INTO xlite_countries VALUES ('Czech Republic','CZ','Czech','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Czechoslovakia','CS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Denmark','DK','Danish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Djibouti','DJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Dominica','DM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Dominican Republic','DO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('East Timor','TP','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Ecuador','EC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Egypt','EG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('El Salvador','SV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Equatorial Guinea','GQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Eritrea','ER','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Estonia','EE','Estonian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='EE';
INSERT INTO xlite_countries VALUES ('Ethiopia','ET','Amharic','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Falkland Islands (Malvinas)','FK','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Faroe Islands','FO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Fiji','FJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Finland','FI','Finnish, Swedish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('France','FR','French','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('France, Metropolitan','FX','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('French Guiana','GF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('French Polynesia','PF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('French Southern Territories','TF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Gabon','GA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Gambia','GM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Georgia','GE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Germany','DE','German','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Ghana','GH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Gibraltar','GI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Greece','GR','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Greenland','GL','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Grenada','GD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guadeloupe','GP','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guam','GU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guatemala','GT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guinea','GN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guinea-Bissau','GW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guyana','GY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Haiti','HT','Creole','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Heard and McDonald Islands','HM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Honduras','HN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Hong Kong','HK','Mandarin','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Hungary','HU','Hungarian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='HU';
INSERT INTO xlite_countries VALUES ('Iceland','IS','Icelandic','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('India','IN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Indonesia','ID','Indonesian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Iraq','IQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Ireland','IE','Irish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Islamic Republic of Iran','IR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Israel','IL','Hebrew','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Italy','IT','Italian','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Jamaica','JM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Japan','JP','Japanese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Jordan','JO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kazakhstan','KZ','Kazakh','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kenya','KE','Kiswahili','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kiribati','KI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Korea','KP','Korean','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Korea, Republic of','KR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kuwait','KW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kyrgyzstan','KG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Laos','LA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Latvia','LV','Latvian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='LV';
INSERT INTO xlite_countries VALUES ('Lebanon','LB','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Lesotho','LS','Sesotho','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Liberia','LR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Libyan Arab Jamahiriya','LY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Liechtenstein','LI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Lithuania','LT','Lithuanian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='LT';
INSERT INTO xlite_countries VALUES ('Luxembourg','LU','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Macau','MO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Macedonia','MK','Macedonian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Madagascar','MG','Malagasy','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Malawi','MW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Malaysia','MY','Malay','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Maldives','MV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mali','ML','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Malta','MT','Maltese','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='MT';
INSERT INTO xlite_countries VALUES ('Marshall Islands','MH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Martinique','MQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mauritania','MR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mauritius','MU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mayotte','YT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mexico','MX','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Micronesia','FM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Moldova, Republic of','MD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Monaco','MC','','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='MC';
INSERT INTO xlite_countries VALUES ('Mongolia','MN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Montserrat','MS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Morocco','MA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mozambique','MZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Myanmar','MM','Burmese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Namibia','NA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nauru','NR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nepal','NP','Nepali','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Netherlands','NL','Dutch','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Netherlands Antilles','AN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('New Caledonia','NC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('New Zealand','NZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nicaragua','NI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Niger','NE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nigeria','NG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Niue','NU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Norfolk Island','NF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Northern Mariana Islands','MP','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Norway','NO','Norwegian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Oman','OM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Pakistan','PK','Urdu','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Palau','PW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Panama','PA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Papua New Guinea','PG','Pidgin','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Paraguay','PY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Peru','PE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Philippines','PH','Filipino','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Pitcairn','PN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Poland','PL','Polish','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='PL';
INSERT INTO xlite_countries VALUES ('Portugal','PT','Portuguese','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Puerto Rico','PR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Qatar','QA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Reunion','RE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Romania','RO','Romanian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='RO';
INSERT INTO xlite_countries VALUES ('Russian Federation','RU','Russian','Windows-1251',1,'N',0);
INSERT INTO xlite_countries VALUES ('Rwanda','RW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Saint Lucia','LC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Samoa','WS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('San Marino','SM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sao Tome and Principe','ST','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Saudi Arabia','SA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Senegal','SN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Seychelles','SC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sierra Leone','SL','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Singapore','SG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Slovakia','SK','Slovak','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='SK';
INSERT INTO xlite_countries VALUES ('Slovenia','SI','Slovene','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='SI';
INSERT INTO xlite_countries VALUES ('Solomon Islands','SB','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Somalia','SO','Somali','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('South Africa','ZA','Afrikaans','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Spain','ES','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Sri Lanka','LK','Sinhala','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Helena','SH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Kitts And Nevis','KN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Pierre and Miquelon','PM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Vincent And The Greadines','VC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sudan','SD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Suriname','SR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Svalbard and Jan Mayen Islands','SJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Swaziland','SZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sweden','SE','Swedish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Switzerland','CH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Syrian Arab Republic','SY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Taiwan','TW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tajikistan','TJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tanzania, United Republic of','TZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Thailand','TH','Thai','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Togo','TG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tokelau','TK','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tonga','TO','Tongan','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Trinidad and Tobago','TT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tunisia','TN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Turkey','TR','Turkish','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Turkmenistan','TM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Turks and Caicos Islands','TC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tuvalu','TV','Tuvaluan','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Uganda','UG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Ukraine','UA','Ukrainian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('United Arab Emirates','AE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('United Kingdom (Great Britain)','GB','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('United States','US','English','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('United States Virgin Islands','VI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Uruguay','UY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Uzbekistan','UZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Vanuatu','VU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Vatican City State','VA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Venezuela','VE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Viet Nam','VN','Vietnamese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Wallis And Futuna Islands','WF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Western Sahara','EH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Yemen','YE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Serbia and Montenegro','YU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Zambia','ZM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Zimbabwe','ZW','','iso-8859-1',1,'N',0);

INSERT INTO xlite_payment_methods VALUES ('CreditCard','Credit Card','Visa, Mastercard, American Express','CreditCard','',10,1);
INSERT INTO xlite_payment_methods VALUES ('PurchaseOrder','Purchase Order','','Offline','',20,1);
INSERT INTO xlite_payment_methods VALUES ('PhoneOrdering','Phone Ordering','Phone: (555) 555-5555','Offline','',30,1);
INSERT INTO xlite_payment_methods VALUES ('FaxOrdering','Fax Ordering','Fax: (555) 555-5555','Offline','',40,1);
INSERT INTO xlite_payment_methods VALUES ('MoneyOrdering','Money Order','US Banks Only','Offline','',45,1);
INSERT INTO xlite_payment_methods VALUES ('Echeck','Check','Check payment','Echeck','',50,1);
INSERT INTO xlite_payment_methods VALUES ('COD','COD','Cash On Delivery','Offline','',60,1);

INSERT INTO xlite_shipping VALUES (2,'Offline','L','National shipping',1,10);
INSERT INTO xlite_shipping VALUES (3,'Offline','I','International shipping',1,20);

INSERT INTO xlite_shipping_rates VALUES (-1,0.00,999999.00,0.00,999999.00,-1,0.00,0.00,0,0,0,99999);
