#! /usr/local/php-530/bin/php
<?php
/**
 * Example file - copy this file to /u/$USER/bin
 *
 * $Id: pear-phpunit 2805 2008-04-14 16:52:19Z sb $
 */

require_once dirname(__FILE__) . '/tests/local.php';

if (!defined('XLITE_DEV_LIB_DIR')) {
	    die('Constant "XLITE_DEV_LIB_DIR" isn\'t defined in tests/local.php script. Code coverage failed.');
}

$_files_to_include_into_path = array(
	'dbunit',
	'php-code-coverage',
	'php-file-iterator',
	'php-text-template',
	'php-timer',
	'php-token-stream',
	'phpunit',
	'phpunit-mock-objects',
	'phpunit-selenium',
);

foreach ($_files_to_include_into_path as $_file) {
	set_include_path(get_include_path() . PATH_SEPARATOR . sprintf('%s/%s/', XLITE_DEV_LIB_DIR, $_file));
}

@date_default_timezone_set(@date_default_timezone_get());

$lastParam = $_SERVER['argv'][count($_SERVER['argv']) - 1];

if (!preg_match('/AllTests.php$/Ss', $lastParam)) {

	// If LOCAL_TESTS is passed then it is supposed that tests are launched on working project
	// Else it's supposed that tests are launched for testing build (via ant) 
	if (preg_match('/(LOCAL_TESTS,?)/', $lastParam, $match)) {
		define('LOCAL_TESTS', true);
		$lastParam = str_replace($match[1], '', $lastParam);
	}
	
	if (!empty($lastParam)) {
		define('INCLUDE_ONLY_TESTS', $lastParam);
	}
}

require 'phpunit.php';

