#! /usr/local/php-530/bin/php
<?php
/**
 * Example file - copy this file to /u/$USER/bin
 *
 * $Id: pear-phpunit 2805 2008-04-14 16:52:19Z sb $
 */

set_include_path(get_include_path() . PATH_SEPARATOR . '/usr/local/share/pear/');
@date_default_timezone_set(@date_default_timezone_get());

require_once 'PHPUnit/Util/Filter.php';

PHPUnit_Util_Filter::addFileToFilter(__FILE__, 'PHPUNIT');

$lastParam = $_SERVER['argv'][count($_SERVER['argv']) - 1];

if (!preg_match('/AllTests.php$/Ss', $lastParam)) {

	// If LOCAL_TESTS is passed then it is supposed that tests are launched on working project
	// Else it's supposed that tests are launched for testing build (via ant) 
	if (preg_match('/(LOCAL_TESTS,?)/', $lastParam, $match)) {
		define('LOCAL_TESTS', true);
		$lastParam = str_replace($match[1], '', $lastParam);
	}
	
	if (!empty($lastParam)) {
		define('INCLUDE_ONLY_TESTS', $lastParam);
	}
}

require 'PHPUnit/TextUI/Command.php';
