ALTER TABLE xlite_modules CHANGE version version varchar(12) NOT NULL DEFAULT '0';
INSERT INTO xlite_config VALUES ('drop_catalog','Drop old catalog pages before building a new catalog','N','HTMLCatalog',10,'checkbox');
UPDATE xlite_config SET comment= 'Drop old catalog pages before building a new catalog' WHERE category='HTMLCatalog' AND name='drop_catalog';
INSERT INTO xlite_config VALUES ('catalog_category','Build HTML pages for category','','HTMLCatalog',20,'select');
INSERT INTO xlite_config VALUES ('catalog_pages','Build HTML pages for','both','HTMLCatalog',30,'select');
INSERT INTO xlite_config VALUES ('catalog_pages_count','Number of pages per one pass','20','HTMLCatalog',40,'select');
INSERT INTO xlite_config VALUES ('catalog_memory','Show memory usage diagnostics','N','HTMLCatalog',50,'checkbox');
UPDATE xlite_config SET comment= 'Show memory usage diagnostics' WHERE category='HTMLCatalog' AND name='catalog_memory';
INSERT INTO xlite_config VALUES ('category_name_format','Category file name format (*)','category_%cid_%cname%cpage.html','HTMLCatalog',60,'text');
INSERT INTO xlite_config VALUES ('category_page_format','Category page substring format (*)','_page_%page','HTMLCatalog',65,'text');
INSERT INTO xlite_config VALUES ('product_name_format','Product file name format (*)','product_%pid_%pname_cat_%cid.html','HTMLCatalog',70,'text');
