


INSERT INTO xlite_states VALUES (1,'Alabama','AL','US');
INSERT INTO xlite_states VALUES (2,'Alaska','AK','US');
INSERT INTO xlite_states VALUES (3,'Arizona','AZ','US');
INSERT INTO xlite_states VALUES (4,'Arkansas','AR','US');
INSERT INTO xlite_states VALUES (5,'California','CA','US');
INSERT INTO xlite_states VALUES (6,'Colorado','CO','US');
INSERT INTO xlite_states VALUES (7,'Connecticut','CT','US');
INSERT INTO xlite_states VALUES (8,'Delaware','DE','US');
INSERT INTO xlite_states VALUES (9,'District of Columbia','DC','US');
INSERT INTO xlite_states VALUES (10,'Florida','FL','US');
INSERT INTO xlite_states VALUES (11,'Georgia','GA','US');
INSERT INTO xlite_states VALUES (12,'Guam','GU','US');
INSERT INTO xlite_states VALUES (13,'Hawaii','HI','US');
INSERT INTO xlite_states VALUES (14,'Idaho','ID','US');
INSERT INTO xlite_states VALUES (15,'Illinois','IL','US');
INSERT INTO xlite_states VALUES (16,'Indiana','IN','US');
INSERT INTO xlite_states VALUES (17,'Iowa','IA','US');
INSERT INTO xlite_states VALUES (18,'Kansas','KS','US');
INSERT INTO xlite_states VALUES (19,'Kentucky','KY','US');
INSERT INTO xlite_states VALUES (20,'Louisiana','LA','US');
INSERT INTO xlite_states VALUES (21,'Maine','ME','US');
INSERT INTO xlite_states VALUES (22,'Maryland','MD','US');
INSERT INTO xlite_states VALUES (23,'Massachusetts','MA','US');
INSERT INTO xlite_states VALUES (24,'Michigan','MI','US');
INSERT INTO xlite_states VALUES (25,'Minnesota','MN','US');
INSERT INTO xlite_states VALUES (26,'Mississippi','MS','US');
INSERT INTO xlite_states VALUES (27,'Missouri','MO','US');
INSERT INTO xlite_states VALUES (28,'Montana','MT','US');
INSERT INTO xlite_states VALUES (29,'Nebraska','NE','US');
INSERT INTO xlite_states VALUES (30,'Nevada','NV','US');
INSERT INTO xlite_states VALUES (31,'New Hampshire','NH','US');
INSERT INTO xlite_states VALUES (32,'New Jersey','NJ','US');
INSERT INTO xlite_states VALUES (33,'New Mexico','NM','US');
INSERT INTO xlite_states VALUES (34,'New York','NY','US');
INSERT INTO xlite_states VALUES (35,'North Carolina','NC','US');
INSERT INTO xlite_states VALUES (36,'North Dakota','ND','US');
INSERT INTO xlite_states VALUES (37,'Ohio','OH','US');
INSERT INTO xlite_states VALUES (38,'Oklahoma','OK','US');
INSERT INTO xlite_states VALUES (39,'Oregon','OR','US');
INSERT INTO xlite_states VALUES (40,'Pennsylvania','PA','US');
INSERT INTO xlite_states VALUES (41,'Puerto Rico','PR','US');
INSERT INTO xlite_states VALUES (42,'Rhode Island','RI','US');
INSERT INTO xlite_states VALUES (43,'South Carolina','SC','US');
INSERT INTO xlite_states VALUES (44,'South Dakota','SD','US');
INSERT INTO xlite_states VALUES (45,'Tennessee','TN','US');
INSERT INTO xlite_states VALUES (46,'Texas','TX','US');
INSERT INTO xlite_states VALUES (47,'Utah','UT','US');
INSERT INTO xlite_states VALUES (48,'Vermont','VT','US');
INSERT INTO xlite_states VALUES (49,'Virgin Islands','VI','US');
INSERT INTO xlite_states VALUES (50,'Virginia','VA','US');
INSERT INTO xlite_states VALUES (51,'Washington','WA','US');
INSERT INTO xlite_states VALUES (52,'West Virginia','WV','US');
INSERT INTO xlite_states VALUES (53,'Wisconsin','WI','US');
INSERT INTO xlite_states VALUES (54,'Wyoming','WY','US');

