


INSERT INTO xlite_states VALUES (55,'Aberdeenshire','ABd',0,'GB');
INSERT INTO xlite_states VALUES (56,'Angus','AG',0,'GB');
INSERT INTO xlite_states VALUES (57,'Argyll','ARg',0,'GB');
INSERT INTO xlite_states VALUES (58,'Avon','AV',0,'GB');
INSERT INTO xlite_states VALUES (59,'Ayrshire','AY',0,'GB');
INSERT INTO xlite_states VALUES (60,'Banffshire','BF',0,'GB');
INSERT INTO xlite_states VALUES (61,'Bedfordshire','BE',0,'GB');
INSERT INTO xlite_states VALUES (62,'Berkshire','BK',0,'GB');
INSERT INTO xlite_states VALUES (63,'Buckinhamshire','BU',0,'GB');
INSERT INTO xlite_states VALUES (64,'Caithness','CN',0,'GB');
INSERT INTO xlite_states VALUES (65,'Cambridgeshire','CB',0,'GB');
INSERT INTO xlite_states VALUES (66,'Cheshire','CH',0,'GB');
INSERT INTO xlite_states VALUES (67,'Clackmannanshire','CL',0,'GB');
INSERT INTO xlite_states VALUES (68,'Cleveland','CV',0,'GB');
INSERT INTO xlite_states VALUES (69,'Clwyd','CW',0,'GB');
INSERT INTO xlite_states VALUES (70,'County Antrim','CAn',0,'GB');
INSERT INTO xlite_states VALUES (71,'County Armagh','CAr',0,'GB');
INSERT INTO xlite_states VALUES (72,'County Down','CDo',0,'GB');
INSERT INTO xlite_states VALUES (73,'County Durham','CDu',0,'GB');
INSERT INTO xlite_states VALUES (74,'County Fermanagh','CFm',0,'GB');
INSERT INTO xlite_states VALUES (75,'County Londonderry','CLd',0,'GB');
INSERT INTO xlite_states VALUES (76,'County Tyrone','CTy',0,'GB');
INSERT INTO xlite_states VALUES (77,'Cornwall','COr',0,'GB');
INSERT INTO xlite_states VALUES (78,'Cumbria','CU',0,'GB');
INSERT INTO xlite_states VALUES (79,'Derbyshire','DB',0,'GB');
INSERT INTO xlite_states VALUES (80,'Devon','DV',0,'GB');
INSERT INTO xlite_states VALUES (81,'Dorset','DO',0,'GB');
INSERT INTO xlite_states VALUES (82,'Dumfriesshire','DF',0,'GB');
INSERT INTO xlite_states VALUES (83,'Dunbartonshire','DU',0,'GB');
INSERT INTO xlite_states VALUES (84,'Dyfed','DY',0,'GB');
INSERT INTO xlite_states VALUES (85,'East Lothian','EL',0,'GB');
INSERT INTO xlite_states VALUES (86,'East Sussex','ES',0,'GB');
INSERT INTO xlite_states VALUES (87,'Essex','EX',0,'GB');
INSERT INTO xlite_states VALUES (88,'Fife','FI',0,'GB');
INSERT INTO xlite_states VALUES (89,'Gloucestershire','GL',0,'GB');
INSERT INTO xlite_states VALUES (90,'Gwent','GW',0,'GB');
INSERT INTO xlite_states VALUES (91,'Gwyedd','GY',0,'GB');
INSERT INTO xlite_states VALUES (92,'Hampshire','HA',0,'GB');
INSERT INTO xlite_states VALUES (93,'Herefordshire','HE',0,'GB');
INSERT INTO xlite_states VALUES (94,'Hertfordshire','HF',0,'GB');
INSERT INTO xlite_states VALUES (95,'Inverness-shire','IS',0,'GB');
INSERT INTO xlite_states VALUES (96,'Isle of Arran','IsAr',0,'GB');
INSERT INTO xlite_states VALUES (97,'Isle of Barra','IsBa',0,'GB');
INSERT INTO xlite_states VALUES (98,'Isle of Benbecula','IsBe',0,'GB');
INSERT INTO xlite_states VALUES (99,'Isle of Bute','IsBu',0,'GB');
INSERT INTO xlite_states VALUES (100,'Isle of Canna','IsCa',0,'GB');
INSERT INTO xlite_states VALUES (101,'Isle of Coll','IsCo',0,'GB');
INSERT INTO xlite_states VALUES (102,'Isle of Colonsay','IsCl',0,'GB');
INSERT INTO xlite_states VALUES (103,'Isle of Cumbrae','IsCu',0,'GB');
INSERT INTO xlite_states VALUES (104,'Isle of Eigg','IsEg',0,'GB');
INSERT INTO xlite_states VALUES (105,'Isle of Gigha','IsGi',0,'GB');
INSERT INTO xlite_states VALUES (106,'Isle of Harris','IsHa',0,'GB');
INSERT INTO xlite_states VALUES (107,'Isle of Iona','IsIo',0,'GB');
INSERT INTO xlite_states VALUES (108,'Isle of Jura','IsJu',0,'GB');
INSERT INTO xlite_states VALUES (109,'Isle of Lewis','IsLw',0,'GB');
INSERT INTO xlite_states VALUES (110,'Isle of Mull','IsMu',0,'GB');
INSERT INTO xlite_states VALUES (111,'Isle of North Uist','IsNu',0,'GB');
INSERT INTO xlite_states VALUES (112,'Buckinghamshire','BKM',0,'GB');
INSERT INTO xlite_states VALUES (113,'Cumberland','CUL',0,'GB');
INSERT INTO xlite_states VALUES (114,'Huntingdonshire','HUN',0,'GB');
INSERT INTO xlite_states VALUES (115,'Kent','KEN',0,'GB');
INSERT INTO xlite_states VALUES (116,'Lancashire','LAN',0,'GB');
INSERT INTO xlite_states VALUES (117,'Leicestershire','LEI',0,'GB');
INSERT INTO xlite_states VALUES (118,'Lincolnshire','LIN',0,'GB');
INSERT INTO xlite_states VALUES (119,'Middlesex','MX',0,'GB');
INSERT INTO xlite_states VALUES (120,'Norfolk','NO',0,'GB');
INSERT INTO xlite_states VALUES (121,'Northamptonshire','NTH',0,'GB');
INSERT INTO xlite_states VALUES (122,'Northumberland','NU',0,'GB');
INSERT INTO xlite_states VALUES (123,'Nottinghamshire','NTT',0,'GB');
INSERT INTO xlite_states VALUES (124,'Oxfordshire','OX',0,'GB');
INSERT INTO xlite_states VALUES (125,'Rutland','RUT',0,'GB');
INSERT INTO xlite_states VALUES (126,'Shropshire','SR',0,'GB');
INSERT INTO xlite_states VALUES (127,'Somerset','SO',0,'GB');
INSERT INTO xlite_states VALUES (128,'Staffordshire','ST',0,'GB');
INSERT INTO xlite_states VALUES (129,'Suffolk','SF',0,'GB');
INSERT INTO xlite_states VALUES (130,'Surrey','SY',0,'GB');
INSERT INTO xlite_states VALUES (131,'Sussex','SU',0,'GB');
INSERT INTO xlite_states VALUES (132,'Warwickshire','WAR',0,'GB');
INSERT INTO xlite_states VALUES (133,'Westmorland','WES',0,'GB');
INSERT INTO xlite_states VALUES (134,'Wiltshire','WIt',0,'GB');
INSERT INTO xlite_states VALUES (135,'Worcestershire','WO',0,'GB');
INSERT INTO xlite_states VALUES (136,'Yorkshire','YKS',0,'GB');
INSERT INTO xlite_states VALUES (137,'Anglesey','AGY',0,'GB');
INSERT INTO xlite_states VALUES (138,'Carmarthenshire','CMN',0,'GB');
INSERT INTO xlite_states VALUES (139,'Cardiganshire','CGN',0,'GB');
INSERT INTO xlite_states VALUES (140,'Denbighshire','DEN',0,'GB');
INSERT INTO xlite_states VALUES (141,'Flintshire','FLN',0,'GB');
INSERT INTO xlite_states VALUES (142,'Glamorgan','GLA',0,'GB');
INSERT INTO xlite_states VALUES (143,'Monmouthshire','MON',0,'GB');
INSERT INTO xlite_states VALUES (144,'Montgomeryshire','MGY',0,'GB');
INSERT INTO xlite_states VALUES (145,'Pembrokeshire','PEM',0,'GB');
INSERT INTO xlite_states VALUES (146,'Radnorshire','RAD',0,'GB');
INSERT INTO xlite_states VALUES (147,'Berwickshire','BEW',0,'GB');
INSERT INTO xlite_states VALUES (148,'Kincardineshire','KCD',0,'GB');
INSERT INTO xlite_states VALUES (149,'Kinross-shire','KRS',0,'GB');
INSERT INTO xlite_states VALUES (150,'Kirkcudbrightshire','KKD',0,'GB');
INSERT INTO xlite_states VALUES (151,'Lanarkshire','LKS',0,'GB');
INSERT INTO xlite_states VALUES (152,'Midlothian','Mdl',0,'GB');
INSERT INTO xlite_states VALUES (153,'Morayshire','MOR',0,'GB');
INSERT INTO xlite_states VALUES (154,'Orkney','OKI',0,'GB');
INSERT INTO xlite_states VALUES (155,'Peebles-shire','PEE',0,'GB');
INSERT INTO xlite_states VALUES (156,'Perth','PER',0,'GB');
INSERT INTO xlite_states VALUES (157,'Renfrewshire','Rn',0,'GB');
INSERT INTO xlite_states VALUES (158,'Ross and Cromarty','ROC',0,'GB');
INSERT INTO xlite_states VALUES (159,'Roxburghshire','ROX',0,'GB');
INSERT INTO xlite_states VALUES (160,'Selkirkshire','SEL',0,'GB');
INSERT INTO xlite_states VALUES (161,'Shetland','SHI',0,'GB');
INSERT INTO xlite_states VALUES (162,'Stirlingshire','STI',0,'GB');
INSERT INTO xlite_states VALUES (163,'Sutherland','SUT',0,'GB');
INSERT INTO xlite_states VALUES (164,'West Lothian','WLN',0,'GB');
INSERT INTO xlite_states VALUES (165,'Wigtownshire','WIG',0,'GB');
INSERT INTO xlite_states VALUES (166,'Isle of Rhum','IsRu',0,'GB');
INSERT INTO xlite_states VALUES (167,'Isle of Scalpay','IsSc',0,'GB');
INSERT INTO xlite_states VALUES (168,'Isle of Shetland','IsSh',0,'GB');
INSERT INTO xlite_states VALUES (169,'Isle of Skye','IsSk',0,'GB');
INSERT INTO xlite_states VALUES (170,'Isle of South Uist','IsSu',0,'GB');
INSERT INTO xlite_states VALUES (171,'Isle of Tiree','IsTi',0,'GB');
INSERT INTO xlite_states VALUES (172,'Isle of Wight','IsWi',0,'GB');
INSERT INTO xlite_states VALUES (173,'Isles of Scilly','IsScl',0,'GB');
INSERT INTO xlite_states VALUES (174,'London','LO',0,'GB');
INSERT INTO xlite_states VALUES (175,'Merseyside','MER',0,'GB');
INSERT INTO xlite_states VALUES (176,'Mid Glamorgan','MG',0,'GB');
INSERT INTO xlite_states VALUES (177,'Nairnshire','NA',0,'GB');
INSERT INTO xlite_states VALUES (178,'North Humberside','NHB',0,'GB');
INSERT INTO xlite_states VALUES (179,'North Yorkshire','NYK',0,'GB');
INSERT INTO xlite_states VALUES (180,'Powys','PO',0,'GB');
INSERT INTO xlite_states VALUES (181,'South Glamorgan','SG',0,'GB');
INSERT INTO xlite_states VALUES (182,'South Humberside','SH',0,'GB');
INSERT INTO xlite_states VALUES (183,'South Yorkshire','SYK',0,'GB');
INSERT INTO xlite_states VALUES (184,'Tyne & Wear','TW',0,'GB');
INSERT INTO xlite_states VALUES (185,'West Glamorgan','WG',0,'GB');
INSERT INTO xlite_states VALUES (186,'West Midlands','WM',0,'GB');
INSERT INTO xlite_states VALUES (187,'West Sussex','WS',0,'GB');
INSERT INTO xlite_states VALUES (188,'West Yorkshire','WYK',0,'GB');

