


INSERT INTO xlite_states VALUES (55,'Aberdeenshire','ABd','GB');
INSERT INTO xlite_states VALUES (56,'Angus','AG','GB');
INSERT INTO xlite_states VALUES (57,'Argyll','ARg','GB');
INSERT INTO xlite_states VALUES (58,'Avon','AV','GB');
INSERT INTO xlite_states VALUES (59,'Ayrshire','AY','GB');
INSERT INTO xlite_states VALUES (60,'Banffshire','BF','GB');
INSERT INTO xlite_states VALUES (61,'Bedfordshire','BE','GB');
INSERT INTO xlite_states VALUES (62,'Berkshire','BK','GB');
INSERT INTO xlite_states VALUES (63,'Buckinhamshire','BU','GB');
INSERT INTO xlite_states VALUES (64,'Caithness','CN','GB');
INSERT INTO xlite_states VALUES (65,'Cambridgeshire','CB','GB');
INSERT INTO xlite_states VALUES (66,'Cheshire','CH','GB');
INSERT INTO xlite_states VALUES (67,'Clackmannanshire','CL','GB');
INSERT INTO xlite_states VALUES (68,'Cleveland','CV','GB');
INSERT INTO xlite_states VALUES (69,'Clwyd','CW','GB');
INSERT INTO xlite_states VALUES (70,'County Antrim','CAn','GB');
INSERT INTO xlite_states VALUES (71,'County Armagh','CAr','GB');
INSERT INTO xlite_states VALUES (72,'County Down','CDo','GB');
INSERT INTO xlite_states VALUES (73,'County Durham','CDu','GB');
INSERT INTO xlite_states VALUES (74,'County Fermanagh','CFm','GB');
INSERT INTO xlite_states VALUES (75,'County Londonderry','CLd','GB');
INSERT INTO xlite_states VALUES (76,'County Tyrone','CTy','GB');
INSERT INTO xlite_states VALUES (77,'Cornwall','COr','GB');
INSERT INTO xlite_states VALUES (78,'Cumbria','CU','GB');
INSERT INTO xlite_states VALUES (79,'Derbyshire','DB','GB');
INSERT INTO xlite_states VALUES (80,'Devon','DV','GB');
INSERT INTO xlite_states VALUES (81,'Dorset','DO','GB');
INSERT INTO xlite_states VALUES (82,'Dumfriesshire','DF','GB');
INSERT INTO xlite_states VALUES (83,'Dunbartonshire','DU','GB');
INSERT INTO xlite_states VALUES (84,'Dyfed','DY','GB');
INSERT INTO xlite_states VALUES (85,'East Lothian','EL','GB');
INSERT INTO xlite_states VALUES (86,'East Sussex','ES','GB');
INSERT INTO xlite_states VALUES (87,'Essex','EX','GB');
INSERT INTO xlite_states VALUES (88,'Fife','FI','GB');
INSERT INTO xlite_states VALUES (89,'Gloucestershire','GL','GB');
INSERT INTO xlite_states VALUES (90,'Gwent','GW','GB');
INSERT INTO xlite_states VALUES (91,'Gwyedd','GY','GB');
INSERT INTO xlite_states VALUES (92,'Hampshire','HA','GB');
INSERT INTO xlite_states VALUES (93,'Herefordshire','HE','GB');
INSERT INTO xlite_states VALUES (94,'Hertfordshire','HF','GB');
INSERT INTO xlite_states VALUES (95,'Inverness-shire','IS','GB');
INSERT INTO xlite_states VALUES (96,'Isle of Arran','IsAr','GB');
INSERT INTO xlite_states VALUES (97,'Isle of Barra','IsBa','GB');
INSERT INTO xlite_states VALUES (98,'Isle of Benbecula','IsBe','GB');
INSERT INTO xlite_states VALUES (99,'Isle of Bute','IsBu','GB');
INSERT INTO xlite_states VALUES (100,'Isle of Canna','IsCa','GB');
INSERT INTO xlite_states VALUES (101,'Isle of Coll','IsCo','GB');
INSERT INTO xlite_states VALUES (102,'Isle of Colonsay','IsCl','GB');
INSERT INTO xlite_states VALUES (103,'Isle of Cumbrae','IsCu','GB');
INSERT INTO xlite_states VALUES (104,'Isle of Eigg','IsEg','GB');
INSERT INTO xlite_states VALUES (105,'Isle of Gigha','IsGi','GB');
INSERT INTO xlite_states VALUES (106,'Isle of Harris','IsHa','GB');
INSERT INTO xlite_states VALUES (107,'Isle of Iona','IsIo','GB');
INSERT INTO xlite_states VALUES (108,'Isle of Jura','IsJu','GB');
INSERT INTO xlite_states VALUES (109,'Isle of Lewis','IsLw','GB');
INSERT INTO xlite_states VALUES (110,'Isle of Mull','IsMu','GB');
INSERT INTO xlite_states VALUES (111,'Isle of North Uist','IsNu','GB');
INSERT INTO xlite_states VALUES (112,'Buckinghamshire','BKM','GB');
INSERT INTO xlite_states VALUES (113,'Cumberland','CUL','GB');
INSERT INTO xlite_states VALUES (114,'Huntingdonshire','HUN','GB');
INSERT INTO xlite_states VALUES (115,'Kent','KEN','GB');
INSERT INTO xlite_states VALUES (116,'Lancashire','LAN','GB');
INSERT INTO xlite_states VALUES (117,'Leicestershire','LEI','GB');
INSERT INTO xlite_states VALUES (118,'Lincolnshire','LIN','GB');
INSERT INTO xlite_states VALUES (119,'Middlesex','MX','GB');
INSERT INTO xlite_states VALUES (120,'Norfolk','NO','GB');
INSERT INTO xlite_states VALUES (121,'Northamptonshire','NTH','GB');
INSERT INTO xlite_states VALUES (122,'Northumberland','NU','GB');
INSERT INTO xlite_states VALUES (123,'Nottinghamshire','NTT','GB');
INSERT INTO xlite_states VALUES (124,'Oxfordshire','OX','GB');
INSERT INTO xlite_states VALUES (125,'Rutland','RUT','GB');
INSERT INTO xlite_states VALUES (126,'Shropshire','SR','GB');
INSERT INTO xlite_states VALUES (127,'Somerset','SO','GB');
INSERT INTO xlite_states VALUES (128,'Staffordshire','ST','GB');
INSERT INTO xlite_states VALUES (129,'Suffolk','SF','GB');
INSERT INTO xlite_states VALUES (130,'Surrey','SY','GB');
INSERT INTO xlite_states VALUES (131,'Sussex','SU','GB');
INSERT INTO xlite_states VALUES (132,'Warwickshire','WAR','GB');
INSERT INTO xlite_states VALUES (133,'Westmorland','WES','GB');
INSERT INTO xlite_states VALUES (134,'Wiltshire','WIt','GB');
INSERT INTO xlite_states VALUES (135,'Worcestershire','WO','GB');
INSERT INTO xlite_states VALUES (136,'Yorkshire','YKS','GB');
INSERT INTO xlite_states VALUES (137,'Anglesey','AGY','GB');
INSERT INTO xlite_states VALUES (138,'Carmarthenshire','CMN','GB');
INSERT INTO xlite_states VALUES (139,'Cardiganshire','CGN','GB');
INSERT INTO xlite_states VALUES (140,'Denbighshire','DEN','GB');
INSERT INTO xlite_states VALUES (141,'Flintshire','FLN','GB');
INSERT INTO xlite_states VALUES (142,'Glamorgan','GLA','GB');
INSERT INTO xlite_states VALUES (143,'Monmouthshire','MON','GB');
INSERT INTO xlite_states VALUES (144,'Montgomeryshire','MGY','GB');
INSERT INTO xlite_states VALUES (145,'Pembrokeshire','PEM','GB');
INSERT INTO xlite_states VALUES (146,'Radnorshire','RAD','GB');
INSERT INTO xlite_states VALUES (147,'Berwickshire','BEW','GB');
INSERT INTO xlite_states VALUES (148,'Kincardineshire','KCD','GB');
INSERT INTO xlite_states VALUES (149,'Kinross-shire','KRS','GB');
INSERT INTO xlite_states VALUES (150,'Kirkcudbrightshire','KKD','GB');
INSERT INTO xlite_states VALUES (151,'Lanarkshire','LKS','GB');
INSERT INTO xlite_states VALUES (152,'Midlothian','Mdl','GB');
INSERT INTO xlite_states VALUES (153,'Morayshire','MOR','GB');
INSERT INTO xlite_states VALUES (154,'Orkney','OKI','GB');
INSERT INTO xlite_states VALUES (155,'Peebles-shire','PEE','GB');
INSERT INTO xlite_states VALUES (156,'Perth','PER','GB');
INSERT INTO xlite_states VALUES (157,'Renfrewshire','Rn','GB');
INSERT INTO xlite_states VALUES (158,'Ross and Cromarty','ROC','GB');
INSERT INTO xlite_states VALUES (159,'Roxburghshire','ROX','GB');
INSERT INTO xlite_states VALUES (160,'Selkirkshire','SEL','GB');
INSERT INTO xlite_states VALUES (161,'Shetland','SHI','GB');
INSERT INTO xlite_states VALUES (162,'Stirlingshire','STI','GB');
INSERT INTO xlite_states VALUES (163,'Sutherland','SUT','GB');
INSERT INTO xlite_states VALUES (164,'West Lothian','WLN','GB');
INSERT INTO xlite_states VALUES (165,'Wigtownshire','WIG','GB');
INSERT INTO xlite_states VALUES (166,'Isle of Rhum','IsRu','GB');
INSERT INTO xlite_states VALUES (167,'Isle of Scalpay','IsSc','GB');
INSERT INTO xlite_states VALUES (168,'Isle of Shetland','IsSh','GB');
INSERT INTO xlite_states VALUES (169,'Isle of Skye','IsSk','GB');
INSERT INTO xlite_states VALUES (170,'Isle of South Uist','IsSu','GB');
INSERT INTO xlite_states VALUES (171,'Isle of Tiree','IsTi','GB');
INSERT INTO xlite_states VALUES (172,'Isle of Wight','IsWi','GB');
INSERT INTO xlite_states VALUES (173,'Isles of Scilly','IsScl','GB');
INSERT INTO xlite_states VALUES (174,'London','LO','GB');
INSERT INTO xlite_states VALUES (175,'Merseyside','MER','GB');
INSERT INTO xlite_states VALUES (176,'Mid Glamorgan','MG','GB');
INSERT INTO xlite_states VALUES (177,'Nairnshire','NA','GB');
INSERT INTO xlite_states VALUES (178,'North Humberside','NHB','GB');
INSERT INTO xlite_states VALUES (179,'North Yorkshire','NYK','GB');
INSERT INTO xlite_states VALUES (180,'Powys','PO','GB');
INSERT INTO xlite_states VALUES (181,'South Glamorgan','SG','GB');
INSERT INTO xlite_states VALUES (182,'South Humberside','SH','GB');
INSERT INTO xlite_states VALUES (183,'South Yorkshire','SYK','GB');
INSERT INTO xlite_states VALUES (184,'Tyne & Wear','TW','GB');
INSERT INTO xlite_states VALUES (185,'West Glamorgan','WG','GB');
INSERT INTO xlite_states VALUES (186,'West Midlands','WM','GB');
INSERT INTO xlite_states VALUES (187,'West Sussex','WS','GB');
INSERT INTO xlite_states VALUES (188,'West Yorkshire','WYK','GB');

