INSERT INTO `xlite_config` VALUES (2,'active_captcha_pages','Captcha','serialized',30,'');
INSERT INTO `xlite_config` VALUES (3,'add_on_mode','General','checkbox',120,'N');
INSERT INTO `xlite_config` VALUES (4,'add_on_mode_page','General','select',125,'cart.php?target=cart');
INSERT INTO `xlite_config` VALUES (5,'admin_ip_protection','Security','checkbox',100,'N');
INSERT INTO `xlite_config` VALUES (6,'admin_presentation','General','separator',400,'');
INSERT INTO `xlite_config` VALUES (9,'admin_security','Security','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (12,'allow_admin_ip','SecurityIP','',40,'');
INSERT INTO `xlite_config` VALUES (27,'buynow_button_enabled','General','checkbox',240,'Y');
-- INSERT INTO `xlite_config` VALUES (29,'callback_code','Shipping','text',0,'');
-- INSERT INTO `xlite_config` VALUES (30,'callback_status','Shipping','text',0,'');
INSERT INTO `xlite_config` VALUES (31,'captcha_length','Captcha','text',20,'5');
INSERT INTO `xlite_config` VALUES (32,'captcha_protection','Captcha','separator',0,'');
INSERT INTO `xlite_config` VALUES (33,'captcha_protection_system','Security','checkbox',110,'N');
INSERT INTO `xlite_config` VALUES (34,'captcha_separator_pages','Captcha','separator',30,'');
INSERT INTO `xlite_config` VALUES (35,'captcha_type','Captcha','select',10,'all');
INSERT INTO `xlite_config` VALUES (38,'clear_cc_info','General','select',500,'N');
INSERT INTO `xlite_config` VALUES (46,'company_address','Company','separator',385,'');
INSERT INTO `xlite_config` VALUES (47,'company_contacts','Company','separator',455,'');
INSERT INTO `xlite_config` VALUES (48,'company_fax','Company','text',420,'(555) 555-5555');
INSERT INTO `xlite_config` VALUES (49,'company_identity','Company','separator',350,'');
INSERT INTO `xlite_config` VALUES (50,'company_name','Company','text',360,'*Your company name*');
INSERT INTO `xlite_config` VALUES (51,'company_phone','Company','text',410,'(555) 555-5555');
INSERT INTO `xlite_config` VALUES (52,'company_website','Company','text',370,'http://');
INSERT INTO `xlite_config` VALUES (65,'customer_presentation','General','separator',200,'');
INSERT INTO `xlite_config` VALUES (66,'customer_security','Security','checkbox',0,'Y');
INSERT INTO `xlite_config` VALUES (67,'date_format','General','select',660,'%b %d, %Y');
INSERT INTO `xlite_config` VALUES (68,'decimal_delim','General','select',650,'.');
INSERT INTO `xlite_config` VALUES (70,'defaultSources','Images','serialized',0,'');
INSERT INTO `xlite_config` VALUES (71,'default_country','General','country',310,'US');
INSERT INTO `xlite_config` VALUES (72,'default_offline_payment','Payments','text',0,'');
INSERT INTO `xlite_config` VALUES (74,'default_purchase_limit','General','text',293,'9999');
INSERT INTO `xlite_config` VALUES (75,'default_select_payment','Payments','text',0,'');
INSERT INTO `xlite_config` VALUES (76,'default_zipcode','General','text',320,'10000');
INSERT INTO `xlite_config` VALUES (89,'direct_product_url','General','checkbox',255,'N');
INSERT INTO `xlite_config` VALUES (90,'discounts_after_taxes','Taxes','checkbox',210,'N');
INSERT INTO `xlite_config` VALUES (91,'display_check_number','General','checkbox',215,'Y');
INSERT INTO `xlite_config` VALUES (100,'enable_anon_checkout','General','checkbox',270,'Y');
INSERT INTO `xlite_config` VALUES (101,'enable_categories_extra_fields','General','checkbox',470,'Y');
INSERT INTO `xlite_config` VALUES (102,'enable_credit_card_validation','General','checkbox',210,'Y');
INSERT INTO `xlite_config` VALUES (103,'enable_extra_fields_inherit','General','checkbox',480,'Y');
INSERT INTO `xlite_config` VALUES (104,'enable_init_order_notif','Email','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (105,'enable_init_order_notif_customer','Email','checkbox',0,'N');
INSERT INTO `xlite_config` VALUES (107,'enable_sale_price','General','checkbox',295,'Y');
INSERT INTO `xlite_config` VALUES (120,'form_id_protection','Security','checkbox',90,'Y');
INSERT INTO `xlite_config` VALUES (128,'full_customer_security','Security','checkbox',5,'N');
INSERT INTO `xlite_config` VALUES (138,'htaccess_protection','Security','checkbox',110,'Y');
INSERT INTO `xlite_config` VALUES (140,'httpsClient','Security','select',20,'autodetect');
INSERT INTO `xlite_config` VALUES (141,'include_tax_message','Taxes','text',0,', including VAT');
INSERT INTO `xlite_config` VALUES (145,'last_date','Htaccess','',0,'0');
INSERT INTO `xlite_config` VALUES (151,'license','License','text',0,'');
INSERT INTO `xlite_config` VALUES (153,'location_address','Company','text',390,'*Your company address*');
INSERT INTO `xlite_config` VALUES (154,'location_city','Company','text',400,'*You company city*');
INSERT INTO `xlite_config` VALUES (155,'location_country','Company','country',450,'US');
INSERT INTO `xlite_config` VALUES (156,'location_custom_state','Company','text',435,'');
INSERT INTO `xlite_config` VALUES (157,'location_state','Company','state',430,'17');
INSERT INTO `xlite_config` VALUES (158,'location_zipcode','Company','text',440,'50001');
INSERT INTO `xlite_config` VALUES (159,'login_lifetime','General','text',450,'3');
INSERT INTO `xlite_config` VALUES (160,'logoff_clear_cart','Security','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (165,'maximal_order_amount','General','text',290,'99999');
INSERT INTO `xlite_config` VALUES (166,'memberships','Memberships','serialized',0,'a:0:{}');
INSERT INTO `xlite_config` VALUES (167,'membershipsCollection','Memberships','serialized',0,'a:3:{i:1;a:3:{s:7:\"orderby\";s:2:\"10\";s:10:\"membership\";s:4:\"Gold\";s:13:\"membership_id\";i:1;}i:2;a:3:{s:7:\"orderby\";s:2:\"20\";s:10:\"membership\";s:8:\"Platinum\";s:13:\"membership_id\";i:2;}i:3;a:3:{s:7:\"orderby\";s:2:\"30\";s:10:\"membership\";s:10:\"Wholesaler\";s:13:\"membership_id\";i:3;}}');
INSERT INTO `xlite_config` VALUES (170,'minimal_order_amount','General','text',280,'10');
INSERT INTO `xlite_config` VALUES (179,'operation_presentation','General','separator',100,'');
INSERT INTO `xlite_config` VALUES (180,'orders_department','Company','text',480,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (181,'orders_per_page','General','text',430,'30');
INSERT INTO `xlite_config` VALUES (182,'order_starting_number','General','text',460,'1');
INSERT INTO `xlite_config` VALUES (197,'params','XCartImport','serialized',0,'a:0:{}');
INSERT INTO `xlite_config` VALUES (199,'partner_product_banner','Miscellaneous','serialized',0,'a:11:{s:11:\"link_target\";s:4:\"_top\";s:5:\"image\";s:9:\"thumbnail\";s:6:\"border\";i:1;s:12:\"product_name\";i:1;s:11:\"description\";s:0:\"\";s:7:\"message\";s:8:\"Buy new!\";s:16:\"background_color\";s:6:\"ffffff\";s:10:\"text_color\";s:6:\"000000\";s:10:\"link_color\";s:6:\"6633ff\";s:5:\"width\";i:120;s:6:\"height\";i:240;}');
INSERT INTO `xlite_config` VALUES (200,'partner_profile','Miscellaneous','serialized',0,'a:8:{s:17:\"billing_firstname\";s:2:\"on\";s:16:\"billing_lastname\";s:2:\"on\";s:13:\"billing_phone\";s:2:\"on\";s:15:\"billing_address\";s:2:\"on\";s:12:\"billing_city\";s:2:\"on\";s:13:\"billing_state\";s:2:\"on\";s:15:\"billing_country\";s:2:\"on\";s:15:\"billing_zipcode\";s:2:\"on\";}');
INSERT INTO `xlite_config` VALUES (205,'prices_include_tax','Taxes','checkbox',200,'N');
INSERT INTO `xlite_config` VALUES (207,'price_format','General','text',630,'$ %s');
INSERT INTO `xlite_config` VALUES (210,'products_per_page','General','text',250,'10');
INSERT INTO `xlite_config` VALUES (211,'products_per_page_admin','General','text',410,'10');
INSERT INTO `xlite_config` VALUES (212,'product_layout','ImportExport',NULL,0,'sku,name,category,brief_description,description,price,tax_class,weight,order_by,enabled,NULL');
INSERT INTO `xlite_config` VALUES (214,'proxy','Security','text',25,'');
INSERT INTO `xlite_config` VALUES (216,'recent_orders','General','text',440,'10');
INSERT INTO `xlite_config` VALUES (217,'redirect_to_cart','General','checkbox',300,'Y');
INSERT INTO `xlite_config` VALUES (228,'safe_mode','General','checkbox',130,'N');
-- INSERT INTO `xlite_config` VALUES (233,'shipping_code','Shipping','text',0,'1702936249');
INSERT INTO `xlite_config` VALUES (234,'shop_closed','General','checkbox',110,'N');
INSERT INTO `xlite_config` VALUES (236,'show_cc_info','Email','checkbox',40,'N');
INSERT INTO `xlite_config` VALUES (237,'show_thumbnails','General','checkbox',230,'Y');
INSERT INTO `xlite_config` VALUES (238,'site_administrator','Company','text',460,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (239,'smtp_password','Email','text',160,'');
INSERT INTO `xlite_config` VALUES (240,'smtp_security','Email','select',170,'no');
INSERT INTO `xlite_config` VALUES (241,'smtp_server','Email','separator',100,'');
INSERT INTO `xlite_config` VALUES (242,'smtp_server_port','Email','text',130,'25');
INSERT INTO `xlite_config` VALUES (243,'smtp_server_url','Email','text',120,'');
INSERT INTO `xlite_config` VALUES (244,'smtp_username','Email','text',150,'');
INSERT INTO `xlite_config` VALUES (245,'start_year','Company','text',380,'2009');
INSERT INTO `xlite_config` VALUES (247,'subcategories_look','General','select',220,'icons');
INSERT INTO `xlite_config` VALUES (248,'support_department','Company','text',490,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (249,'taxes','Taxes','text',0,'a:1:{i:0;a:2:{s:4:\"name\";s:3:\"Tax\";s:13:\"display_label\";s:3:\"Tax\";}}');
INSERT INTO `xlite_config` VALUES (250,'tax_rates','Taxes','',20,'a:3:{i:0;s:6:\"Tax:=0\";i:1;a:2:{s:9:\"condition\";s:30:\"product class=shipping service\";s:6:\"action\";s:6:\"Tax:=0\";}i:2;a:2:{s:9:\"condition\";s:22:\"product class=Tax free\";s:6:\"action\";s:6:\"Tax:=0\";}}');
INSERT INTO `xlite_config` VALUES (252,'thousand_delim','General','select',640,',');
INSERT INTO `xlite_config` VALUES (255,'time_format','General','select',670,'%H:%M');
INSERT INTO `xlite_config` VALUES (256,'time_zone','General','select',680,'');
INSERT INTO `xlite_config` VALUES (258,'unit_presentation','General','separator',600,'');
INSERT INTO `xlite_config` VALUES (265,'users_department','Company','text',470,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (266,'users_per_page','General','text',420,'30');
INSERT INTO `xlite_config` VALUES (267,'user_layout','ImportExport',NULL,0,'login, password, billing_firstname, billing_lastname');
INSERT INTO `xlite_config` VALUES (268,'use_billing_info','Taxes','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (269,'use_smtp','Email','checkbox',110,'N');
INSERT INTO `xlite_config` VALUES (270,'use_smtp_auth','Email','checkbox',140,'N');
INSERT INTO `xlite_config` VALUES (271,'valid_email_domains','Email','text',30,'com;net;edu;mil;gov;org;biz');
INSERT INTO `xlite_config` VALUES (273,'version','Version','',0,'3.0.0-alpha2');
INSERT INTO `xlite_config` VALUES (275,'weight_symbol','General','text',620,'lbs');
INSERT INTO `xlite_config` VALUES (276,'weight_unit','General','select',610,'lbs');
INSERT INTO `xlite_config` VALUES (299,'you_save','General','select',296,'Y');
INSERT INTO `xlite_config` VALUES (300,'default_language','General','',330,'en');

INSERT INTO `xlite_config` VALUES (310,'anonymous','Shipping','separator',30,'');
INSERT INTO `xlite_config` VALUES (311,'anonymous_address','Shipping','text',40,'');
INSERT INTO `xlite_config` VALUES (312,'anonymous_city','Shipping','text',50,'');
INSERT INTO `xlite_config` VALUES (313,'anonymous_country','Shipping','country',90,'US');
INSERT INTO `xlite_config` VALUES (314,'anonymous_custom_state','Shipping','text',70,'');
INSERT INTO `xlite_config` VALUES (315,'anonymous_state','Shipping','state',60,'34');
INSERT INTO `xlite_config` VALUES (316,'anonymous_zipcode','Shipping','text',80,'10001');
INSERT INTO `xlite_config` VALUES (317,'shipping_enabled','Shipping','',10,'Y');
INSERT INTO `xlite_config` VALUES (77,'def_calc_shippings_taxes','Shipping','checkbox',20,'N');

INSERT INTO `xlite_config` VALUES (350,'check_templates_status','Performance','checkbox',10,'Y');

INSERT INTO `xlite_config` VALUES (351,'cli_key','Security','',110,'');

--  ********************************************************************************************************************



INSERT INTO xlite_countries VALUES ('Afghanistan','AF',1,'N');
INSERT INTO xlite_countries VALUES ('Albania','AL',1,'N');
INSERT INTO xlite_countries VALUES ('Algeria','DZ',1,'N');
INSERT INTO xlite_countries VALUES ('American Samoa','AS',1,'N');
INSERT INTO xlite_countries VALUES ('Andorra','AD',1,'N');
INSERT INTO xlite_countries VALUES ('Angola','AO',1,'N');
INSERT INTO xlite_countries VALUES ('Anguilla','AI',1,'N');
INSERT INTO xlite_countries VALUES ('Antarctica','AQ',1,'N');
INSERT INTO xlite_countries VALUES ('Antigua and Barbuda','AG',1,'N');
INSERT INTO xlite_countries VALUES ('Argentina','AR',1,'N');
INSERT INTO xlite_countries VALUES ('Armenia','AM',1,'N');
INSERT INTO xlite_countries VALUES ('Aruba','AW',1,'N');
INSERT INTO xlite_countries VALUES ('Australia','AU',1,'N');
INSERT INTO xlite_countries VALUES ('Austria','AT',1,'Y');
INSERT INTO xlite_countries VALUES ('Azerbaijan','AZ',1,'N');
INSERT INTO xlite_countries VALUES ('Bahamas','BS',1,'N');
INSERT INTO xlite_countries VALUES ('Bahrain','BH',1,'N');
INSERT INTO xlite_countries VALUES ('Bangladesh','BD',1,'N');
INSERT INTO xlite_countries VALUES ('Barbados','BB',1,'N');
INSERT INTO xlite_countries VALUES ('Belarus','BY',1,'N');
INSERT INTO xlite_countries VALUES ('Belgium','BE',1,'Y');
INSERT INTO xlite_countries VALUES ('Belize','BZ',1,'N');
INSERT INTO xlite_countries VALUES ('Benin','BJ',1,'N');
INSERT INTO xlite_countries VALUES ('Bermuda','BM',1,'N');
INSERT INTO xlite_countries VALUES ('Bhutan','BT',1,'N');
INSERT INTO xlite_countries VALUES ('Bolivia','BO',1,'N');
INSERT INTO xlite_countries VALUES ('Bosnia and Herzegowina','BA',1,'N');
INSERT INTO xlite_countries VALUES ('Botswana','BW',1,'N');
INSERT INTO xlite_countries VALUES ('Bouvet Island','BV',1,'N');
INSERT INTO xlite_countries VALUES ('Brazil','BR',1,'N');
INSERT INTO xlite_countries VALUES ('British Indian Ocean Territory','IO',1,'N');
INSERT INTO xlite_countries VALUES ('British Virgin Islands','VG',1,'N');
INSERT INTO xlite_countries VALUES ('Brunei Darussalam','BN',1,'N');
INSERT INTO xlite_countries VALUES ('Bulgaria','BG',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='BG';
INSERT INTO xlite_countries VALUES ('Burkina Faso','BF',1,'N');
INSERT INTO xlite_countries VALUES ('Burundi','BI',1,'N');
INSERT INTO xlite_countries VALUES ('Cambodia','KH',1,'N');
INSERT INTO xlite_countries VALUES ('Cameroon','CM',1,'N');
INSERT INTO xlite_countries VALUES ('Canada','CA',1,'N');
INSERT INTO xlite_countries VALUES ('Cape Verde','CV',1,'N');
INSERT INTO xlite_countries VALUES ('Cayman Islands','KY',1,'N');
INSERT INTO xlite_countries VALUES ('Central African Republic','CF',1,'N');
INSERT INTO xlite_countries VALUES ('Chad','TD',1,'N');
INSERT INTO xlite_countries VALUES ('Chile','CL',1,'N');
INSERT INTO xlite_countries VALUES ('China','CN',1,'N');
INSERT INTO xlite_countries VALUES ('Christmas Island','CX',1,'N');
INSERT INTO xlite_countries VALUES ('Cocos (Keeling) Islands','CC',1,'N');
INSERT INTO xlite_countries VALUES ('Colombia','CO',1,'N');
INSERT INTO xlite_countries VALUES ('Comoros','KM',1,'N');
INSERT INTO xlite_countries VALUES ('Congo, Democratic Republic of','CD',1,'N');
INSERT INTO xlite_countries VALUES ('Cook Islands','CK',1,'N');
INSERT INTO xlite_countries VALUES ('Costa Rica','CR',1,'N');
INSERT INTO xlite_countries VALUES ('Cote D\'ivoire','CI',1,'N');
INSERT INTO xlite_countries VALUES ('Croatia','HR',1,'N');
INSERT INTO xlite_countries VALUES ('Cuba','CU',1,'N');
INSERT INTO xlite_countries VALUES ('Cyprus','CY',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='CY';
INSERT INTO xlite_countries VALUES ('Czech Republic','CZ',1,'N');
INSERT INTO xlite_countries VALUES ('Czechoslovakia','CS',1,'N');
INSERT INTO xlite_countries VALUES ('Denmark','DK',1,'Y');
INSERT INTO xlite_countries VALUES ('Djibouti','DJ',1,'N');
INSERT INTO xlite_countries VALUES ('Dominica','DM',1,'N');
INSERT INTO xlite_countries VALUES ('Dominican Republic','DO',1,'N');
INSERT INTO xlite_countries VALUES ('East Timor','TP',1,'N');
INSERT INTO xlite_countries VALUES ('Ecuador','EC',1,'N');
INSERT INTO xlite_countries VALUES ('Egypt','EG',1,'N');
INSERT INTO xlite_countries VALUES ('El Salvador','SV',1,'N');
INSERT INTO xlite_countries VALUES ('Equatorial Guinea','GQ',1,'N');
INSERT INTO xlite_countries VALUES ('Eritrea','ER',1,'N');
INSERT INTO xlite_countries VALUES ('Estonia','EE',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='EE';
INSERT INTO xlite_countries VALUES ('Ethiopia','ET',1,'N');
INSERT INTO xlite_countries VALUES ('Falkland Islands (Malvinas)','FK',1,'N');
INSERT INTO xlite_countries VALUES ('Faroe Islands','FO',1,'N');
INSERT INTO xlite_countries VALUES ('Fiji','FJ',1,'N');
INSERT INTO xlite_countries VALUES ('Finland','FI',1,'Y');
INSERT INTO xlite_countries VALUES ('France','FR',1,'Y');
INSERT INTO xlite_countries VALUES ('France, Metropolitan','FX',1,'N');
INSERT INTO xlite_countries VALUES ('French Guiana','GF',1,'N');
INSERT INTO xlite_countries VALUES ('French Polynesia','PF',1,'N');
INSERT INTO xlite_countries VALUES ('French Southern Territories','TF',1,'N');
INSERT INTO xlite_countries VALUES ('Gabon','GA',1,'N');
INSERT INTO xlite_countries VALUES ('Gambia','GM',1,'N');
INSERT INTO xlite_countries VALUES ('Georgia','GE',1,'N');
INSERT INTO xlite_countries VALUES ('Germany','DE',1,'Y');
INSERT INTO xlite_countries VALUES ('Ghana','GH',1,'N');
INSERT INTO xlite_countries VALUES ('Gibraltar','GI',1,'N');
INSERT INTO xlite_countries VALUES ('Greece','GR',1,'Y');
INSERT INTO xlite_countries VALUES ('Greenland','GL',1,'N');
INSERT INTO xlite_countries VALUES ('Grenada','GD',1,'N');
INSERT INTO xlite_countries VALUES ('Guadeloupe','GP',1,'N');
INSERT INTO xlite_countries VALUES ('Guam','GU',1,'N');
INSERT INTO xlite_countries VALUES ('Guatemala','GT',1,'N');
INSERT INTO xlite_countries VALUES ('Guinea','GN',1,'N');
INSERT INTO xlite_countries VALUES ('Guinea-Bissau','GW',1,'N');
INSERT INTO xlite_countries VALUES ('Guyana','GY',1,'N');
INSERT INTO xlite_countries VALUES ('Haiti','HT',1,'N');
INSERT INTO xlite_countries VALUES ('Heard and McDonald Islands','HM',1,'N');
INSERT INTO xlite_countries VALUES ('Honduras','HN',1,'N');
INSERT INTO xlite_countries VALUES ('Hong Kong','HK',1,'N');
INSERT INTO xlite_countries VALUES ('Hungary','HU',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='HU';
INSERT INTO xlite_countries VALUES ('Iceland','IS',1,'N');
INSERT INTO xlite_countries VALUES ('India','IN',1,'N');
INSERT INTO xlite_countries VALUES ('Indonesia','ID',1,'N');
INSERT INTO xlite_countries VALUES ('Iraq','IQ',1,'N');
INSERT INTO xlite_countries VALUES ('Ireland','IE',1,'Y');
INSERT INTO xlite_countries VALUES ('Islamic Republic of Iran','IR',1,'N');
INSERT INTO xlite_countries VALUES ('Israel','IL',1,'N');
INSERT INTO xlite_countries VALUES ('Italy','IT',1,'Y');
INSERT INTO xlite_countries VALUES ('Jamaica','JM',1,'N');
INSERT INTO xlite_countries VALUES ('Japan','JP',1,'N');
INSERT INTO xlite_countries VALUES ('Jordan','JO',1,'N');
INSERT INTO xlite_countries VALUES ('Kazakhstan','KZ',1,'N');
INSERT INTO xlite_countries VALUES ('Kenya','KE',1,'N');
INSERT INTO xlite_countries VALUES ('Kiribati','KI',1,'N');
INSERT INTO xlite_countries VALUES ('Korea','KP',1,'N');
INSERT INTO xlite_countries VALUES ('Korea, Republic of','KR',1,'N');
INSERT INTO xlite_countries VALUES ('Kuwait','KW',1,'N');
INSERT INTO xlite_countries VALUES ('Kyrgyzstan','KG',1,'N');
INSERT INTO xlite_countries VALUES ('Laos','LA',1,'N');
INSERT INTO xlite_countries VALUES ('Latvia','LV',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='LV';
INSERT INTO xlite_countries VALUES ('Lebanon','LB',1,'N');
INSERT INTO xlite_countries VALUES ('Lesotho','LS',1,'N');
INSERT INTO xlite_countries VALUES ('Liberia','LR',1,'N');
INSERT INTO xlite_countries VALUES ('Libyan Arab Jamahiriya','LY',1,'N');
INSERT INTO xlite_countries VALUES ('Liechtenstein','LI',1,'N');
INSERT INTO xlite_countries VALUES ('Lithuania','LT',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='LT';
INSERT INTO xlite_countries VALUES ('Luxembourg','LU',1,'Y');
INSERT INTO xlite_countries VALUES ('Macau','MO',1,'N');
INSERT INTO xlite_countries VALUES ('Macedonia','MK',1,'N');
INSERT INTO xlite_countries VALUES ('Madagascar','MG',1,'N');
INSERT INTO xlite_countries VALUES ('Malawi','MW',1,'N');
INSERT INTO xlite_countries VALUES ('Malaysia','MY',1,'N');
INSERT INTO xlite_countries VALUES ('Maldives','MV',1,'N');
INSERT INTO xlite_countries VALUES ('Mali','ML',1,'N');
INSERT INTO xlite_countries VALUES ('Malta','MT',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='MT';
INSERT INTO xlite_countries VALUES ('Marshall Islands','MH',1,'N');
INSERT INTO xlite_countries VALUES ('Martinique','MQ',1,'N');
INSERT INTO xlite_countries VALUES ('Mauritania','MR',1,'N');
INSERT INTO xlite_countries VALUES ('Mauritius','MU',1,'N');
INSERT INTO xlite_countries VALUES ('Mayotte','YT',1,'N');
INSERT INTO xlite_countries VALUES ('Mexico','MX',1,'N');
INSERT INTO xlite_countries VALUES ('Micronesia','FM',1,'N');
INSERT INTO xlite_countries VALUES ('Moldova, Republic of','MD',1,'N');
INSERT INTO xlite_countries VALUES ('Monaco','MC',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='MC';
INSERT INTO xlite_countries VALUES ('Mongolia','MN',1,'N');
INSERT INTO xlite_countries VALUES ('Montserrat','MS',1,'N');
INSERT INTO xlite_countries VALUES ('Morocco','MA',1,'N');
INSERT INTO xlite_countries VALUES ('Mozambique','MZ',1,'N');
INSERT INTO xlite_countries VALUES ('Myanmar','MM',1,'N');
INSERT INTO xlite_countries VALUES ('Namibia','NA',1,'N');
INSERT INTO xlite_countries VALUES ('Nauru','NR',1,'N');
INSERT INTO xlite_countries VALUES ('Nepal','NP',1,'N');
INSERT INTO xlite_countries VALUES ('Netherlands','NL',1,'Y');
INSERT INTO xlite_countries VALUES ('Netherlands Antilles','AN',1,'N');
INSERT INTO xlite_countries VALUES ('New Caledonia','NC',1,'N');
INSERT INTO xlite_countries VALUES ('New Zealand','NZ',1,'N');
INSERT INTO xlite_countries VALUES ('Nicaragua','NI',1,'N');
INSERT INTO xlite_countries VALUES ('Niger','NE',1,'N');
INSERT INTO xlite_countries VALUES ('Nigeria','NG',1,'N');
INSERT INTO xlite_countries VALUES ('Niue','NU',1,'N');
INSERT INTO xlite_countries VALUES ('Norfolk Island','NF',1,'N');
INSERT INTO xlite_countries VALUES ('Northern Mariana Islands','MP',1,'N');
INSERT INTO xlite_countries VALUES ('Norway','NO',1,'N');
INSERT INTO xlite_countries VALUES ('Oman','OM',1,'N');
INSERT INTO xlite_countries VALUES ('Pakistan','PK',1,'N');
INSERT INTO xlite_countries VALUES ('Palau','PW',1,'N');
INSERT INTO xlite_countries VALUES ('Panama','PA',1,'N');
INSERT INTO xlite_countries VALUES ('Papua New Guinea','PG',1,'N');
INSERT INTO xlite_countries VALUES ('Paraguay','PY',1,'N');
INSERT INTO xlite_countries VALUES ('Peru','PE',1,'N');
INSERT INTO xlite_countries VALUES ('Philippines','PH',1,'N');
INSERT INTO xlite_countries VALUES ('Pitcairn','PN',1,'N');
INSERT INTO xlite_countries VALUES ('Poland','PL',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='PL';
INSERT INTO xlite_countries VALUES ('Portugal','PT',1,'Y');
INSERT INTO xlite_countries VALUES ('Puerto Rico','PR',1,'N');
INSERT INTO xlite_countries VALUES ('Qatar','QA',1,'N');
INSERT INTO xlite_countries VALUES ('Reunion','RE',1,'N');
INSERT INTO xlite_countries VALUES ('Romania','RO',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='RO';
INSERT INTO xlite_countries VALUES ('Russian Federation','RU',1,'N');
INSERT INTO xlite_countries VALUES ('Rwanda','RW',1,'N');
INSERT INTO xlite_countries VALUES ('Saint Lucia','LC',1,'N');
INSERT INTO xlite_countries VALUES ('Samoa','WS',1,'N');
INSERT INTO xlite_countries VALUES ('San Marino','SM',1,'N');
INSERT INTO xlite_countries VALUES ('Sao Tome and Principe','ST',1,'N');
INSERT INTO xlite_countries VALUES ('Saudi Arabia','SA',1,'N');
INSERT INTO xlite_countries VALUES ('Senegal','SN',1,'N');
INSERT INTO xlite_countries VALUES ('Seychelles','SC',1,'N');
INSERT INTO xlite_countries VALUES ('Sierra Leone','SL',1,'N');
INSERT INTO xlite_countries VALUES ('Singapore','SG',1,'N');
INSERT INTO xlite_countries VALUES ('Slovakia','SK',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='SK';
INSERT INTO xlite_countries VALUES ('Slovenia','SI',1,'Y');
--  UPDATE xlite_countries SET eu_member='Y' WHERE code='SI';
INSERT INTO xlite_countries VALUES ('Solomon Islands','SB',1,'N');
INSERT INTO xlite_countries VALUES ('Somalia','SO',1,'N');
INSERT INTO xlite_countries VALUES ('South Africa','ZA',1,'N');
INSERT INTO xlite_countries VALUES ('Spain','ES',1,'Y');
INSERT INTO xlite_countries VALUES ('Sri Lanka','LK',1,'N');
INSERT INTO xlite_countries VALUES ('St. Helena','SH',1,'N');
INSERT INTO xlite_countries VALUES ('St. Kitts And Nevis','KN',1,'N');
INSERT INTO xlite_countries VALUES ('St. Pierre and Miquelon','PM',1,'N');
INSERT INTO xlite_countries VALUES ('St. Vincent And The Greadines','VC',1,'N');
INSERT INTO xlite_countries VALUES ('Sudan','SD',1,'N');
INSERT INTO xlite_countries VALUES ('Suriname','SR',1,'N');
INSERT INTO xlite_countries VALUES ('Svalbard and Jan Mayen Islands','SJ',1,'N');
INSERT INTO xlite_countries VALUES ('Swaziland','SZ',1,'N');
INSERT INTO xlite_countries VALUES ('Sweden','SE',1,'Y');
INSERT INTO xlite_countries VALUES ('Switzerland','CH',1,'N');
INSERT INTO xlite_countries VALUES ('Syrian Arab Republic','SY',1,'N');
INSERT INTO xlite_countries VALUES ('Taiwan','TW',1,'N');
INSERT INTO xlite_countries VALUES ('Tajikistan','TJ',1,'N');
INSERT INTO xlite_countries VALUES ('Tanzania, United Republic of','TZ',1,'N');
INSERT INTO xlite_countries VALUES ('Thailand','TH',1,'N');
INSERT INTO xlite_countries VALUES ('Togo','TG',1,'N');
INSERT INTO xlite_countries VALUES ('Tokelau','TK',1,'N');
INSERT INTO xlite_countries VALUES ('Tonga','TO',1,'N');
INSERT INTO xlite_countries VALUES ('Trinidad and Tobago','TT',1,'N');
INSERT INTO xlite_countries VALUES ('Tunisia','TN',1,'N');
INSERT INTO xlite_countries VALUES ('Turkey','TR',1,'N');
INSERT INTO xlite_countries VALUES ('Turkmenistan','TM',1,'N');
INSERT INTO xlite_countries VALUES ('Turks and Caicos Islands','TC',1,'N');
INSERT INTO xlite_countries VALUES ('Tuvalu','TV',1,'N');
INSERT INTO xlite_countries VALUES ('Uganda','UG',1,'N');
INSERT INTO xlite_countries VALUES ('Ukraine','UA',1,'N');
INSERT INTO xlite_countries VALUES ('United Arab Emirates','AE',1,'N');
INSERT INTO xlite_countries VALUES ('United Kingdom (Great Britain)','GB',1,'Y');
INSERT INTO xlite_countries VALUES ('United States','US',1,'N');
INSERT INTO xlite_countries VALUES ('United States Virgin Islands','VI',1,'N');
INSERT INTO xlite_countries VALUES ('Uruguay','UY',1,'N');
INSERT INTO xlite_countries VALUES ('Uzbekistan','UZ',1,'N');
INSERT INTO xlite_countries VALUES ('Vanuatu','VU',1,'N');
INSERT INTO xlite_countries VALUES ('Vatican City State','VA',1,'N');
INSERT INTO xlite_countries VALUES ('Venezuela','VE',1,'N');
INSERT INTO xlite_countries VALUES ('Viet Nam','VN',1,'N');
INSERT INTO xlite_countries VALUES ('Wallis And Futuna Islands','WF',1,'N');
INSERT INTO xlite_countries VALUES ('Western Sahara','EH',1,'N');
INSERT INTO xlite_countries VALUES ('Yemen','YE',1,'N');
INSERT INTO xlite_countries VALUES ('Serbia and Montenegro','YU',1,'N');
INSERT INTO xlite_countries VALUES ('Zambia','ZM',1,'N');
INSERT INTO xlite_countries VALUES ('Zimbabwe','ZW',1,'N');

--  Payment methods
INSERT INTO xlite_payment_methods VALUES (1,'CreditCard','Model\\Payment\\Processor\\CreditCard',10,1);
INSERT INTO xlite_payment_methods VALUES (2,'PurchaseOrder','Model\\Payment\\Processor\\PurchaseOrder',20,1);
INSERT INTO xlite_payment_methods VALUES (3,'PhoneOrdering','Model\\Payment\\Processor\\Offline',30,1);
INSERT INTO xlite_payment_methods VALUES (4,'FaxOrdering','Model\\Payment\\Processor\\Offline',40,1);
INSERT INTO xlite_payment_methods VALUES (5,'MoneyOrdering','Model\\Payment\\Processor\\Offline',50,1);
INSERT INTO xlite_payment_methods VALUES (6,'Echeck','Model\\Payment\\Processor\\Check',60,1);
INSERT INTO xlite_payment_methods VALUES (7,'COD','Model\\Payment\\Processor\\Offline',70,1);


--  Languages
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (1,'aa','aar');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (2,'ab','abk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (3,'af','afr');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (4,'ak','aka');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (5,'sq','alb');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (6,'am','amh');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (7,'ar','ara');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (8,'an','arg');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (9,'hy','arm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (10,'as','asm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (11,'av','ava');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (12,'ae','ave');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (13,'ay','aym');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (14,'az','aze');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (15,'ba','bak');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (16,'bm','bam');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (17,'eu','baq');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (18,'be','bel');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (19,'bn','ben');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (20,'bh','bih');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (21,'bi','bis');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (22,'bs','bos');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (23,'br','bre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (24,'bg','bul');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (25,'my','bur');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (26,'ca','cat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (27,'ch','cha');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (28,'ce','che');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (29,'zh','chi');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (30,'cu','chu');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (31,'cv','chv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (32,'kw','cor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (33,'co','cos');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (34,'cr','cre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (35,'cs','cze');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (36,'da','dan');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (37,'dv','div');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (38,'nl','dut');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (39,'dz','dzo');
INSERT INTO xlite_languages (lng_id, code, code3, status) VALUES (40,'en','eng',2);
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (41,'eo','epo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (42,'et','est');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (43,'ee','ewe');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (44,'fo','fao');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (45,'fj','fij');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (46,'fi','fin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (47,'fr','fre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (48,'fy','fry');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (49,'ff','ful');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (50,'ka','geo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (51,'de','ger');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (52,'gd','gla');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (53,'ga','gle');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (54,'gl','glg');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (55,'gv','glv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (56,'el','gre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (57,'gn','grn');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (58,'gu','guj');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (59,'ht','hat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (60,'ha','hau');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (61,'he','heb');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (62,'hz','her');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (63,'hi','hin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (64,'ho','hmo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (65,'hr','hrv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (66,'hu','hun');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (67,'ig','ibo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (68,'is','ice');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (69,'io','ido');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (70,'ii','iii');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (71,'iu','iku');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (72,'ie','ile');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (73,'ia','ina');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (74,'id','ind');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (75,'ik','ipk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (76,'it','ita');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (77,'jv','jav');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (78,'ja','jpn');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (79,'kl','kal');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (80,'kn','kan');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (81,'ks','kas');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (82,'kr','kau');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (83,'kk','kaz');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (84,'km','khm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (85,'ki','kik');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (86,'rw','kin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (87,'ky','kir');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (88,'kv','kom');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (89,'kg','kon');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (90,'ko','kor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (91,'kj','kua');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (92,'ku','kur');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (93,'lo','lao');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (94,'la','lat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (95,'lv','lav');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (96,'li','lim');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (97,'ln','lin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (98,'lt','lit');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (99,'lb','ltz');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (100,'lu','lub');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (101,'lg','lug');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (102,'mk','mac');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (103,'mh','mah');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (104,'ml','mal');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (105,'mi','mao');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (106,'mr','mar');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (107,'ms','may');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (108,'mg','mlg');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (109,'mt','mlt');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (110,'mn','mon');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (111,'na','nau');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (112,'nv','nav');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (113,'nr','nbl');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (114,'nd','nde');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (115,'ng','ndo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (116,'ne','nep');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (117,'no','nor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (118,'ny','nya');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (119,'oc','oci');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (120,'oj','oji');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (121,'or','ori');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (122,'om','orm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (123,'os','oss');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (124,'pa','pan');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (125,'fa','per');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (126,'pi','pli');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (127,'pl','pol');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (128,'pt','por');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (129,'ps','pus');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (130,'qu','que');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (131,'rm','roh');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (132,'ro','rum');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (133,'rn','run');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (134,'ru','rus');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (135,'sg','sag');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (136,'sa','san');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (137,'si','sin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (138,'sk','slo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (139,'sl','slv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (140,'se','sme');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (141,'sm','smo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (142,'sn','sna');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (143,'sd','snd');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (144,'so','som');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (145,'st','sot');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (146,'es','spa');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (147,'sc','srd');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (148,'sr','srp');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (149,'ss','ssw');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (150,'su','sun');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (151,'sw','swa');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (152,'sv','swe');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (153,'ty','tah');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (154,'ta','tam');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (155,'tt','tat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (156,'te','tel');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (157,'tg','tgk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (158,'tl','tgl');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (159,'th','tha');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (160,'bo','tib');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (161,'ti','tir');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (162,'to','ton');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (163,'tn','tsn');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (164,'ts','tso');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (165,'tk','tuk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (166,'tr','tur');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (167,'tw','twi');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (168,'ug','uig');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (169,'uk','ukr');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (170,'ur','urd');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (171,'uz','uzb');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (172,'ve','ven');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (173,'vi','vie');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (174,'vo','vol');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (175,'cy','wel');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (176,'wa','wln');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (177,'wo','wol');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (178,'xh','xho');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (179,'yi','yid');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (180,'yo','yor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (181,'za','zha');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (182,'zu','zul');

--  Memberships
INSERT INTO xlite_memberships VALUES (1, 10, 1);
INSERT INTO xlite_memberships VALUES (2, 20, 1);
INSERT INTO xlite_memberships VALUES (3, 30, 1);

--  Language labels
INSERT INTO xlite_language_labels (label_id, name) VALUES (1, 'Weight');
INSERT INTO xlite_language_labels (label_id, name) VALUES (2, 'Add to cart');
INSERT INTO xlite_language_labels (label_id, name) VALUES (3, 'Description');
INSERT INTO xlite_language_labels (label_id, name) VALUES (4, 'SKU');
INSERT INTO xlite_language_labels (label_id, name) VALUES (5, 'Previous product');
INSERT INTO xlite_language_labels (label_id, name) VALUES (6, 'Next product');
INSERT INTO xlite_language_labels (label_id, name) VALUES (7, 'Clear cart');
INSERT INTO xlite_language_labels (label_id, name) VALUES (8, 'Continue shopping');
INSERT INTO xlite_language_labels (label_id, name) VALUES (9, 'Submit');
INSERT INTO xlite_language_labels (label_id, name) VALUES (10, 'Delivery');
INSERT INTO xlite_language_labels (label_id, name) VALUES (11, 'This product is out of stock or it has been disabled for sale');
INSERT INTO xlite_language_labels (label_id, name) VALUES (12, 'Update');
INSERT INTO xlite_language_labels (label_id, name) VALUES (13, 'Grand total');
INSERT INTO xlite_language_labels (label_id, name) VALUES (14, 'Shipping cost');
INSERT INTO xlite_language_labels (label_id, name) VALUES (15, 'Free');
INSERT INTO xlite_language_labels (label_id, name) VALUES (16, 'Subtotal');
INSERT INTO xlite_language_labels (label_id, name) VALUES (17, 'Tax');
INSERT INTO xlite_language_labels (label_id, name) VALUES (18, 'n/a');
INSERT INTO xlite_language_labels (label_id, name) VALUES (19, 'Your shopping cart is empty');
INSERT INTO xlite_language_labels (label_id, name) VALUES (20, 'Delete item');
INSERT INTO xlite_language_labels (label_id, name) VALUES (21, 'Continue...');
INSERT INTO xlite_language_labels (label_id, name) VALUES (22, 'The language you want to add has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (23, 'The language you want to add has already been added');
INSERT INTO xlite_language_labels (label_id, name) VALUES (24, 'The X language has been added successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (25, 'The language you want to delete has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (26, 'The language you want to delete is the default application language and cannot be deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (27, 'The language you want to delete is the default interface language and cannot be deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (28, 'The X language has been deleted successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (29, 'The language has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (30, 'The default interface language cannot be disabled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (31, 'The X language has been disabled successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (32, 'The X language has been enabled successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (33, 'Text labels have been updated successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (34, 'Text labels have not been updated successfully: the translation language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (35, 'Text labels have not been updated successfully: the default application language has been set as the translation language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (36, 'Text labels have not been updated successfully: the translation language has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (37, 'Text labels have been deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (38, 'Text labels have not been deleted: no text labels have been found or specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (39, 'The text label has been deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (40, 'The text label has not been deleted: it has been either not found or not specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (41, 'The text label has not been added, because its name has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (42, 'The text label has not been added, because such a text label already exists');
INSERT INTO xlite_language_labels (label_id, name) VALUES (43, 'The text label has not been added, because its translation for the default application language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (44, 'The text label has not been added, because its translation for the default interface language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (45, 'The text label has been added successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (46, 'The text label has not been modified, because its translation for the default application language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (47, 'The text label has not been modified, because its translation for the default interface language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (48, 'The text label has been modified successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (49, 'The edited language has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (50, 'The name of the edited language in the default application language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (51, 'The language data has been saved');
INSERT INTO xlite_language_labels (label_id, name) VALUES (52, 'Search');
INSERT INTO xlite_language_labels (label_id, name) VALUES (53, 'Show all labels');
INSERT INTO xlite_language_labels (label_id, name) VALUES (54, 'N items found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (55, 'Language options');
INSERT INTO xlite_language_labels (label_id, name) VALUES (56, 'X labels');
INSERT INTO xlite_language_labels (label_id, name) VALUES (57, 'translate to');
INSERT INTO xlite_language_labels (label_id, name) VALUES (58, 'Select language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (59, 'No other languages defined');
INSERT INTO xlite_language_labels (label_id, name) VALUES (60, 'Add new label');
INSERT INTO xlite_language_labels (label_id, name) VALUES (61, 'Add language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (62, 'N items');
INSERT INTO xlite_language_labels (label_id, name) VALUES (63, 'Select language to edit');
INSERT INTO xlite_language_labels (label_id, name) VALUES (64, 'Add new language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (65, 'Save');
INSERT INTO xlite_language_labels (label_id, name) VALUES (66, 'Please specify text labels for each language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (67, 'Label name');
INSERT INTO xlite_language_labels (label_id, name) VALUES (68, 'required');
INSERT INTO xlite_language_labels (label_id, name) VALUES (69, 'Confirm deletion');
INSERT INTO xlite_language_labels (label_id, name) VALUES (70, 'You are going to delete X language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (71, 'Delete');
INSERT INTO xlite_language_labels (label_id, name) VALUES (72, 'Cancel');
INSERT INTO xlite_language_labels (label_id, name) VALUES (73, 'X Language (Code: Y)');
INSERT INTO xlite_language_labels (label_id, name) VALUES (74, 'Language name in X');
INSERT INTO xlite_language_labels (label_id, name) VALUES (75, 'Native language name');
INSERT INTO xlite_language_labels (label_id, name) VALUES (76, 'Disable');
INSERT INTO xlite_language_labels (label_id, name) VALUES (77, 'Enable');
INSERT INTO xlite_language_labels (label_id, name) VALUES (78, 'Default for customer zone and can not disabled or deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (79, 'Set this language as default for customer zone');
INSERT INTO xlite_language_labels (label_id, name) VALUES (80, 'Disabled language can not be set as default for customer zone');
INSERT INTO xlite_language_labels (label_id, name) VALUES (81, 'Delete Language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (82, 'Edit label');
INSERT INTO xlite_language_labels (label_id, name) VALUES (83, 'Please specify a pattern to find the required labels');
INSERT INTO xlite_language_labels (label_id, name) VALUES (84, 'The language is enabled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (85, 'The language is disabled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (86, 'The module to uninstall has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (87, 'The module has been uninstalled successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (88, 'The module has been partially uninstalled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (89, 'The X module has been installed successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (90, 'The X module has been installed with errors: the DB has not been modified correctly');
INSERT INTO xlite_language_labels (label_id, name) VALUES (91, 'The X module has been installed incorrectly. Please see the logs for more information');
INSERT INTO xlite_language_labels (label_id, name) VALUES (92, 'The X module has been installed, but the module has a wrong module control class');
INSERT INTO xlite_language_labels (label_id, name) VALUES (93, 'The X module has been uninstalled in an abnormal way');
INSERT INTO xlite_language_labels (label_id, name) VALUES (94, 'The modules have been updated');
INSERT INTO xlite_language_labels (label_id, name) VALUES (95, 'The X module has been disabled in an abnormal way');
INSERT INTO xlite_language_labels (label_id, name) VALUES (96, 'Congratulations! Your order has been successfully placed');
INSERT INTO xlite_language_labels (label_id, name) VALUES (97, 'X items in bag');
INSERT INTO xlite_language_labels (label_id, name) VALUES (98, 'Other items');
INSERT INTO xlite_language_labels (label_id, name) VALUES (99, 'The selected shipping method has been deleted successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (100, 'Shipping methods have been updated');
INSERT INTO xlite_language_labels (label_id, name) VALUES (101, 'Shipping method has been added');
INSERT INTO xlite_language_labels (label_id, name) VALUES (102, 'The selected zones have been deleted successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (103, 'Zone details have been updated successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (104, 'New zone has been created successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (105, 'This product has been added to your bag');
INSERT INTO xlite_language_labels (label_id, name) VALUES (106, 'Your shopping bag - X items');
INSERT INTO xlite_language_labels (label_id, name) VALUES (107, 'Greetings, X');
INSERT INTO xlite_language_labels (label_id, name) VALUES (108, 'X items');
INSERT INTO xlite_language_labels (label_id, name) VALUES (109, 'This email address is used for an existing account. Enter another email address or sign in');
INSERT INTO xlite_language_labels (label_id, name) VALUES (110, 'This user name is used for an existing account. Enter another user name or sign in');
INSERT INTO xlite_language_labels (label_id, name) VALUES (111, 'I accept Terms and Conditions');
INSERT INTO xlite_language_labels (label_id, name) VALUES (112, 'Place order X');
INSERT INTO xlite_language_labels (label_id, name) VALUES (113, 'Enter a correct email');
INSERT INTO xlite_language_labels (label_id, name) VALUES (114, 'Enter an integer');
INSERT INTO xlite_language_labels (label_id, name) VALUES (115, 'Enter a number');
INSERT INTO xlite_language_labels (label_id, name) VALUES (116, 'Zero cannot be used');
INSERT INTO xlite_language_labels (label_id, name) VALUES (117, 'Enter a positive number');
INSERT INTO xlite_language_labels (label_id, name) VALUES (118, 'Enter a negative number');
INSERT INTO xlite_language_labels (label_id, name) VALUES (119, 'This field is required');

INSERT INTO xlite_zones VALUES (1,'Default zone (all addresses)',1);

--  Currencies
INSERT INTO xlite_currencies VALUES ('ADP',20,'',2);
INSERT INTO xlite_currencies VALUES ('AED',784,'',2);
INSERT INTO xlite_currencies VALUES ('AFA',4,'',2);
INSERT INTO xlite_currencies VALUES ('ALL',8,'',2);
INSERT INTO xlite_currencies VALUES ('AMD',51,'',0);
INSERT INTO xlite_currencies VALUES ('ANG',532,'',2);
INSERT INTO xlite_currencies VALUES ('AON',24,'',2);
INSERT INTO xlite_currencies VALUES ('ARS',32,'',2);
INSERT INTO xlite_currencies VALUES ('ATS',40,'',2);
INSERT INTO xlite_currencies VALUES ('AUD',36,'',2);
INSERT INTO xlite_currencies VALUES ('AWG',533,'',2);
INSERT INTO xlite_currencies VALUES ('AZM',31,'',2);
INSERT INTO xlite_currencies VALUES ('BAM',977,'',2);
INSERT INTO xlite_currencies VALUES ('BBD',52,'',2);
INSERT INTO xlite_currencies VALUES ('BDT',50,'',2);
INSERT INTO xlite_currencies VALUES ('BEF',56,'',2);
INSERT INTO xlite_currencies VALUES ('BGL',100,'',2);
INSERT INTO xlite_currencies VALUES ('BHD',48,'',3);
INSERT INTO xlite_currencies VALUES ('BIF',108,'',0);
INSERT INTO xlite_currencies VALUES ('BMD',60,'',2);
INSERT INTO xlite_currencies VALUES ('BND',96,'',2);
INSERT INTO xlite_currencies VALUES ('BOB',68,'',2);
INSERT INTO xlite_currencies VALUES ('BRL',986,'',2);
INSERT INTO xlite_currencies VALUES ('BTN',64,'',2);
INSERT INTO xlite_currencies VALUES ('BWP',72,'',2);
INSERT INTO xlite_currencies VALUES ('BYR',974,'',0);
INSERT INTO xlite_currencies VALUES ('BZD',84,'',2);
INSERT INTO xlite_currencies VALUES ('CAD',124,'',2);
INSERT INTO xlite_currencies VALUES ('CDF',976,'',2);
INSERT INTO xlite_currencies VALUES ('CHF',756,'',2);
INSERT INTO xlite_currencies VALUES ('CLP',152,'',0);
INSERT INTO xlite_currencies VALUES ('CNY',156,'',1);
INSERT INTO xlite_currencies VALUES ('COP',170,'',0);
INSERT INTO xlite_currencies VALUES ('CRC',188,'',2);
INSERT INTO xlite_currencies VALUES ('CUP',192,'',2);
INSERT INTO xlite_currencies VALUES ('CVE',132,'',2);
INSERT INTO xlite_currencies VALUES ('CYP',196,'',2);
INSERT INTO xlite_currencies VALUES ('CZK',203,'',2);
INSERT INTO xlite_currencies VALUES ('DEM',276,'',2);
INSERT INTO xlite_currencies VALUES ('DJF',262,'',0);
INSERT INTO xlite_currencies VALUES ('DKK',208,'',2);
INSERT INTO xlite_currencies VALUES ('DOP',214,'',2);
INSERT INTO xlite_currencies VALUES ('DZD',12,'',2);
INSERT INTO xlite_currencies VALUES ('EEK',233,'',2);
INSERT INTO xlite_currencies VALUES ('EGP',818,'',2);
INSERT INTO xlite_currencies VALUES ('ERN',232,'',2);
INSERT INTO xlite_currencies VALUES ('ETB',230,'',2);
INSERT INTO xlite_currencies VALUES ('EUR',978,'',2);
INSERT INTO xlite_currencies VALUES ('FIM',246,'',2);
INSERT INTO xlite_currencies VALUES ('FJD',242,'',2);
INSERT INTO xlite_currencies VALUES ('FKP',238,'',2);
INSERT INTO xlite_currencies VALUES ('FRF',250,'',2);
INSERT INTO xlite_currencies VALUES ('GBP',826,'£',2);
INSERT INTO xlite_currencies VALUES ('GEL',981,'',2);
INSERT INTO xlite_currencies VALUES ('GHC',288,'',2);
INSERT INTO xlite_currencies VALUES ('GIP',292,'',2);
INSERT INTO xlite_currencies VALUES ('GMD',270,'',2);
INSERT INTO xlite_currencies VALUES ('GNF',324,'',0);
INSERT INTO xlite_currencies VALUES ('GTQ',320,'',2);
INSERT INTO xlite_currencies VALUES ('GWP',624,'',2);
INSERT INTO xlite_currencies VALUES ('GYD',328,'',2);
INSERT INTO xlite_currencies VALUES ('HKD',344,'',2);
INSERT INTO xlite_currencies VALUES ('HNL',340,'',2);
INSERT INTO xlite_currencies VALUES ('HRK',191,'',2);
INSERT INTO xlite_currencies VALUES ('HTG',332,'',2);
INSERT INTO xlite_currencies VALUES ('HUF',348,'',2);
INSERT INTO xlite_currencies VALUES ('IDR',360,'',0);
INSERT INTO xlite_currencies VALUES ('IEP',372,'',2);
INSERT INTO xlite_currencies VALUES ('ILS',376,'',2);
INSERT INTO xlite_currencies VALUES ('INR',356,'',2);
INSERT INTO xlite_currencies VALUES ('IQD',368,'',0);
INSERT INTO xlite_currencies VALUES ('IRR',364,'',0);
INSERT INTO xlite_currencies VALUES ('ISK',352,'',0);
INSERT INTO xlite_currencies VALUES ('ITL',380,'',2);
INSERT INTO xlite_currencies VALUES ('JMD',388,'',2);
INSERT INTO xlite_currencies VALUES ('JOD',400,'',3);
INSERT INTO xlite_currencies VALUES ('JPY',392,'',0);
INSERT INTO xlite_currencies VALUES ('KES',404,'',2);
INSERT INTO xlite_currencies VALUES ('KGS',417,'',2);
INSERT INTO xlite_currencies VALUES ('KMF',174,'',0);
INSERT INTO xlite_currencies VALUES ('KPW',408,'',0);
INSERT INTO xlite_currencies VALUES ('KRW',410,'',0);
INSERT INTO xlite_currencies VALUES ('KWD',414,'',3);
INSERT INTO xlite_currencies VALUES ('KYD',136,'',2);
INSERT INTO xlite_currencies VALUES ('KZT',398,'',2);
INSERT INTO xlite_currencies VALUES ('LAK',418,'',0);
INSERT INTO xlite_currencies VALUES ('LBP',422,'',0);
INSERT INTO xlite_currencies VALUES ('LKR',144,'',2);
INSERT INTO xlite_currencies VALUES ('LRD',430,'',2);
INSERT INTO xlite_currencies VALUES ('LSL',426,'',2);
INSERT INTO xlite_currencies VALUES ('LTL',440,'',2);
INSERT INTO xlite_currencies VALUES ('LUF',442,'',2);
INSERT INTO xlite_currencies VALUES ('LVL',428,'',2);
INSERT INTO xlite_currencies VALUES ('LYD',434,'',3);
INSERT INTO xlite_currencies VALUES ('MAD',504,'',2);
INSERT INTO xlite_currencies VALUES ('MDL',498,'',2);
INSERT INTO xlite_currencies VALUES ('MGF',450,'',2);
INSERT INTO xlite_currencies VALUES ('MKD',807,'',2);
INSERT INTO xlite_currencies VALUES ('MMK',104,'',0);
INSERT INTO xlite_currencies VALUES ('MNT',496,'',2);
INSERT INTO xlite_currencies VALUES ('MOP',446,'',1);
INSERT INTO xlite_currencies VALUES ('MRO',478,'',0);
INSERT INTO xlite_currencies VALUES ('MTL',470,'',2);
INSERT INTO xlite_currencies VALUES ('MUR',480,'',2);
INSERT INTO xlite_currencies VALUES ('MVR',462,'',2);
INSERT INTO xlite_currencies VALUES ('MWK',454,'',2);
INSERT INTO xlite_currencies VALUES ('MXN',484,'',2);
INSERT INTO xlite_currencies VALUES ('MYR',458,'',2);
INSERT INTO xlite_currencies VALUES ('MZM',508,'',2);
INSERT INTO xlite_currencies VALUES ('NAD',516,'',2);
INSERT INTO xlite_currencies VALUES ('NGN',566,'',2);
INSERT INTO xlite_currencies VALUES ('NIO',558,'',2);
INSERT INTO xlite_currencies VALUES ('NLG',528,'',2);
INSERT INTO xlite_currencies VALUES ('NOK',578,'',2);
INSERT INTO xlite_currencies VALUES ('NPR',524,'',2);
INSERT INTO xlite_currencies VALUES ('NZD',554,'',2);
INSERT INTO xlite_currencies VALUES ('OMR',512,'',3);
INSERT INTO xlite_currencies VALUES ('PAB',590,'',2);
INSERT INTO xlite_currencies VALUES ('PEN',604,'',2);
INSERT INTO xlite_currencies VALUES ('PGK',598,'',2);
INSERT INTO xlite_currencies VALUES ('PHP',608,'',2);
INSERT INTO xlite_currencies VALUES ('PKR',586,'',2);
INSERT INTO xlite_currencies VALUES ('PLN',985,'',2);
INSERT INTO xlite_currencies VALUES ('PTE',620,'',2);
INSERT INTO xlite_currencies VALUES ('PYG',600,'',0);
INSERT INTO xlite_currencies VALUES ('QAR',634,'',2);
INSERT INTO xlite_currencies VALUES ('ROL',642,'',2);
INSERT INTO xlite_currencies VALUES ('RSD',941,'',2);
INSERT INTO xlite_currencies VALUES ('RUR',810,'',2);
INSERT INTO xlite_currencies VALUES ('RWF',646,'',0);
INSERT INTO xlite_currencies VALUES ('SAR',682,'',2);
INSERT INTO xlite_currencies VALUES ('SBD',90,'',2);
INSERT INTO xlite_currencies VALUES ('SCR',690,'',2);
INSERT INTO xlite_currencies VALUES ('SDD',736,'',2);
INSERT INTO xlite_currencies VALUES ('SEK',752,'',2);
INSERT INTO xlite_currencies VALUES ('SGD',702,'',2);
INSERT INTO xlite_currencies VALUES ('SHP',654,'',2);
INSERT INTO xlite_currencies VALUES ('SHR',116,'',2);
INSERT INTO xlite_currencies VALUES ('SIT',705,'',2);
INSERT INTO xlite_currencies VALUES ('SKK',703,'',2);
INSERT INTO xlite_currencies VALUES ('SLL',694,'',0);
INSERT INTO xlite_currencies VALUES ('SOS',706,'',2);
INSERT INTO xlite_currencies VALUES ('SRG',740,'',2);
INSERT INTO xlite_currencies VALUES ('STD',678,'',0);
INSERT INTO xlite_currencies VALUES ('SVC',222,'',2);
INSERT INTO xlite_currencies VALUES ('SYP',760,'',2);
INSERT INTO xlite_currencies VALUES ('SZL',748,'',2);
INSERT INTO xlite_currencies VALUES ('THB',764,'',2);
INSERT INTO xlite_currencies VALUES ('TJS',972,'',2);
INSERT INTO xlite_currencies VALUES ('TMM',795,'',2);
INSERT INTO xlite_currencies VALUES ('TND',788,'',3);
INSERT INTO xlite_currencies VALUES ('TOP',776,'',2);
INSERT INTO xlite_currencies VALUES ('TPE',626,'',2);
INSERT INTO xlite_currencies VALUES ('TRL',792,'',2);
INSERT INTO xlite_currencies VALUES ('TTD',780,'',2);
INSERT INTO xlite_currencies VALUES ('TWD',901,'',1);
INSERT INTO xlite_currencies VALUES ('TZS',834,'',2);
INSERT INTO xlite_currencies VALUES ('UAH',980,'',2);
INSERT INTO xlite_currencies VALUES ('UGX',800,'',0);
INSERT INTO xlite_currencies VALUES ('USD',840,'$',2);
INSERT INTO xlite_currencies VALUES ('UYU',858,'',2);
INSERT INTO xlite_currencies VALUES ('UZS',860,'',2);
INSERT INTO xlite_currencies VALUES ('VEB',862,'',2);
INSERT INTO xlite_currencies VALUES ('VND',704,'',0);
INSERT INTO xlite_currencies VALUES ('VUV',548,'',0);
INSERT INTO xlite_currencies VALUES ('WST',882,'',2);
INSERT INTO xlite_currencies VALUES ('XAF',950,'',0);
INSERT INTO xlite_currencies VALUES ('XCD',951,'',2);
INSERT INTO xlite_currencies VALUES ('XOF',952,'',0);
INSERT INTO xlite_currencies VALUES ('XPF',953,'',0);
INSERT INTO xlite_currencies VALUES ('YER',886,'',0);
INSERT INTO xlite_currencies VALUES ('YUM',891,'',2);
INSERT INTO xlite_currencies VALUES ('ZAR',710,'',2);
INSERT INTO xlite_currencies VALUES ('ZMK',894,'',0);
INSERT INTO xlite_currencies VALUES ('ZWD',716,'',2);

--  Insert root category

INSERT INTO xlite_categories VALUES (1,0,1,2,0,1,'',1);

