-- Language labels
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (1, 'en', 'Weight');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (2, 'en', 'Add to Cart');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (3, 'en', 'Description');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (4, 'en', 'SKU');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (5, 'en', 'Previous product');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (6, 'en', 'Next product');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (7, 'en', 'Clear cart');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (8, 'en', 'Continue shopping');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (9, 'en', 'Submit');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (10, 'en', 'Delivery');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (11, 'en', '(!) This product is out of stock or it has been disabled for sale.');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (12, 'en', 'Update');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (13, 'en', 'Grand total');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (14, 'en', 'Shipping cost');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (15, 'en', 'Free');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (16, 'en', 'Subtotal');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (17, 'en', 'Tax');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (18, 'en', 'n/a');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (19, 'en', 'Your shopping cart is empty');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (20, 'en', 'Delete item');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (21, 'en', 'Continue...');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (22, 'en', 'The language you want to add has not been found');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (23, 'en', 'The language you want to add has already been added');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (24, 'en', 'The {{language}} language has been added successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (25, 'en', 'The language you want to delete has not been found');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (26, 'en', 'The language you want to delete is the default application language and cannot be deleted');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (27, 'en', 'The language you want to delete is the default interface language and cannot be deleted');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (28, 'en', 'The {{language}} language has been deleted successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (29, 'en', 'The language has not been found');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (30, 'en', 'The default interface language cannot be disabled');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (31, 'en', 'The {{language}} language has been disabled successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (32, 'en', 'The {{language}} language has been enabled successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (33, 'en', 'Text labels have been updated successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (34, 'en', 'Text labels have not been updated successfully: the translation language has not been specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (35, 'en', 'Text labels have not been updated successfully: the default application language has been set as the translation language');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (36, 'en', 'Text labels have not been updated successfully: the translation language has not been found');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (37, 'en', 'Text labels have been deleted');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (38, 'en', 'Text labels have not been deleted: no text labels have been found or specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (39, 'en', 'The text label has been deleted');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (40, 'en', 'The text label has not been deleted: it has been either not found or not specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (41, 'en', 'The text label has not been added, because its name has not been specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (42, 'en', 'The text label has not been added, because such a text label already exists');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (43, 'en', 'The text label has not been added, because its translation for the default application language has not been specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (44, 'en', 'The text label has not been added, because its translation for the default interface language has not been specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (45, 'en', 'The text label has been added successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (46, 'en', 'The text label has not been modified, because its translation for the default application language has not been specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (47, 'en', 'The text label has not been modified, because its translation for the default interface language has not been specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (48, 'en', 'The text label has been modified successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (49, 'en', 'The edited language has not been found');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (50, 'en', 'The name of the edited language in the default application language has not been specified');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (51, 'en', 'The language data has been saved');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (52, 'en', 'Search');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (53, 'en', 'Show all labels');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (54, 'en', '{{n}} items found');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (55, 'en', 'Language options');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (56, 'en', '{{language}} labels');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (57, 'en', 'translate to');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (58, 'en', 'Select language');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (59, 'en', 'No other languages defined');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (60, 'en', 'Add new label');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (61, 'en', 'Add language');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (62, 'en', '{{n}} items');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (63, 'en', 'Select language to edit');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (64, 'en', 'Add new language');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (65, 'en', 'Save');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (66, 'en', 'Please specify text labels for each language. If you do not specify a value for some language, the {{language}} label will be used.');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (67, 'en', 'Label name');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (68, 'en', 'required');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (69, 'en', 'Confirm deletion');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (70, 'en', 'You are going to delete {{language}} language. This operation is irreversable. Are you sure you want to continue?');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (71, 'en', 'Delete');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (72, 'en', 'Cancel');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (73, 'en', '{{language}} Language (Code: {{code}})');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (74, 'en', 'Language name in {{language}}');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (75, 'en', 'Native language name');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (76, 'en', 'Disable');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (77, 'en', 'Enable');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (78, 'en', 'Default for customer zone and can not disabled or deleted');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (79, 'en', 'Set this language as default for customer zone');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (80, 'en', 'Disabled language can not be set as default for customer zone');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (81, 'en', 'Delete Language');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (82, 'en', 'Edit label');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (83, 'en', 'Please specify a pattern to find the required labels');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (84, 'en', 'The language is <span>enabled</span>');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (85, 'en', 'The language is <span>disabled</span>');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (86, 'en', 'The module to uninstall has not been found');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (87, 'en', 'The module has been uninstalled successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (88, 'en', 'The module has been partially uninstalled');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (89, 'en', 'The {{module}} module has been installed successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (90, 'en', 'The {{module}} module has been installed with errors: the DB has not been modified correctly');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (91, 'en', 'The {{module}} module has been installed incorrectly. Please see the logs for more information');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (92, 'en', 'The {{module}} module has been installed, but the module has a wrong module control class');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (93, 'en', 'The {{module}} module has been uninstalled in an abnormal way');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (94, 'en', 'The modules have been updated');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (95, 'en', 'The {{module}} module has been disabled in an abnormal way');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (96, 'en', 'Congratulations! Your order has been successfully placed.<br />Thank you for using our store. An order notification has been sent to your e-mail address.<br />Your order will be processed according to the delivery details.');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (97, 'en', '{{count}} items in bag');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (98, 'en', 'Other items');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (99, 'en', 'The selected shipping method has been deleted successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (100, 'en', 'Shipping methods have been updated');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (101, 'en', 'Shipping methods has been added');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (102, 'en', 'The selected zones have been deleted successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (103, 'en', 'Zone details have been updated successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (104, 'en', 'New zone has been created successfully');
INSERT INTO xlite_language_label_translations (id, code, label) VALUES (105, 'en', 'This product has been added to <a href="{{href}}">your bag</a>');

-- Language names
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',1,'Afar');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',2,'Abkhazian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',3,'Afrikaans');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',4,'Akan');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',5,'Albanian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',6,'Amharic');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',7,'Arabic');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',8,'Aragonese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',9,'Armenian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',10,'Assamese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',11,'Avaric');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',12,'Avestan');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',13,'Aymara');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',14,'Azerbaijani');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',15,'Bashkir');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',16,'Bambara');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',17,'Basque');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',18,'Belarusian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',19,'Bengali');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',20,'Bihari');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',21,'Bislama');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',22,'Bosnian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',23,'Breton');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',24,'Bulgarian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',25,'Burmese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',26,'Catalan');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',27,'Chamorro');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',28,'Chechen');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',29,'Chinese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',30,'Church Slavic');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',31,'Chuvash');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',32,'Cornish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',33,'Corsican');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',34,'Cree');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',35,'Czech');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',36,'Danish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',37,'Divehi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',38,'Dutch');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',39,'Dzongkha');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',40,'English');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',41,'Esperanto');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',42,'Estonian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',43,'Ewe');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',44,'Faroese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',45,'Fijian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',46,'Finnish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',47,'French');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',48,'Western Frisian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',49,'Fulah');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',50,'Georgian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',51,'German');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',52,'Gaelic');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',53,'Irish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',54,'Galician');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',55,'Manx');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',56,'Greek');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',57,'Guarani');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',58,'Gujarati');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',59,'Haitian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',60,'Hausa');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',61,'Hebrew');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',62,'Herero');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',63,'Hindi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',64,'Hiri Motu');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',65,'Croatian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',66,'Hungarian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',67,'Igbo');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',68,'Icelandic');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',69,'Ido');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',70,'Sichuan Yi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',71,'Inuktitut');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',72,'Interlingue');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',73,'Interlingua');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',74,'Indonesian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',75,'Inupiaq');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',76,'Italian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',77,'Javanese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',78,'Japanese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',79,'Kalaallisut');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',80,'Kannada');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',81,'Kashmiri');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',82,'Kanuri');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',83,'Kazakh');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',84,'Central Khmer');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',85,'Kikuyu');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',86,'Kinyarwanda');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',87,'Kirghiz');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',88,'Komi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',89,'Kongo');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',90,'Korean');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',91,'Kuanyama');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',92,'Kurdish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',93,'Lao');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',94,'Latin');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',95,'Latvian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',96,'Limburgan');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',97,'Lingala');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',98,'Lithuanian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',99,'Luxembourgish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',100,'Luba-Katanga');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',101,'Ganda');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',102,'Macedonian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',103,'Marshallese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',104,'Malayalam');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',105,'Maori');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',106,'Marathi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',107,'Malay');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',108,'Malagasy');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',109,'Maltese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',110,'Mongolian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',111,'Nauru');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',112,'Navajo');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',113,'Ndebele, South');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',114,'Ndebele, North');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',115,'Ndonga');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',116,'Nepali');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',117,'Norwegian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',118,'Chichewa');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',119,'Occitan');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',120,'Ojibwa');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',121,'Oriya');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',122,'Oromo');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',123,'Ossetian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',124,'Panjabi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',125,'Persian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',126,'Pali');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',127,'Polish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',128,'Portuguese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',129,'Pushto');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',130,'Quechua');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',131,'Romansh');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',132,'Romanian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',133,'Rundi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',134,'Russian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',135,'Sango');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',136,'Sanskrit');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',137,'Sinhala');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',138,'Slovak');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',139,'Slovenian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',140,'Northern Sami');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',141,'Samoan');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',142,'Shona');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',143,'Sindhi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',144,'Somali');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',145,'Sotho, Southern');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',146,'Spanish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',147,'Sardinian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',148,'Serbian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',149,'Swati');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',150,'Sundanese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',151,'Swahili');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',152,'Swedish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',153,'Tahitian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',154,'Tamil');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',155,'Tatar');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',156,'Telugu');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',157,'Tajik');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',158,'Tagalog');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',159,'Thai');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',160,'Tibetan');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',161,'Tigrinya');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',162,'Tonga');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',163,'Tswana');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',164,'Tsonga');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',165,'Turkmen');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',166,'Turkish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',167,'Twi');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',168,'Uighur');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',169,'Ukrainian');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',170,'Urdu');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',171,'Uzbek');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',172,'Venda');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',173,'Vietnamese');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',174,'Volap&uuml;k');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',175,'Welsh');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',176,'Walloon');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',177,'Wolof');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',178,'Xhosa');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',179,'Yiddish');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',180,'Yoruba');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',181,'Zhuang');
INSERT INTO xlite_language_translations (code, id, name) VALUES ('en',182,'Zulu');

-- Config
INSERT INTO `xlite_config_translations` VALUES (1,'en',2,'active_captcha_pages','');
INSERT INTO `xlite_config_translations` VALUES (2,'en',3,'Checkout desk operation mode','');
INSERT INTO `xlite_config_translations` VALUES (3,'en',4,'Checkout desk operation mode main page','');
INSERT INTO `xlite_config_translations` VALUES (4,'en',5,'Enable admin IP protection system','');
INSERT INTO `xlite_config_translations` VALUES (5,'en',6,'Administrator Zone settings','');
INSERT INTO `xlite_config_translations` VALUES (8,'en',9,'Use HTTPS in the Administrator Zone','');
INSERT INTO `xlite_config_translations` VALUES (9,'en',10,'Enable folding sidebar menus','');
INSERT INTO `xlite_config_translations` VALUES (11,'en',12,'Allow admin IP','');
INSERT INTO `xlite_config_translations` VALUES (24,'en',27,'Enable \"Buy Now\" button in the product list','');
INSERT INTO `xlite_config_translations` VALUES (25,'en',31,'Length of string','');
INSERT INTO `xlite_config_translations` VALUES (26,'en',32,'Image generator options','');
INSERT INTO `xlite_config_translations` VALUES (27,'en',33,'Enable Captcha protection system','');
INSERT INTO `xlite_config_translations` VALUES (28,'en',34,'Where to display','');
INSERT INTO `xlite_config_translations` VALUES (29,'en',35,'Type of string that should be used for the image','');
INSERT INTO `xlite_config_translations` VALUES (32,'en',38,'Clear credit cards info from the database on order status change','');
INSERT INTO `xlite_config_translations` VALUES (40,'en',46,'Address','');
INSERT INTO `xlite_config_translations` VALUES (41,'en',47,'Contacts','');
INSERT INTO `xlite_config_translations` VALUES (42,'en',48,'Fax','');
INSERT INTO `xlite_config_translations` VALUES (43,'en',49,'Identity','');
INSERT INTO `xlite_config_translations` VALUES (44,'en',50,'Company name','');
INSERT INTO `xlite_config_translations` VALUES (45,'en',51,'Phone','');
INSERT INTO `xlite_config_translations` VALUES (46,'en',52,'Company website','');
INSERT INTO `xlite_config_translations` VALUES (52,'en',65,'Customer Zone settings','');
INSERT INTO `xlite_config_translations` VALUES (53,'en',66,'Use HTTPS in the Customer Zone (for login, checkout and profile pages)','');
INSERT INTO `xlite_config_translations` VALUES (54,'en',67,'Date format','');
INSERT INTO `xlite_config_translations` VALUES (55,'en',68,'Currency decimal delimiter','');
INSERT INTO `xlite_config_translations` VALUES (57,'en',71,'Default country in the registration form','');
INSERT INTO `xlite_config_translations` VALUES (58,'en',72,'Payment method to be assumed in case of zero order totals','');
INSERT INTO `xlite_config_translations` VALUES (60,'en',74,'Default purchase limit','');
INSERT INTO `xlite_config_translations` VALUES (61,'en',75,'Default payment method','');
INSERT INTO `xlite_config_translations` VALUES (62,'en',76,'Default zip/postal code in the registration form','');
INSERT INTO `xlite_config_translations` VALUES (63,'en',77,'Display shipping rates to unregistered customers<br>(presuming that a customer comes from the default country)','');
INSERT INTO `xlite_config_translations` VALUES (64,'en',80,'Developer\'s mode (force to re-generate cache)','');
INSERT INTO `xlite_config_translations` VALUES (67,'en',89,'Allow direct URL access to products from disabled categories','');
INSERT INTO `xlite_config_translations` VALUES (68,'en',90,'Discounts charged after taxes application','');
INSERT INTO `xlite_config_translations` VALUES (69,'en',91,'Display check number for eCheck payment method','');
INSERT INTO `xlite_config_translations` VALUES (76,'en',100,'Enable anonymous checkout','');
INSERT INTO `xlite_config_translations` VALUES (77,'en',101,'Enable extra fields in the category management dialogue','');
INSERT INTO `xlite_config_translations` VALUES (78,'en',102,'Validate credit cards','');
INSERT INTO `xlite_config_translations` VALUES (79,'en',103,'Enable products to inherit extra fields from disabled categories','');
INSERT INTO `xlite_config_translations` VALUES (80,'en',104,'E-mail order details to the sales department after order placement','');
INSERT INTO `xlite_config_translations` VALUES (81,'en',105,'E-mail order details to customers after order placement','');
INSERT INTO `xlite_config_translations` VALUES (83,'en',107,'Enable \"Market price\" feature','');
INSERT INTO `xlite_config_translations` VALUES (93,'en',120,'Enable admin forms protection system','');
INSERT INTO `xlite_config_translations` VALUES (101,'en',128,'Customer Zone fully on HTTPS','');
INSERT INTO `xlite_config_translations` VALUES (107,'en',138,'Enable .htaccess verification system','');
INSERT INTO `xlite_config_translations` VALUES (108,'en',140,'HTTPS client to use (for integration with secure payment/shipping services)','');
INSERT INTO `xlite_config_translations` VALUES (109,'en',141,'Includes tax message','');
INSERT INTO `xlite_config_translations` VALUES (112,'en',153,'Street address','');
INSERT INTO `xlite_config_translations` VALUES (113,'en',154,'City','');
INSERT INTO `xlite_config_translations` VALUES (114,'en',155,'Country','');
INSERT INTO `xlite_config_translations` VALUES (115,'en',156,'Other state (specify)','');
INSERT INTO `xlite_config_translations` VALUES (116,'en',157,'State','');
INSERT INTO `xlite_config_translations` VALUES (117,'en',158,'Zip/postal code','');
INSERT INTO `xlite_config_translations` VALUES (118,'en',159,'Days to store last login data','');
INSERT INTO `xlite_config_translations` VALUES (119,'en',160,'Clear cart on customer logoff','');
INSERT INTO `xlite_config_translations` VALUES (122,'en',165,'Maximum allowed order total','');
INSERT INTO `xlite_config_translations` VALUES (123,'en',166,'Membership levels','');
INSERT INTO `xlite_config_translations` VALUES (124,'en',167,'Membership levels','');
INSERT INTO `xlite_config_translations` VALUES (126,'en',170,'Minimum allowed order total','');
INSERT INTO `xlite_config_translations` VALUES (135,'en',179,'Maintenance and operation','');
INSERT INTO `xlite_config_translations` VALUES (136,'en',180,'Sales department e-mail','');
INSERT INTO `xlite_config_translations` VALUES (137,'en',181,'Orders per page','');
INSERT INTO `xlite_config_translations` VALUES (138,'en',182,'Initial order number','');
INSERT INTO `xlite_config_translations` VALUES (151,'en',205,'Prices include tax','');
INSERT INTO `xlite_config_translations` VALUES (153,'en',207,'Currency format','');
INSERT INTO `xlite_config_translations` VALUES (156,'en',210,'Products per category listing page','');
INSERT INTO `xlite_config_translations` VALUES (157,'en',211,'Products per page','');
INSERT INTO `xlite_config_translations` VALUES (159,'en',214,'HTTPS proxy','');
INSERT INTO `xlite_config_translations` VALUES (161,'en',216,'Amount of orders in the recent orders list','');
INSERT INTO `xlite_config_translations` VALUES (162,'en',217,'Redirect customer to cart when adding a product','');
INSERT INTO `xlite_config_translations` VALUES (172,'en',228,'Safe mode (do not initialize modules)','');
INSERT INTO `xlite_config_translations` VALUES (175,'en',234,'Check this to temporary close the shop','');
INSERT INTO `xlite_config_translations` VALUES (177,'en',236,'Include order details (credit card or eCheck information) into admin order notification message','');
INSERT INTO `xlite_config_translations` VALUES (178,'en',237,'Show thumbnails in product list','');
INSERT INTO `xlite_config_translations` VALUES (179,'en',238,'Site administrator e-mail','');
INSERT INTO `xlite_config_translations` VALUES (180,'en',239,'Password','');
INSERT INTO `xlite_config_translations` VALUES (181,'en',240,'Secure connection','');
INSERT INTO `xlite_config_translations` VALUES (182,'en',241,'SMTP server','');
INSERT INTO `xlite_config_translations` VALUES (183,'en',242,'SMTP port','');
INSERT INTO `xlite_config_translations` VALUES (184,'en',243,'SMTP server','');
INSERT INTO `xlite_config_translations` VALUES (185,'en',244,'Username','');
INSERT INTO `xlite_config_translations` VALUES (186,'en',245,'Year when store started its operation','');
INSERT INTO `xlite_config_translations` VALUES (188,'en',247,'Category listings format','');
INSERT INTO `xlite_config_translations` VALUES (189,'en',248,'HelpDesk/Support service e-mail','');
INSERT INTO `xlite_config_translations` VALUES (190,'en',250,'Tax rates','');
INSERT INTO `xlite_config_translations` VALUES (191,'en',252,'Currency thousands delimiter','');
INSERT INTO `xlite_config_translations` VALUES (194,'en',255,'Time format','');
INSERT INTO `xlite_config_translations` VALUES (195,'en',256,'Time zone','');
INSERT INTO `xlite_config_translations` VALUES (197,'en',258,'Units of measurement','');
INSERT INTO `xlite_config_translations` VALUES (198,'en',265,'Customer relations e-mail','');
INSERT INTO `xlite_config_translations` VALUES (199,'en',266,'Users per page','');
INSERT INTO `xlite_config_translations` VALUES (200,'en',268,'Use billing info to calculate taxes','');
INSERT INTO `xlite_config_translations` VALUES (201,'en',269,'Use SMTP server','');
INSERT INTO `xlite_config_translations` VALUES (202,'en',270,'Use authentication','');
INSERT INTO `xlite_config_translations` VALUES (203,'en',271,'Valid domain names for email','');
INSERT INTO `xlite_config_translations` VALUES (204,'en',275,'Weight symbol','');
INSERT INTO `xlite_config_translations` VALUES (205,'en',276,'Weight unit','');
INSERT INTO `xlite_config_translations` VALUES (224,'en',299,'Enable \"save\" label (for Market Price)','');

INSERT INTO `xlite_config_translations` VALUES (225,'en',310,'Default customer shipping address','');
INSERT INTO `xlite_config_translations` VALUES (226,'en',311,'Address line','');
INSERT INTO `xlite_config_translations` VALUES (227,'en',312,'City','');
INSERT INTO `xlite_config_translations` VALUES (228,'en',313,'Country','');
INSERT INTO `xlite_config_translations` VALUES (229,'en',314,'Other state (specify)','');
INSERT INTO `xlite_config_translations` VALUES (230,'en',315,'State','');
INSERT INTO `xlite_config_translations` VALUES (231,'en',316,'Zip/postal code','');


-- Memberships
INSERT INTO xlite_membership_translations (id, code, name) VALUES (1, 'en', 'Gold');
INSERT INTO xlite_membership_translations (id, code, name) VALUES (2, 'en', 'Platinum');
INSERT INTO xlite_membership_translations (id, code, name) VALUES (3, 'en', 'Wholesaler');
