INSERT INTO `xlite_config` VALUES (2,'active_captcha_pages','Captcha','serialized',30,'');
INSERT INTO `xlite_config` VALUES (3,'add_on_mode','General','checkbox',120,'N');
INSERT INTO `xlite_config` VALUES (4,'add_on_mode_page','General','select',125,'cart.php?target=cart');
INSERT INTO `xlite_config` VALUES (5,'admin_ip_protection','Security','checkbox',100,'N');
INSERT INTO `xlite_config` VALUES (6,'admin_presentation','General','separator',400,'');
INSERT INTO `xlite_config` VALUES (9,'admin_security','Security','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (10,'admin_zone_sbbe_enabled','General','checkbox',490,'Y');
INSERT INTO `xlite_config` VALUES (12,'allow_admin_ip','SecurityIP','',40,'');
INSERT INTO `xlite_config` VALUES (27,'buynow_button_enabled','General','checkbox',240,'Y');
INSERT INTO `xlite_config` VALUES (29,'callback_code','Shipping','text',0,'');
INSERT INTO `xlite_config` VALUES (30,'callback_status','Shipping','text',0,'');
INSERT INTO `xlite_config` VALUES (31,'captcha_length','Captcha','text',20,'5');
INSERT INTO `xlite_config` VALUES (32,'captcha_protection','Captcha','separator',0,'');
INSERT INTO `xlite_config` VALUES (33,'captcha_protection_system','Security','checkbox',110,'N');
INSERT INTO `xlite_config` VALUES (34,'captcha_separator_pages','Captcha','separator',30,'');
INSERT INTO `xlite_config` VALUES (35,'captcha_type','Captcha','select',10,'all');
INSERT INTO `xlite_config` VALUES (38,'clear_cc_info','General','select',500,'N');
INSERT INTO `xlite_config` VALUES (46,'company_address','Company','separator',385,'');
INSERT INTO `xlite_config` VALUES (47,'company_contacts','Company','separator',455,'');
INSERT INTO `xlite_config` VALUES (48,'company_fax','Company','text',420,'(555) 555-5555');
INSERT INTO `xlite_config` VALUES (49,'company_identity','Company','separator',350,'');
INSERT INTO `xlite_config` VALUES (50,'company_name','Company','text',360,'*Your company name*');
INSERT INTO `xlite_config` VALUES (51,'company_phone','Company','text',410,'(555) 555-5555');
INSERT INTO `xlite_config` VALUES (52,'company_website','Company','text',370,'http://');
INSERT INTO `xlite_config` VALUES (65,'customer_presentation','General','separator',200,'');
INSERT INTO `xlite_config` VALUES (66,'customer_security','Security','checkbox',0,'Y');
INSERT INTO `xlite_config` VALUES (67,'date_format','General','select',660,'%m/%d/%Y');
INSERT INTO `xlite_config` VALUES (68,'decimal_delim','General','select',650,'.');
INSERT INTO `xlite_config` VALUES (70,'defaultSources','Images','serialized',0,'');
INSERT INTO `xlite_config` VALUES (71,'default_country','General','country',310,'US');
INSERT INTO `xlite_config` VALUES (72,'default_offline_payment','Payments','text',0,'');
INSERT INTO `xlite_config` VALUES (74,'default_purchase_limit','General','text',293,'9999');
INSERT INTO `xlite_config` VALUES (75,'default_select_payment','Payments','text',0,'');
INSERT INTO `xlite_config` VALUES (76,'default_zipcode','General','text',320,'10000');
INSERT INTO `xlite_config` VALUES (77,'def_calc_shippings_taxes','General','checkbox',260,'N');
INSERT INTO `xlite_config` VALUES (80,'developer_mode','General','checkbox',105,'');
INSERT INTO `xlite_config` VALUES (89,'direct_product_url','General','checkbox',255,'N');
INSERT INTO `xlite_config` VALUES (90,'discounts_after_taxes','Taxes','checkbox',210,'N');
INSERT INTO `xlite_config` VALUES (91,'display_check_number','General','checkbox',215,'Y');
INSERT INTO `xlite_config` VALUES (100,'enable_anon_checkout','General','checkbox',270,'Y');
INSERT INTO `xlite_config` VALUES (101,'enable_categories_extra_fields','General','checkbox',470,'Y');
INSERT INTO `xlite_config` VALUES (102,'enable_credit_card_validation','General','checkbox',210,'Y');
INSERT INTO `xlite_config` VALUES (103,'enable_extra_fields_inherit','General','checkbox',480,'Y');
INSERT INTO `xlite_config` VALUES (104,'enable_init_order_notif','Email','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (105,'enable_init_order_notif_customer','Email','checkbox',0,'N');
INSERT INTO `xlite_config` VALUES (107,'enable_sale_price','General','checkbox',295,'Y');
INSERT INTO `xlite_config` VALUES (120,'form_id_protection','Security','checkbox',90,'Y');
INSERT INTO `xlite_config` VALUES (128,'full_customer_security','Security','checkbox',5,'N');
INSERT INTO `xlite_config` VALUES (138,'htaccess_protection','Security','checkbox',110,'Y');
INSERT INTO `xlite_config` VALUES (140,'httpsClient','Security','select',20,'autodetect');
INSERT INTO `xlite_config` VALUES (141,'include_tax_message','Taxes','text',0,', including VAT');
INSERT INTO `xlite_config` VALUES (145,'last_date','Htaccess','',0,'0');
INSERT INTO `xlite_config` VALUES (151,'license','License','text',0,'');
INSERT INTO `xlite_config` VALUES (153,'location_address','Company','text',390,'*Your company address*');
INSERT INTO `xlite_config` VALUES (154,'location_city','Company','text',400,'*You company city*');
INSERT INTO `xlite_config` VALUES (155,'location_country','Company','country',450,'US');
INSERT INTO `xlite_config` VALUES (156,'location_custom_state','Company','text',435,'');
INSERT INTO `xlite_config` VALUES (157,'location_state','Company','state',430,'17');
INSERT INTO `xlite_config` VALUES (158,'location_zipcode','Company','text',440,'50001');
INSERT INTO `xlite_config` VALUES (159,'login_lifetime','General','text',450,'3');
INSERT INTO `xlite_config` VALUES (160,'logoff_clear_cart','Security','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (165,'maximal_order_amount','General','text',290,'99999');
INSERT INTO `xlite_config` VALUES (166,'memberships','Memberships','serialized',0,'a:0:{}');
INSERT INTO `xlite_config` VALUES (167,'membershipsCollection','Memberships','serialized',0,'a:3:{i:1;a:3:{s:7:\"orderby\";s:2:\"10\";s:10:\"membership\";s:4:\"Gold\";s:13:\"membership_id\";i:1;}i:2;a:3:{s:7:\"orderby\";s:2:\"20\";s:10:\"membership\";s:8:\"Platinum\";s:13:\"membership_id\";i:2;}i:3;a:3:{s:7:\"orderby\";s:2:\"30\";s:10:\"membership\";s:10:\"Wholesaler\";s:13:\"membership_id\";i:3;}}');
INSERT INTO `xlite_config` VALUES (170,'minimal_order_amount','General','text',280,'10');
INSERT INTO `xlite_config` VALUES (179,'operation_presentation','General','separator',100,'');
INSERT INTO `xlite_config` VALUES (180,'orders_department','Company','text',480,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (181,'orders_per_page','General','text',430,'30');
INSERT INTO `xlite_config` VALUES (182,'order_starting_number','General','text',460,'1');
INSERT INTO `xlite_config` VALUES (197,'params','XCartImport','serialized',0,'a:0:{}');
INSERT INTO `xlite_config` VALUES (199,'partner_product_banner','Miscellaneous','serialized',0,'a:11:{s:11:\"link_target\";s:4:\"_top\";s:5:\"image\";s:9:\"thumbnail\";s:6:\"border\";i:1;s:12:\"product_name\";i:1;s:11:\"description\";s:0:\"\";s:7:\"message\";s:8:\"Buy new!\";s:16:\"background_color\";s:6:\"ffffff\";s:10:\"text_color\";s:6:\"000000\";s:10:\"link_color\";s:6:\"6633ff\";s:5:\"width\";i:120;s:6:\"height\";i:240;}');
INSERT INTO `xlite_config` VALUES (200,'partner_profile','Miscellaneous','serialized',0,'a:8:{s:17:\"billing_firstname\";s:2:\"on\";s:16:\"billing_lastname\";s:2:\"on\";s:13:\"billing_phone\";s:2:\"on\";s:15:\"billing_address\";s:2:\"on\";s:12:\"billing_city\";s:2:\"on\";s:13:\"billing_state\";s:2:\"on\";s:15:\"billing_country\";s:2:\"on\";s:15:\"billing_zipcode\";s:2:\"on\";}');
INSERT INTO `xlite_config` VALUES (205,'prices_include_tax','Taxes','checkbox',200,'N');
INSERT INTO `xlite_config` VALUES (207,'price_format','General','text',630,'$ %s');
INSERT INTO `xlite_config` VALUES (210,'products_per_page','General','text',250,'10');
INSERT INTO `xlite_config` VALUES (211,'products_per_page_admin','General','text',410,'30');
INSERT INTO `xlite_config` VALUES (212,'product_layout','ImportExport',NULL,0,'sku,name,category,brief_description,description,thumbnail,image,price,tax_class,weight,order_by,enabled,NULL');
INSERT INTO `xlite_config` VALUES (214,'proxy','Security','text',25,'');
INSERT INTO `xlite_config` VALUES (216,'recent_orders','General','text',440,'10');
INSERT INTO `xlite_config` VALUES (217,'redirect_to_cart','General','checkbox',300,'Y');
INSERT INTO `xlite_config` VALUES (228,'safe_mode','General','checkbox',130,'N');
INSERT INTO `xlite_config` VALUES (233,'shipping_code','Shipping','text',0,'1702936249');
INSERT INTO `xlite_config` VALUES (234,'shop_closed','General','checkbox',110,'N');
INSERT INTO `xlite_config` VALUES (236,'show_cc_info','Email','checkbox',40,'N');
INSERT INTO `xlite_config` VALUES (237,'show_thumbnails','General','checkbox',230,'Y');
INSERT INTO `xlite_config` VALUES (238,'site_administrator','Company','text',460,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (239,'smtp_password','Email','text',160,'');
INSERT INTO `xlite_config` VALUES (240,'smtp_security','Email','select',170,'no');
INSERT INTO `xlite_config` VALUES (241,'smtp_server','Email','separator',100,'');
INSERT INTO `xlite_config` VALUES (242,'smtp_server_port','Email','text',130,'25');
INSERT INTO `xlite_config` VALUES (243,'smtp_server_url','Email','text',120,'');
INSERT INTO `xlite_config` VALUES (244,'smtp_username','Email','text',150,'');
INSERT INTO `xlite_config` VALUES (245,'start_year','Company','text',380,'2009');
INSERT INTO `xlite_config` VALUES (247,'subcategories_look','General','select',220,'icons');
INSERT INTO `xlite_config` VALUES (248,'support_department','Company','text',490,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (249,'taxes','Taxes','text',0,'a:1:{i:0;a:2:{s:4:\"name\";s:3:\"Tax\";s:13:\"display_label\";s:3:\"Tax\";}}');
INSERT INTO `xlite_config` VALUES (250,'tax_rates','Taxes','',20,'a:3:{i:0;s:6:\"Tax:=0\";i:1;a:2:{s:9:\"condition\";s:30:\"product class=shipping service\";s:6:\"action\";s:6:\"Tax:=0\";}i:2;a:2:{s:9:\"condition\";s:22:\"product class=Tax free\";s:6:\"action\";s:6:\"Tax:=0\";}}');
INSERT INTO `xlite_config` VALUES (252,'thousand_delim','General','select',640,',');
INSERT INTO `xlite_config` VALUES (255,'time_format','General','select',670,'%H:%M');
INSERT INTO `xlite_config` VALUES (256,'time_zone','General','select',680,'');
INSERT INTO `xlite_config` VALUES (258,'unit_presentation','General','separator',600,'');
INSERT INTO `xlite_config` VALUES (265,'users_department','Company','text',470,'bit-bucket@x-cart.com');
INSERT INTO `xlite_config` VALUES (266,'users_per_page','General','text',420,'30');
INSERT INTO `xlite_config` VALUES (267,'user_layout','ImportExport',NULL,0,'login, password, billing_firstname, billing_lastname');
INSERT INTO `xlite_config` VALUES (268,'use_billing_info','Taxes','checkbox',10,'N');
INSERT INTO `xlite_config` VALUES (269,'use_smtp','Email','checkbox',110,'N');
INSERT INTO `xlite_config` VALUES (270,'use_smtp_auth','Email','checkbox',140,'N');
INSERT INTO `xlite_config` VALUES (271,'valid_email_domains','Email','text',30,'com;net;edu;mil;gov;org;biz');
INSERT INTO `xlite_config` VALUES (273,'version','Version','',0,'3.x-dev');
INSERT INTO `xlite_config` VALUES (275,'weight_symbol','General','text',620,'lbs');
INSERT INTO `xlite_config` VALUES (276,'weight_unit','General','select',610,'lbs');
INSERT INTO `xlite_config` VALUES (299,'you_save','General','select',296,'Y');
INSERT INTO `xlite_config` VALUES (300,'default_language','General','',330,'en');




-- ********************************************************************************************************************



INSERT INTO xlite_countries VALUES ('Afghanistan','AF','Dari, Pushtu','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Albania','AL','Albanian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Algeria','DZ','Arabic','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('American Samoa','AS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Andorra','AD','Catalan','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Angola','AO','Portuguese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Anguilla','AI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Antarctica','AQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Antigua and Barbuda','AG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Argentina','AR','Spanish','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Armenia','AM','Armenian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Aruba','AW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Australia','AU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Austria','AT','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Azerbaijan','AZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bahamas','BS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bahrain','BH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bangladesh','BD','Bengali','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Barbados','BB','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Belarus','BY','Belarussian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Belgium','BE','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Belize','BZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Benin','BJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bermuda','BM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bhutan','BT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bolivia','BO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bosnia and Herzegowina','BA','Bosnian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Botswana','BW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bouvet Island','BV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Brazil','BR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('British Indian Ocean Territory','IO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('British Virgin Islands','VG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Brunei Darussalam','BN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Bulgaria','BG','Bulgarian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='BG';
INSERT INTO xlite_countries VALUES ('Burkina Faso','BF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Burundi','BI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cambodia','KH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cameroon','CM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Canada','CA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cape Verde','CV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cayman Islands','KY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Central African Republic','CF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Chad','TD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Chile','CL','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('China','CN','Chinese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Christmas Island','CX','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cocos (Keeling) Islands','CC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Colombia','CO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Comoros','KM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Congo, Democratic Republic of','CD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cook Islands','CK','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Costa Rica','CR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cote D\'ivoire','CI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Croatia','HR','Croatian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cuba','CU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Cyprus','CY','Greek','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='CY';
INSERT INTO xlite_countries VALUES ('Czech Republic','CZ','Czech','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Czechoslovakia','CS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Denmark','DK','Danish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Djibouti','DJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Dominica','DM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Dominican Republic','DO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('East Timor','TP','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Ecuador','EC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Egypt','EG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('El Salvador','SV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Equatorial Guinea','GQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Eritrea','ER','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Estonia','EE','Estonian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='EE';
INSERT INTO xlite_countries VALUES ('Ethiopia','ET','Amharic','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Falkland Islands (Malvinas)','FK','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Faroe Islands','FO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Fiji','FJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Finland','FI','Finnish, Swedish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('France','FR','French','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('France, Metropolitan','FX','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('French Guiana','GF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('French Polynesia','PF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('French Southern Territories','TF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Gabon','GA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Gambia','GM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Georgia','GE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Germany','DE','German','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Ghana','GH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Gibraltar','GI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Greece','GR','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Greenland','GL','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Grenada','GD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guadeloupe','GP','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guam','GU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guatemala','GT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guinea','GN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guinea-Bissau','GW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Guyana','GY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Haiti','HT','Creole','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Heard and McDonald Islands','HM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Honduras','HN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Hong Kong','HK','Mandarin','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Hungary','HU','Hungarian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='HU';
INSERT INTO xlite_countries VALUES ('Iceland','IS','Icelandic','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('India','IN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Indonesia','ID','Indonesian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Iraq','IQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Ireland','IE','Irish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Islamic Republic of Iran','IR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Israel','IL','Hebrew','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Italy','IT','Italian','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Jamaica','JM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Japan','JP','Japanese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Jordan','JO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kazakhstan','KZ','Kazakh','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kenya','KE','Kiswahili','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kiribati','KI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Korea','KP','Korean','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Korea, Republic of','KR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kuwait','KW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Kyrgyzstan','KG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Laos','LA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Latvia','LV','Latvian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='LV';
INSERT INTO xlite_countries VALUES ('Lebanon','LB','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Lesotho','LS','Sesotho','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Liberia','LR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Libyan Arab Jamahiriya','LY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Liechtenstein','LI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Lithuania','LT','Lithuanian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='LT';
INSERT INTO xlite_countries VALUES ('Luxembourg','LU','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Macau','MO','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Macedonia','MK','Macedonian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Madagascar','MG','Malagasy','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Malawi','MW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Malaysia','MY','Malay','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Maldives','MV','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mali','ML','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Malta','MT','Maltese','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='MT';
INSERT INTO xlite_countries VALUES ('Marshall Islands','MH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Martinique','MQ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mauritania','MR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mauritius','MU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mayotte','YT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mexico','MX','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Micronesia','FM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Moldova, Republic of','MD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Monaco','MC','','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='MC';
INSERT INTO xlite_countries VALUES ('Mongolia','MN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Montserrat','MS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Morocco','MA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Mozambique','MZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Myanmar','MM','Burmese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Namibia','NA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nauru','NR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nepal','NP','Nepali','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Netherlands','NL','Dutch','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Netherlands Antilles','AN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('New Caledonia','NC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('New Zealand','NZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nicaragua','NI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Niger','NE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Nigeria','NG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Niue','NU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Norfolk Island','NF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Northern Mariana Islands','MP','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Norway','NO','Norwegian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Oman','OM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Pakistan','PK','Urdu','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Palau','PW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Panama','PA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Papua New Guinea','PG','Pidgin','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Paraguay','PY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Peru','PE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Philippines','PH','Filipino','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Pitcairn','PN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Poland','PL','Polish','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='PL';
INSERT INTO xlite_countries VALUES ('Portugal','PT','Portuguese','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Puerto Rico','PR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Qatar','QA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Reunion','RE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Romania','RO','Romanian','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='RO';
INSERT INTO xlite_countries VALUES ('Russian Federation','RU','Russian','Windows-1251',1,'N',0);
INSERT INTO xlite_countries VALUES ('Rwanda','RW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Saint Lucia','LC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Samoa','WS','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('San Marino','SM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sao Tome and Principe','ST','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Saudi Arabia','SA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Senegal','SN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Seychelles','SC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sierra Leone','SL','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Singapore','SG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Slovakia','SK','Slovak','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='SK';
INSERT INTO xlite_countries VALUES ('Slovenia','SI','Slovene','iso-8859-1',1,'Y',0);
-- UPDATE xlite_countries SET eu_member='Y' WHERE code='SI';
INSERT INTO xlite_countries VALUES ('Solomon Islands','SB','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Somalia','SO','Somali','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('South Africa','ZA','Afrikaans','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Spain','ES','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Sri Lanka','LK','Sinhala','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Helena','SH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Kitts And Nevis','KN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Pierre and Miquelon','PM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('St. Vincent And The Greadines','VC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sudan','SD','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Suriname','SR','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Svalbard and Jan Mayen Islands','SJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Swaziland','SZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Sweden','SE','Swedish','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('Switzerland','CH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Syrian Arab Republic','SY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Taiwan','TW','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tajikistan','TJ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tanzania, United Republic of','TZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Thailand','TH','Thai','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Togo','TG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tokelau','TK','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tonga','TO','Tongan','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Trinidad and Tobago','TT','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tunisia','TN','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Turkey','TR','Turkish','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Turkmenistan','TM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Turks and Caicos Islands','TC','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Tuvalu','TV','Tuvaluan','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Uganda','UG','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Ukraine','UA','Ukrainian','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('United Arab Emirates','AE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('United Kingdom (Great Britain)','GB','','iso-8859-1',1,'Y',0);
INSERT INTO xlite_countries VALUES ('United States','US','English','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('United States Virgin Islands','VI','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Uruguay','UY','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Uzbekistan','UZ','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Vanuatu','VU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Vatican City State','VA','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Venezuela','VE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Viet Nam','VN','Vietnamese','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Wallis And Futuna Islands','WF','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Western Sahara','EH','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Yemen','YE','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Serbia and Montenegro','YU','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Zambia','ZM','','iso-8859-1',1,'N',0);
INSERT INTO xlite_countries VALUES ('Zimbabwe','ZW','','iso-8859-1',1,'N',0);

INSERT INTO xlite_payment_methods VALUES ('CreditCard','Credit Card','Visa, Mastercard, American Express','CreditCard','',10,1);
INSERT INTO xlite_payment_methods VALUES ('PurchaseOrder','Purchase Order','','Offline','',20,1);
INSERT INTO xlite_payment_methods VALUES ('PhoneOrdering','Phone Ordering','Phone: (555) 555-5555','Offline','',30,1);
INSERT INTO xlite_payment_methods VALUES ('FaxOrdering','Fax Ordering','Fax: (555) 555-5555','Offline','',40,1);
INSERT INTO xlite_payment_methods VALUES ('MoneyOrdering','Money Order','US Banks Only','Offline','',45,1);
INSERT INTO xlite_payment_methods VALUES ('Echeck','Check','Check payment','Echeck','',50,1);
INSERT INTO xlite_payment_methods VALUES ('COD','COD','Cash On Delivery','Offline','',60,1);

INSERT INTO xlite_shipping VALUES (2,'Offline','L','National shipping',1,10);
INSERT INTO xlite_shipping VALUES (3,'Offline','I','International shipping',1,20);

INSERT INTO `xlite_shipping_rates` VALUES (2,'0.00','999999.00','0.00','999999.00',0,'2.00','0.00','0.00','0.00',0,999999);
INSERT INTO `xlite_shipping_rates` VALUES (3,'0.00','999999.00','0.00','999999.00',0,'5.00','0.00','0.00','0.00',0,999999);

-- Languages
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (1,'aa','aar');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (2,'ab','abk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (3,'af','afr');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (4,'ak','aka');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (5,'sq','alb');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (6,'am','amh');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (7,'ar','ara');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (8,'an','arg');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (9,'hy','arm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (10,'as','asm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (11,'av','ava');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (12,'ae','ave');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (13,'ay','aym');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (14,'az','aze');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (15,'ba','bak');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (16,'bm','bam');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (17,'eu','baq');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (18,'be','bel');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (19,'bn','ben');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (20,'bh','bih');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (21,'bi','bis');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (22,'bs','bos');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (23,'br','bre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (24,'bg','bul');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (25,'my','bur');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (26,'ca','cat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (27,'ch','cha');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (28,'ce','che');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (29,'zh','chi');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (30,'cu','chu');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (31,'cv','chv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (32,'kw','cor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (33,'co','cos');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (34,'cr','cre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (35,'cs','cze');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (36,'da','dan');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (37,'dv','div');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (38,'nl','dut');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (39,'dz','dzo');
INSERT INTO xlite_languages (lng_id, code, code3, status) VALUES (40,'en','eng',2);
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (41,'eo','epo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (42,'et','est');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (43,'ee','ewe');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (44,'fo','fao');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (45,'fj','fij');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (46,'fi','fin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (47,'fr','fre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (48,'fy','fry');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (49,'ff','ful');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (50,'ka','geo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (51,'de','ger');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (52,'gd','gla');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (53,'ga','gle');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (54,'gl','glg');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (55,'gv','glv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (56,'el','gre');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (57,'gn','grn');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (58,'gu','guj');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (59,'ht','hat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (60,'ha','hau');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (61,'he','heb');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (62,'hz','her');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (63,'hi','hin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (64,'ho','hmo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (65,'hr','hrv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (66,'hu','hun');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (67,'ig','ibo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (68,'is','ice');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (69,'io','ido');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (70,'ii','iii');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (71,'iu','iku');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (72,'ie','ile');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (73,'ia','ina');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (74,'id','ind');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (75,'ik','ipk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (76,'it','ita');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (77,'jv','jav');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (78,'ja','jpn');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (79,'kl','kal');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (80,'kn','kan');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (81,'ks','kas');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (82,'kr','kau');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (83,'kk','kaz');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (84,'km','khm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (85,'ki','kik');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (86,'rw','kin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (87,'ky','kir');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (88,'kv','kom');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (89,'kg','kon');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (90,'ko','kor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (91,'kj','kua');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (92,'ku','kur');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (93,'lo','lao');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (94,'la','lat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (95,'lv','lav');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (96,'li','lim');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (97,'ln','lin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (98,'lt','lit');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (99,'lb','ltz');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (100,'lu','lub');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (101,'lg','lug');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (102,'mk','mac');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (103,'mh','mah');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (104,'ml','mal');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (105,'mi','mao');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (106,'mr','mar');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (107,'ms','may');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (108,'mg','mlg');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (109,'mt','mlt');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (110,'mn','mon');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (111,'na','nau');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (112,'nv','nav');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (113,'nr','nbl');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (114,'nd','nde');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (115,'ng','ndo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (116,'ne','nep');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (117,'no','nor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (118,'ny','nya');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (119,'oc','oci');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (120,'oj','oji');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (121,'or','ori');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (122,'om','orm');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (123,'os','oss');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (124,'pa','pan');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (125,'fa','per');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (126,'pi','pli');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (127,'pl','pol');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (128,'pt','por');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (129,'ps','pus');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (130,'qu','que');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (131,'rm','roh');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (132,'ro','rum');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (133,'rn','run');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (134,'ru','rus');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (135,'sg','sag');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (136,'sa','san');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (137,'si','sin');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (138,'sk','slo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (139,'sl','slv');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (140,'se','sme');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (141,'sm','smo');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (142,'sn','sna');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (143,'sd','snd');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (144,'so','som');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (145,'st','sot');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (146,'es','spa');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (147,'sc','srd');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (148,'sr','srp');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (149,'ss','ssw');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (150,'su','sun');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (151,'sw','swa');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (152,'sv','swe');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (153,'ty','tah');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (154,'ta','tam');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (155,'tt','tat');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (156,'te','tel');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (157,'tg','tgk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (158,'tl','tgl');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (159,'th','tha');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (160,'bo','tib');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (161,'ti','tir');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (162,'to','ton');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (163,'tn','tsn');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (164,'ts','tso');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (165,'tk','tuk');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (166,'tr','tur');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (167,'tw','twi');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (168,'ug','uig');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (169,'uk','ukr');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (170,'ur','urd');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (171,'uz','uzb');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (172,'ve','ven');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (173,'vi','vie');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (174,'vo','vol');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (175,'cy','wel');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (176,'wa','wln');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (177,'wo','wol');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (178,'xh','xho');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (179,'yi','yid');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (180,'yo','yor');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (181,'za','zha');
INSERT INTO xlite_languages (lng_id, code, code3) VALUES (182,'zu','zul');

-- Memberships
INSERT INTO xlite_memberships VALUES (1, 10, 1);
INSERT INTO xlite_memberships VALUES (2, 20, 1);
INSERT INTO xlite_memberships VALUES (3, 30, 1);

-- Language labels
INSERT INTO xlite_language_labels (label_id, name) VALUES (1, 'Weight');
INSERT INTO xlite_language_labels (label_id, name) VALUES (2, 'Add to cart');
INSERT INTO xlite_language_labels (label_id, name) VALUES (3, 'Description');
INSERT INTO xlite_language_labels (label_id, name) VALUES (4, 'SKU');
INSERT INTO xlite_language_labels (label_id, name) VALUES (5, 'Previous product');
INSERT INTO xlite_language_labels (label_id, name) VALUES (6, 'Next product');
INSERT INTO xlite_language_labels (label_id, name) VALUES (7, 'Clear cart');
INSERT INTO xlite_language_labels (label_id, name) VALUES (8, 'Continue shopping');
INSERT INTO xlite_language_labels (label_id, name) VALUES (9, 'Submit');
INSERT INTO xlite_language_labels (label_id, name) VALUES (10, 'Delivery');
INSERT INTO xlite_language_labels (label_id, name) VALUES (11, 'This product is out of stock or it has been disabled for sale');
INSERT INTO xlite_language_labels (label_id, name) VALUES (12, 'Update');
INSERT INTO xlite_language_labels (label_id, name) VALUES (13, 'Grand total');
INSERT INTO xlite_language_labels (label_id, name) VALUES (14, 'Shipping cost');
INSERT INTO xlite_language_labels (label_id, name) VALUES (15, 'Free');
INSERT INTO xlite_language_labels (label_id, name) VALUES (16, 'Subtotal');
INSERT INTO xlite_language_labels (label_id, name) VALUES (17, 'Tax');
INSERT INTO xlite_language_labels (label_id, name) VALUES (18, 'n/a');
INSERT INTO xlite_language_labels (label_id, name) VALUES (19, 'Your shopping cart is empty');
INSERT INTO xlite_language_labels (label_id, name) VALUES (20, 'Delete item');
INSERT INTO xlite_language_labels (label_id, name) VALUES (21, 'Continue...');
INSERT INTO xlite_language_labels (label_id, name) VALUES (22, 'The language you want to add has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (23, 'The language you want to add has already been added');
INSERT INTO xlite_language_labels (label_id, name) VALUES (24, 'The X language has been added successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (25, 'The language you want to delete has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (26, 'The language you want to delete is the default application language and cannot be deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (27, 'The language you want to delete is the default interface language and cannot be deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (28, 'The X language has been deleted successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (29, 'The language has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (30, 'The default interface language cannot be disabled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (31, 'The X language has been disabled successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (32, 'The X language has been enabled successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (33, 'Text labels have been updated successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (34, 'Text labels have not been updated successfully: the translation language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (35, 'Text labels have not been updated successfully: the default application language has been set as the translation language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (36, 'Text labels have not been updated successfully: the translation language has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (37, 'Text labels have been deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (38, 'Text labels have not been deleted: no text labels have been found or specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (39, 'The text label has been deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (40, 'The text label has not been deleted: it has been either not found or not specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (41, 'The text label has not been added, because its name has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (42, 'The text label has not been added, because such a text label already exists');
INSERT INTO xlite_language_labels (label_id, name) VALUES (43, 'The text label has not been added, because its translation for the default application language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (44, 'The text label has not been added, because its translation for the default interface language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (45, 'The text label has been added successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (46, 'The text label has not been modified, because its translation for the default application language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (47, 'The text label has not been modified, because its translation for the default interface language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (48, 'The text label has been modified successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (49, 'The edited language has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (50, 'The name of the edited language in the default application language has not been specified');
INSERT INTO xlite_language_labels (label_id, name) VALUES (51, 'The language data has been saved');
INSERT INTO xlite_language_labels (label_id, name) VALUES (52, 'Search');
INSERT INTO xlite_language_labels (label_id, name) VALUES (53, 'Show all labels');
INSERT INTO xlite_language_labels (label_id, name) VALUES (54, 'N items found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (55, 'Language options');
INSERT INTO xlite_language_labels (label_id, name) VALUES (56, 'X labels');
INSERT INTO xlite_language_labels (label_id, name) VALUES (57, 'translate to');
INSERT INTO xlite_language_labels (label_id, name) VALUES (58, 'Select language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (59, 'No other languages defined');
INSERT INTO xlite_language_labels (label_id, name) VALUES (60, 'Add new label');
INSERT INTO xlite_language_labels (label_id, name) VALUES (61, 'Add language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (62, 'N items');
INSERT INTO xlite_language_labels (label_id, name) VALUES (63, 'Select language to edit');
INSERT INTO xlite_language_labels (label_id, name) VALUES (64, 'Add new language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (65, 'Save');
INSERT INTO xlite_language_labels (label_id, name) VALUES (66, 'Please specify text labels for each language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (67, 'Label name');
INSERT INTO xlite_language_labels (label_id, name) VALUES (68, 'required');
INSERT INTO xlite_language_labels (label_id, name) VALUES (69, 'Confirm deletion');
INSERT INTO xlite_language_labels (label_id, name) VALUES (70, 'You are going to delete X language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (71, 'Delete');
INSERT INTO xlite_language_labels (label_id, name) VALUES (72, 'Cancel');
INSERT INTO xlite_language_labels (label_id, name) VALUES (73, 'X Language (Code: Y)');
INSERT INTO xlite_language_labels (label_id, name) VALUES (74, 'Language name in X');
INSERT INTO xlite_language_labels (label_id, name) VALUES (75, 'Native language name');
INSERT INTO xlite_language_labels (label_id, name) VALUES (76, 'Disable');
INSERT INTO xlite_language_labels (label_id, name) VALUES (77, 'Enable');
INSERT INTO xlite_language_labels (label_id, name) VALUES (78, 'Default for customer zone and can not disabled or deleted');
INSERT INTO xlite_language_labels (label_id, name) VALUES (79, 'Set this language as default for customer zone');
INSERT INTO xlite_language_labels (label_id, name) VALUES (80, 'Disabled language can not be set as default for customer zone');
INSERT INTO xlite_language_labels (label_id, name) VALUES (81, 'Delete Language');
INSERT INTO xlite_language_labels (label_id, name) VALUES (82, 'Edit label');
INSERT INTO xlite_language_labels (label_id, name) VALUES (83, 'Please specify a pattern to find the required labels');
INSERT INTO xlite_language_labels (label_id, name) VALUES (84, 'The language is enabled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (85, 'The language is disabled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (86, 'The module to uninstall has not been found');
INSERT INTO xlite_language_labels (label_id, name) VALUES (87, 'The module has been uninstalled successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (88, 'The module has been partially uninstalled');
INSERT INTO xlite_language_labels (label_id, name) VALUES (89, 'The X module has been installed successfully');
INSERT INTO xlite_language_labels (label_id, name) VALUES (90, 'The X module has been installed with errors: the DB has not been modified correctly');
INSERT INTO xlite_language_labels (label_id, name) VALUES (91, 'The X module has been installed incorrectly. Please see the logs for more information');
INSERT INTO xlite_language_labels (label_id, name) VALUES (92, 'The X module has been installed, but the module has a wrong module control class');
INSERT INTO xlite_language_labels (label_id, name) VALUES (93, 'The X module has been uninstalled in an abnormal way');
INSERT INTO xlite_language_labels (label_id, name) VALUES (94, 'The modules have been updated');
INSERT INTO xlite_language_labels (label_id, name) VALUES (95, 'The X module has been disabled in an abnormal way');


