INSERT INTO `xlite_config_translations` VALUES (1,'en',2,'active_captcha_pages','');
INSERT INTO `xlite_config_translations` VALUES (2,'en',3,'Checkout desk operation mode','');
INSERT INTO `xlite_config_translations` VALUES (3,'en',4,'Checkout desk operation mode main page','');
INSERT INTO `xlite_config_translations` VALUES (4,'en',5,'Enable admin IP protection system','');
INSERT INTO `xlite_config_translations` VALUES (5,'en',6,'Administrator Zone settings','');
INSERT INTO `xlite_config_translations` VALUES (8,'en',9,'Use HTTPS in the Administrator Zone','');
INSERT INTO `xlite_config_translations` VALUES (9,'en',10,'Enable folding sidebar menus','');
INSERT INTO `xlite_config_translations` VALUES (11,'en',12,'Allow admin IP','');
INSERT INTO `xlite_config_translations` VALUES (24,'en',27,'Enable \"Buy Now\" button in the product list','');
INSERT INTO `xlite_config_translations` VALUES (25,'en',31,'Length of string','');
INSERT INTO `xlite_config_translations` VALUES (26,'en',32,'Image generator options','');
INSERT INTO `xlite_config_translations` VALUES (27,'en',33,'Enable Captcha protection system','');
INSERT INTO `xlite_config_translations` VALUES (28,'en',34,'Where to display','');
INSERT INTO `xlite_config_translations` VALUES (29,'en',35,'Type of string that should be used for the image','');
INSERT INTO `xlite_config_translations` VALUES (32,'en',38,'Clear credit cards info from the database on order status change','');
INSERT INTO `xlite_config_translations` VALUES (40,'en',46,'Address','');
INSERT INTO `xlite_config_translations` VALUES (41,'en',47,'Contacts','');
INSERT INTO `xlite_config_translations` VALUES (42,'en',48,'Fax','');
INSERT INTO `xlite_config_translations` VALUES (43,'en',49,'Identity','');
INSERT INTO `xlite_config_translations` VALUES (44,'en',50,'Company name','');
INSERT INTO `xlite_config_translations` VALUES (45,'en',51,'Phone','');
INSERT INTO `xlite_config_translations` VALUES (46,'en',52,'Company website','');
INSERT INTO `xlite_config_translations` VALUES (52,'en',65,'Customer Zone settings','');
INSERT INTO `xlite_config_translations` VALUES (53,'en',66,'Use HTTPS in the Customer Zone (for login, checkout and profile pages)','');
INSERT INTO `xlite_config_translations` VALUES (54,'en',67,'Date format','');
INSERT INTO `xlite_config_translations` VALUES (55,'en',68,'Currency decimal delimiter','');
INSERT INTO `xlite_config_translations` VALUES (57,'en',71,'Default country in the registration form','');
INSERT INTO `xlite_config_translations` VALUES (58,'en',72,'Payment method to be assumed in case of zero order totals','');
INSERT INTO `xlite_config_translations` VALUES (60,'en',74,'Default purchase limit','');
INSERT INTO `xlite_config_translations` VALUES (61,'en',75,'Default payment method','');
INSERT INTO `xlite_config_translations` VALUES (62,'en',76,'Default zip/postal code in the registration form','');
INSERT INTO `xlite_config_translations` VALUES (63,'en',77,'Show shipping rates & taxes to unregistered customers<br>(presuming that a customer comes from the default country)','');
INSERT INTO `xlite_config_translations` VALUES (64,'en',80,'Developer\'s mode (force to re-generate cache)','');
INSERT INTO `xlite_config_translations` VALUES (67,'en',89,'Allow direct URL access to products from disabled categories','');
INSERT INTO `xlite_config_translations` VALUES (68,'en',90,'Discounts charged after taxes application','');
INSERT INTO `xlite_config_translations` VALUES (69,'en',91,'Display check number for eCheck payment method','');
INSERT INTO `xlite_config_translations` VALUES (76,'en',100,'Enable anonymous checkout','');
INSERT INTO `xlite_config_translations` VALUES (77,'en',101,'Enable extra fields in the category management dialogue','');
INSERT INTO `xlite_config_translations` VALUES (78,'en',102,'Validate credit cards','');
INSERT INTO `xlite_config_translations` VALUES (79,'en',103,'Enable products to inherit extra fields from disabled categories (for MultiCategories)','');
INSERT INTO `xlite_config_translations` VALUES (80,'en',104,'E-mail order details to the sales department after order placement','');
INSERT INTO `xlite_config_translations` VALUES (81,'en',105,'E-mail order details to customers after order placement','');
INSERT INTO `xlite_config_translations` VALUES (83,'en',107,'Enable \"Market price\" feature','');
INSERT INTO `xlite_config_translations` VALUES (93,'en',120,'Enable admin forms protection system','');
INSERT INTO `xlite_config_translations` VALUES (101,'en',128,'Customer Zone fully on HTTPS','');
INSERT INTO `xlite_config_translations` VALUES (107,'en',138,'Enable .htaccess verification system','');
INSERT INTO `xlite_config_translations` VALUES (108,'en',140,'HTTPS client to use (for integration with secure payment/shipping services)','');
INSERT INTO `xlite_config_translations` VALUES (109,'en',141,'Includes tax message','');
INSERT INTO `xlite_config_translations` VALUES (112,'en',153,'Street address','');
INSERT INTO `xlite_config_translations` VALUES (113,'en',154,'City','');
INSERT INTO `xlite_config_translations` VALUES (114,'en',155,'Country','');
INSERT INTO `xlite_config_translations` VALUES (115,'en',156,'Other state (specify)','');
INSERT INTO `xlite_config_translations` VALUES (116,'en',157,'State','');
INSERT INTO `xlite_config_translations` VALUES (117,'en',158,'Zip/postal code','');
INSERT INTO `xlite_config_translations` VALUES (118,'en',159,'Days to store last login data','');
INSERT INTO `xlite_config_translations` VALUES (119,'en',160,'Clear cart on customer logoff','');
INSERT INTO `xlite_config_translations` VALUES (122,'en',165,'Maximum allowed order total','');
INSERT INTO `xlite_config_translations` VALUES (123,'en',166,'Membership levels','');
INSERT INTO `xlite_config_translations` VALUES (124,'en',167,'Membership levels','');
INSERT INTO `xlite_config_translations` VALUES (126,'en',170,'Minimum allowed order total','');
INSERT INTO `xlite_config_translations` VALUES (135,'en',179,'Maintenance and operation','');
INSERT INTO `xlite_config_translations` VALUES (136,'en',180,'Sales department e-mail','');
INSERT INTO `xlite_config_translations` VALUES (137,'en',181,'Orders per page','');
INSERT INTO `xlite_config_translations` VALUES (138,'en',182,'Initial order number','');
INSERT INTO `xlite_config_translations` VALUES (151,'en',205,'Prices include tax','');
INSERT INTO `xlite_config_translations` VALUES (153,'en',207,'Currency format','');
INSERT INTO `xlite_config_translations` VALUES (156,'en',210,'Products per category listing page','');
INSERT INTO `xlite_config_translations` VALUES (157,'en',211,'Products per page','');
INSERT INTO `xlite_config_translations` VALUES (159,'en',214,'HTTPS proxy','');
INSERT INTO `xlite_config_translations` VALUES (161,'en',216,'Amount of orders in the recent orders list','');
INSERT INTO `xlite_config_translations` VALUES (162,'en',217,'Redirect customer to cart when adding a product','');
INSERT INTO `xlite_config_translations` VALUES (172,'en',228,'Safe mode (do not initialize modules)','');
INSERT INTO `xlite_config_translations` VALUES (175,'en',234,'Check this to temporary close the shop','');
INSERT INTO `xlite_config_translations` VALUES (177,'en',236,'Include order details (credit card or eCheck information) into admin order notification message','');
INSERT INTO `xlite_config_translations` VALUES (178,'en',237,'Show thumbnails in product list','');
INSERT INTO `xlite_config_translations` VALUES (179,'en',238,'Site administrator e-mail','');
INSERT INTO `xlite_config_translations` VALUES (180,'en',239,'Password','');
INSERT INTO `xlite_config_translations` VALUES (181,'en',240,'Secure connection','');
INSERT INTO `xlite_config_translations` VALUES (182,'en',241,'SMTP server','');
INSERT INTO `xlite_config_translations` VALUES (183,'en',242,'SMTP port','');
INSERT INTO `xlite_config_translations` VALUES (184,'en',243,'SMTP server','');
INSERT INTO `xlite_config_translations` VALUES (185,'en',244,'Username','');
INSERT INTO `xlite_config_translations` VALUES (186,'en',245,'Year when store started its operation','');
INSERT INTO `xlite_config_translations` VALUES (188,'en',247,'Category listings format','');
INSERT INTO `xlite_config_translations` VALUES (189,'en',248,'HelpDesk/Support service e-mail','');
INSERT INTO `xlite_config_translations` VALUES (190,'en',250,'Tax rates','');
INSERT INTO `xlite_config_translations` VALUES (191,'en',252,'Currency thousands delimiter','');
INSERT INTO `xlite_config_translations` VALUES (194,'en',255,'Time format','');
INSERT INTO `xlite_config_translations` VALUES (195,'en',256,'Time zone','');
INSERT INTO `xlite_config_translations` VALUES (197,'en',258,'Units of measurement','');
INSERT INTO `xlite_config_translations` VALUES (198,'en',265,'Customer relations e-mail','');
INSERT INTO `xlite_config_translations` VALUES (199,'en',266,'Users per page','');
INSERT INTO `xlite_config_translations` VALUES (200,'en',268,'Use billing info to calculate taxes','');
INSERT INTO `xlite_config_translations` VALUES (201,'en',269,'Use SMTP server','');
INSERT INTO `xlite_config_translations` VALUES (202,'en',270,'Use authentication','');
INSERT INTO `xlite_config_translations` VALUES (203,'en',271,'Valid domain names for email','');
INSERT INTO `xlite_config_translations` VALUES (204,'en',275,'Weight symbol','');
INSERT INTO `xlite_config_translations` VALUES (205,'en',276,'Weight unit','');
INSERT INTO `xlite_config_translations` VALUES (224,'en',299,'Enable \"save\" label (for Market Price)','');

