# vim: set ts=2 sw=2 sts=2 et:
#
# Unused config options
#
# @author    Creative Development LLC <info@cdev.ru>
# @copyright Copyright (c) 2011-2012 Creative Development LLC <info@cdev.ru>. All rights reserved
# @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
# @link      http://www.litecommerce.com/

XLite\Model\Config:
  - { name: 'enable_anon_checkout', category: 'General' }
  - { name: 'show_thumbnails', category: 'General' }
  - { name: 'order_starting_number', category: 'General' }
