
                       SOFTWARE LICENSE AGREEMENT

Copyright c 2003-2005 Creative Development <info@creativedevelopment.biz> 
All rights reserved. 

 PLEASE READ 

THIS  AGREEMENT  EXPRESSES  THE  TERMS AND CONDITIONS ON WHICH YOU MAY USE THIS
SOFTWARE  PROGRAM  AND  ASSOCIATED  DOCUMENTATION THAT CREATIVE DEVELOPMENT LLC
REGISTERED  IN  ULYANOVSK,  RUSSIAN FEDERATION (hereinafter referred to as "THE
AUTHOR")  IS  FURNISHING  OR  MAKING  AVAILABLE  TO  YOU  WITH  THIS  AGREEMENT
(COLLECTIVELY,   THE   "SOFTWARE").  PLEASE  REVIEW  THE  FOLLOWING  TERMS  AND
CONDITIONS  OF  THIS LICENSE AGREEMENT CAREFULLY BEFORE INSTALLING OR USING THE
SOFTWARE.  BY INSTALLING, COPYING OR OTHERWISE USING THE SOFTWARE, YOU AND YOUR
COMPANY  (COLLECTIVELY,  "YOU") ARE ACCEPTING AND AGREEING TO THE TERMS OF THIS
LICENSE AGREEMENT. IF YOU ARE NOT WILLING TO BE BOUND BY THIS AGREEMENT, DO NOT
INSTALL OR USE THE SOFTWARE. VARIOUS COPYRIGHTS AND OTHER INTELLECTUAL PROPERTY
RIGHTS  PROTECT  THE SOFTWARE. THIS AGREEMENT IS A LICENSE AGREEMENT THAT GIVES
YOU  LIMITED  RIGHTS  TO  USE THE SOFTWARE AND NOT AN AGREEMENT FOR SALE OR FOR
TRANSFER  OF TITLE. THE AUTHOR RETAINS ALL RIGHTS NOT EXPRESSLY GRANTED BY THIS
AGREEMENT.  The  author  forbids,  under  any  circumstances,  the unauthorized
reproduction  of  the  Software  or  use of illegally obtained software. Making
illegal copies of the Software is prohibited. Individuals who violate copyright
law  and  software  licensing  agreements  may  be subject to criminal or civil
action by the owner of the copyright.

1. LICENCE GRANT 

Upon  the  terms  and  conditions  of  this  Agreement, the Author grants you a
nonexclusive,  nontransferable license to use the Software on a computer server
and  only  for  purposes  of  provision of contractual services offering remote
access  for  your  clients to the operational and maintenance interfaces of the
Software  for  the  purpose  of  operating  an electronic commerce store on the
Internet.

2. PROPERTY RIGHTS AND RESTRICTIONS 

2.1  Ownership.  The  Software  and  all  modifications  or enhancements to, or
derivative  works  based on the Software, whether created by the Author or you,
and  all  copyrights, patents, trade secrets, trademarks and other intellectual
property  rights  protecting or pertaining to any aspect of the Software or any
such modification, enhancement or derivative work are and shall remain the sole
and  exclusive  property of the Author. This Agreement does not convey title or
ownership  to  you  but  instead gives you only the limited rights set forth in
this Agreement.

2.2 Limited Rights. Pursuant to this Agreement, you may: a) use the Software on
one  website  only, for purposes of running number of e-commerce shops which do
not  exceeds  maximum shop quantity specified in your license and granting your
clients  ability to operate these shops as a contractual service. The number of
clients simultaneously subscribed for such contractual service shall not exceed
maximum  shop  quantity  specified in your license. You must provide the author
with  the  exact  URL  (Unique Resource Locator) of the website you install the
Software  to;  b)  modify  the  Software  and/or merge it into another program;
c)transfer  the Software and license to another party if the other party agrees
to  accept  the terms and conditions of this Agreement. Except as expressly set
forth  in  this  Agreement, you have no right to use, make, sublicense, modify,
transfer or copy either the original or any copies of the Software or to permit
anyone  else  to do so. You may not allow any third party to use or have access
to  the  Software.  It  is illegal to copy the Software and install that single
program for simultaneous use on multiple machines.

2.3  Proprietary  Notices.  You may not remove, disable, modify, or tamper with
any  copyright,  trademark  or  other proprietary notices and legends contained
within the code of the Software.

2.4  Confidentiality.  The  Software  and  the templates contain valuable trade
secrets  and  proprietary  information  belonging  to  Author.  You  must  keep
confidential  and  protect  from unauthorized disclosure all such program code,
all   templates  and  all  information  that  Author  expressly  designates  as
confidential  or  that  you  reasonably should understand to be confidential or
proprietary.  You  can  grant  access  to  the templates that are necessary for
normal  operation of the software only for those clients that are legally bound
with  you  by  Service  Level  Agreement  or  other contractual obligations for
provision of services.

3. WARRANTIES, DISCLAIMERS AND EXLUSIVE REMEDIES

3.1 We warrant that the Software will substantially operate as described in the
applicable  program  documentation  for  1  year  after you download/copy it to
install on your website. If ordered, technical support can be provided based on
the  current  policies  for  the  applicable services ordered. This Software is
provided  "as  is" and these warranties do not guarantee that the Software will
perform  error-free  or  uninterrupted,  or  that  we  will correct all program
errors.  These warranties are exclusive and take the place of all other express
or  implied  warranties  or  conditions  including  warranties or conditions of
merchantability, satisfactory quality, and fitness for a particular purpose. If
we  cannot  substantially correct a breach of our warranties, in a commercially
reasonable  manner,  you  may  end your program license and recover the license
fees  or  technical  support  fees  paid to us under this license agreement, as
applicable. This is your exclusive remedy.

4. LIMITATION OF LIABILITY 

Neither  party shall be liable for any indirect, incidental, special, punitive,
or  consequential  damages, or any loss of profits, revenue, data, or data use.
Our  maximum  liability  for  any  damages whether in contract or tort will not
exceed  the fees which you have paid to us or are payable to us for this order,
and  if such damages result from your use of the Software or technical support,
the  liability shall be limited to the fees paid or payable for the Software or
technical support.

5. TERM 

The  license  is  effective until terminated. You may terminate it at any other
time  by  deleting  the  Software  together  with all copies, modifications and
merged  portions  in any form. It will also terminate upon conditions set forth
elsewhere in this Agreement or if you fail to comply with any term or condition
of  this  Agreement.  You  agree  upon  such termination to delete the Software
together with all copies, modifications and merged portions in any form.

6. GENERAL 

If  any  provision  of  this Agreement is declared void or unenforceable by any
judicial  authority,  this  shall  not  nullify the remaining provisions of the
Agreement  which shall remain in full force and effect. You may not sublicense,
assign  or transfer the license or the Software except as expressly provided in
this  Agreement. Any attempt to otherwise sublicense, assign or transfer any of
the rights, duties or obligations hereunder is null and void. This Agreement is
governed  by  English  law.  Any dispute arising out or in connection with this
agreement   including   any  question  regarding  its  existence,  validity  or
termination, shall be referred to and finally resolved by arbitration under the
Rules of the London Court of International Arbitration ("LCIA") which Rules are
deemed  to  be  incorporated  by  reference  into  this  clause.  The  place of
arbitration shall be London, England.

The Initial Developer of the Original Code is Creative Development LLC.
Portions  created  by  Creative  Development  LLC  are  Copyright (C) 2003-2005
Creative Development LLC. All Rights Reserved.
