#!/usr/local/php-532/bin/php -q
<?php

function _do_query_upload($sqlfile, $connection = null, $ignoreErrors = false) {
	echo '+++ ' . $sqlfile . PHP_EOL;
	ob_start();
	query_upload($sqlfile, $connection, $ignoreErrors);
	$output = ob_get_contents();
	ob_end_clean();
	$output = strip_tags($output);
	if (!empty($output) && preg_match('/\[NOTE:/', $output)) {
		echo PHP_EOL . $output . PHP_EOL;
	}
}

if (isset($argv[1]) && $argv[1] == 'help') {
	echo <<<OUT
Usage: $argv[0] [option1] [option2]

where:
  option1 - one of the following: demo (install all demo data), standalone (only demo data for LC standalone distributive), drupal (install only demo data for distributive and enable DrupalConnector module; uses by default).
  option2 - if has a value 'all' then all modules will be enabled (only if option1=demo)

Examples:
  $argv[0]
  $argv[0] demo
  $argv[0] demo all
  $argv[0] standalone

OUT;
	exit;
}

chdir(dirname(__FILE__));

define('LC_DO_NOT_REBUILD_CACHE', true);
require_once './top.inc.php';

set_time_limit(0);
error_reporting(E_ALL ^ E_NOTICE);
$config = parse_ini_file('etc/config.local.php');

$config['hostspec'] .= empty($config['socket'])
	? (empty($config['port']) ? '' : ':' . $config['port'])
	: ':' . $config['socket'];
$connection = mysql_connect($config['hostspec'], $config['username'], $config['password']);
mysql_select_db($config['database']);

_do_query_upload('sql/xlite_tables.sql', $connection, true);
_do_query_upload('sql/xlite_data.sql', $connection, true);
_do_query_upload('sql/xlite_lng_en.sql', $connection, true);
_do_query_upload('sql/xlite_lng_de.sql', $connection, true);
_do_query_upload('sql/states_US.sql', $connection, true);
_do_query_upload('sql/states_GB.sql', $connection, true);
_do_query_upload('sql/states_CA.sql', $connection, true);

if (!isset($argv[1]) || $argv[1] != 'demo') {
	_do_query_upload('sql/xlite_demo.sql', $connection, true);
}

require_once 'classes/XLite/Module/AModule.php';
require_once 'classes/XLite/Base/IPatcher.php';

// modules
$modules = opendir('classes/XLite/Module');

while (($dir = readdir($modules)) !== false) {
	if (
		substr($dir, 0, 1) != '.'
		&& is_dir('classes/XLite/Module/' . $dir)
		&& file_exists('classes/XLite/Module/' . $dir . '/Main.php')
	) {

		require_once 'classes/XLite/Module/' . $dir . '/Main.php';
		$class = '\XLite\Module\\' . $dir . '\Main';
		$obj = new $class();

		mysql_query('REPLACE INTO xlite_modules SET name = \'' . $dir . '\', mutual_modules = \'' . implode(',', $obj->getMutualModulesList()) . '\', type = \'' . $obj->getModuleType(). '\', installed = 1, version = \'' . $obj->getVersion() . '\', dependencies = \'' . implode(',', $obj->getDependenciesList()) . '\'');

		$sqlFile = 'classes/XLite/Module/' . $dir . '/install.sql';
		if (file_exists($sqlFile)) {
			_do_query_upload($sqlFile, $connection, true);
		}
	}
}

closedir($modules);

_do_query_upload('sql/demo/xlite_demo_user.sql', $connection, true);

if (isset($argv[1]) && $argv[1] == 'demo') {

    _do_query_upload('sql/demo/xlite_demo_data.sql', $connection, true);
	_do_query_upload('sql/demo/xlite_demo_store.sql', $connection, true);
	_do_query_upload('sql/demo/xlite_demo_orders.sql', $connection, true);
	_do_query_upload('sql/local/xlite_test_accounts.sql', $connection, true);

	if (isset($argv[2]) && $argv[2] == 'all') {
		_do_query_upload('sql/local/xlite_all_modules.sql', $connection, true);
	}

} elseif (isset($argv[1]) && in_array($argv[1], array('standalone', 'st', 's', 'stand'))) {
	_do_query_upload('sql/local/xlite_modules_standalone.sql', $connection, true);
} else {
	_do_query_upload('sql/local/xlite_modules_drupal.sql', $connection, true);
}

if (file_exists('sql/local/xlite_local_demo.sql')) {
	_do_query_upload('sql/local/xlite_local_demo.sql', $connection, true);
}

echo 'Remove the var/* sub-directories' . PHP_EOL . PHP_EOL;

\Includes\Utils\FileManager::unlinkRecursive('var/run');
\Includes\Utils\FileManager::unlinkRecursive('var/locale');
\Includes\Utils\FileManager::unlinkRecursive('var/images');
\Includes\Utils\FileManager::unlinkRecursive('var/datacache');
\Includes\Utils\FileManager::unlinkRecursive('var/log');

mysql_close($connection);

