<?php
/**
 * LiteCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to licensing@litecommerce.com so we can send you a copy immediately.
 *
 * @category   LiteCommerce
 * @package    Tests
 * @subpackage Amazon
 * @author     Creative Development LLC <info@cdev.ru>
 * @copyright  Copyright (c) 2010 Creative Development LLC <info@cdev.ru>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link       http://www.litecommerce.com/
 * @see        ____file_see____
 */

/**
 * @param $url
 * @param $port
 * @param $timeout
 * @return bool
 */
function wait_for_service($url, $port, $timeout)
{
    $time = time() + $timeout;
    while ($time > time()) {
        $ch = curl_init($url . ':' . $port);
        curl_setopt($ch, CURLOPT_HEADER, TRUE);
        curl_setopt($ch, CURLOPT_NOBODY, TRUE); // remove body
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($httpCode == 200)
            return true;
    }
    return false;
}

function array_reduce_index($array, $callback, $initial = null)
{
    foreach ($array as $key => $element) {
        $initial = call_user_func($callback, $initial, $element, $key);
    }
    return $initial;
}

function get_screenshots($app)
{
    if (!file_exists($app['logdir'] . '/screenshots'))
        mkdir($app['logdir'] . '/screenshots');
    foreach ($app['cloud']->farms as $farm) {
        exec('scp -i ' . $app['keypair'] . ' ubuntu@' . $farm->public_dns . ':/var/www/selenium-screenshots/* ' . $app['logdir'] . '/screenshots');
    }
    if ($app['cloud']->micro_farm)
        exec('scp -i ' . $app['keypair'] . ' ubuntu@' . $app['cloud']->micro_farm->public_dns . ':/var/www/selenium-screenshots/* ' . $app['logdir'] . '/screenshots');
}

function server_setup($app)
{
    print PHP_EOL . "Setting up LC server..." . PHP_EOL;

    $server = $app['cloud']->server;
    $options = array('pwd' => "/opt/bitnami/apache2/htdocs/xlite",
        'user' => 'bitnami',
        'keypair' => $app['keypair']);
    $server->run("sudo sed 's/_hostname_/" . $app['cloud']->server->private_dns . "/g'  src/etc/config.template.php > src/etc/config.php", $options);
    $server->run("sudo /etc/init.d/lc-startup", $options);
    $server->run("sed 's/_hostname_/" . $app['cloud']->server->private_dns . "/g'  .dev/tests/local.template.php | sed 's/_grid_hub_/" . $app['cloud']->hub->private_dns . "/g' | sed 's/_clients_count_/" . $app['farms_count'] . "/g' > .dev/tests/local.php", $options);
    $options['pwd'] .= '/.dev';
    $code = $server->run("./phpunit tests/Dev_Install.php", $options);
    //if ($code != 0)
      //  die($code);
}

require_once "lib/Cloud.php";

function start_instance($ami, $type, $keypair_name){

}

task("setup", function ($app)
{
    $app['remote_control_port_range'] = array_key_exists('remote_control_port_range', $app) ? $app['remote_control_port_range'] : "5555-5555";
    $app['launch_timeout'] = array_key_exists('launch_timeout', $app) ? $app['launch_timeout'] : 240;
    $app['cloud'] = Cloud::getInstance();
    $app['farms_count'] = 5;
    $app['hub_ami'] = exec("ec2-describe-images | grep lc-test-grid | cut -f2");
    $app['lc_ami'] = exec("ec2-describe-images | grep lc-server | cut -f2");
    $app['server_instance_type'] = "m1.small";
    $app['grid_instance_type'] = "m1.small";
    $app['firefox_profile'] = "/http/selenium/selenium-grid/FirefoxProfile";

    $app['keypair'] = getenv("EC2_KEYPAIR");
    $app['keypair_name'] = getenv("EC2_KEYPAIR_NAME");
    $app['selenium_grid_path'] = "/http/selenium/selenium-grid";
    $app['logdir'] = 'logs';
    if (file_exists($app['logdir'])) {
        exec('rm -rf ' . $app['logdir']);
    }
    mkdir($app['logdir']);
});


group("grid", function()
{
    desc("Boot EC2 Instances for a Selenium Grid of 1 Hub and <farms_count> Remote Control Farms.");
    task("boot", "setup", "hub:boot", "rc:boot", "server:boot", function($app)
    {
        Ec2Client::authorize_port(22);
        Ec2Client::authorize_port(4444);
        Ec2Client::authorize_port(5900);
        Ec2Client::authorize_port(6000);
        $boundaries = explode("-", $app['remote_control_port_range']);
        for ($i = $boundaries[0]; $i <= (isset($boundaries[1]) ? $boundaries[1] : $boundaries[0]); $i++) {
            Ec2Client::authorize_port($i);
        }
    });

    desc("Shutdown EC2 Instance used to run Selenium Hub.");
    task("shutdown", 'setup', "hub:shutdown", "server:shutdown", "rc:shutdown", function ($app)
    {
        $app['cloud'] = Cloud::getInstance();
        $app['cloud']->save();
    });


    task("start_hub", "boot", "hub:start", "rc:start", function($app)
    {
        wait_for_service($app['cloud']->hub->public_dns, 4444, $app['launch_timeout']);
    });

    desc("Start Selenium Grid.");
    task("start", "start_hub", "rc:start", "server:setup");

    desc("Stop Selenium Grid Hub.");
    task("stop", "rc:stop", "hub:stop");

    desc("Display information about current Selenium Grid");
    task("info", 'setup', function($app)
    {
        print
            PHP_EOL . "EC2 Selenium Grid:
        ==================

        Hub:
        ----"
                . ($app['cloud']->hub ?
                "\n      - Public DNS:  " . $app['cloud']->hub->public_url .
                    "\n      - Private DNS: " . $app['cloud']->hub->private_url .
                    "\n      - Console:     " . $app['cloud']->hub->console_url : "") .
                PHP_EOL .
                "  LC server:
        ----"
                . ($app['cloud']->server ?
                "\n      - Public DNS:  " . $app['cloud']->server->public_dns .
                    "\n      - Private DNS: " . $app['cloud']->server->private_dns .
                    "\n      - Admin URL: " . $app['cloud']->server->admin_url .
                    "\n      - XLite CMS URL: " . $app['cloud']->server->cms_url : "") .
                PHP_EOL .
                "  Remote Control Farms:
        ---------------------"
                . array_reduce_index($app['cloud']->farms, function($val, $el, $key) use($app)
            {
                return $val . PHP_EOL .
                    "       * Farm #$key
                    - Public DNS:  " . $el->public_dns . PHP_EOL
                    . "               - Private DNS: " . $el->private_dns . PHP_EOL
                    . "               - Port Range: " . $app['remote_control_port_range'] . PHP_EOL;

            });
    });

});

###### Hub Recipes ######
group("hub", function()
{
    desc("Boot a new EC2 Instance to Run Selenium Grid Hub.");
    task("boot", "setup", function($app)
    {
        print PHP_EOL . "Starting a new EC2 Instance...";
        $app['cloud']->hub = Hub::boot_and_acquire_dns($app['hub_ami'], array('keypair_name' => $app['keypair_name'], 'type' => 't1.micro' /*$app['grid_instance_type']*/));
        print PHP_EOL . "Started new Hub at " . $app['cloud']->hub->public_dns;

        print PHP_EOL . "Starting a new EC2 Instance...";
        try {
            $farm = Server::boot_and_acquire_dns($app['hub_ami'], array('keypair_name' => $app['keypair_name'], 'type' => 't1.micro'));
            $app['cloud']->micro_farm = $farm;
            $app['cloud']->save();
            print PHP_EOL . "Started new Remote Control farm at " . $farm->public_dns;
        }
        catch (Exception $e) {
            print PHP_EOL . "Failed to boot new Remote Control farm.";
        }

        $app['cloud']->save();
    });

    desc("Shutdown EC2 Instance used to run Selenium Hub.");
    task("shutdown", "setup", function($app)
    {
        if ($app['cloud']->hub) {
            print PHP_EOL . "Shutting down EC2 Instance " . $app['cloud']->hub->public_dns . "...";
            $app['cloud']->hub->shutdown();
            $app['cloud']->hub = null;
            $app['cloud']->save();
        }
        if ($app['cloud']->micro_farm) {
            print PHP_EOL . "Shutting down EC2 Instance " . $app['cloud']->micro_farm->public_dns . "...";
            $app['cloud']->micro_farm->shutdown();
            $app['cloud']->micro_farm = null;
            $app['cloud']->save();
        }
    });

    desc("(Re)start Selenium Grid Hub.");
    task("restart", ":stop", ":start");

    desc("Start Selenium Grid Hub.");
    task("start", "setup", function($app)
    {
        $app['cloud']->hub->run("nohup rake hub:start BACKGROUND=true", array('pwd' => $app['selenium_grid_path'], 'keypair' => $app['keypair']));
        $farm = $app['cloud']->micro_farm;
        $farm->run("nohup rake rc:start_all SELENIUM_ARGS=\"-firefoxProfileTemplate ".$app['firefox_profile']."\"  HUB_URL=" . $app['cloud']->hub->private_url . " HOST=" . $farm->private_dns . " PORTS=" . $app['remote_control_port_range'] . " BACKGROUND=true",
            array('display' => ":0", 'path' => "/usr/lib/firefox-8.0", 'pwd' => $app["selenium_grid_path"], 'keypair' => $app['keypair']));
        $farm->run("nohup vncserver :0", array('keypair' => $app['keypair']));
    });

    desc("Stop Selenium Grid Hub.");
    task("stop", "setup", function($app)
    {
        $app['cloud']->hub->run('rake hub:stop', array('pwd' => $app['selenium_grid_path'], 'keypair' => $app['keypair']));
        $app['cloud']->save();
    });

    desc("Open Selenium Grid Hub Console in a browser.");
    task("console", "setup", function($app)
    {
        exec("firefox " . $app['cloud']->hub->console_url);
    });

    desc("View Selenium Grid Hub logs.");
    task('logs', "setup", function($app)
    {
        $app['cloud']->hub->run("tail -200f " . $app['selenium_grid_path'] . "/log/hub.log", array('keypair' => $app['keypair']));
    });

});


###### Remote Control Recipes ######
group("rc", function()
{

    desc("Boot a new EC2 Instance to run a collection of Selenium Grid Remote Controls.");
    task("boot", "setup", function($app)
    {
        for ($i = 0; $i < $app['farms_count']; $i++) {
            print PHP_EOL . "Starting a new EC2 Instance...";
            try {
                $farm = Server::boot_and_acquire_dns($app['hub_ami'], array('keypair_name' => $app['keypair_name'], 'type' => $app['grid_instance_type']));
                $app['cloud']->farms[] = $farm;
                $app['cloud']->save();
                print PHP_EOL . "Started new Remote Control farm at " . $farm->public_dns;
            }
            catch (Exception $e) {
                print PHP_EOL . "Failed to boot new Remote Control farm.";
            }
        }
    });

    desc("Shutdown all EC2 Instances used to run Selenium Grid Remote Controls.");
    task("shutdown", "setup", function($app)
    {
        foreach ($app['cloud']->farms as $key => $farm) {
            print PHP_EOL . "Shutting down EC2 Instance " . $farm->public_dns . "...";
            $farm->shutdown();
            unset($app['cloud']->farms[$key]);
        }
        $app['cloud']->save();
    });

    desc("(Re)start Remote Controls for all farms.");
    task('restart', ":stop", ":start");

    desc("Start Remote Controls for all farms.");
    task('start', "setup", function($app)
    {
        if ($app['cloud']->micro_farm){
            print PHP_EOL . "Stopping Remote Control at " . $app['cloud']->micro_farm->public_dns . "...";
            $app['cloud']->micro_farm->run("rake rc:stop_all PORTS=" . $app['remote_control_port_range'], array('pwd' => $app['selenium_grid_path'], 'keypair' => $app['keypair']));
        }
        foreach ($app['cloud']->farms as $farm) {
            print PHP_EOL . "Starting Remote Control at " . $farm->public_dns . "...";
            $farm->run("nohup rake rc:start_all SELENIUM_ARGS=\"-firefoxProfileTemplate ".$app['firefox_profile']."\" HUB_URL=" . $app['cloud']->hub->private_url . " HOST=" . $farm->private_dns . " PORTS=" . $app['remote_control_port_range'] . " BACKGROUND=true",
                array('display' => ":0", 'path' => "/usr/lib/firefox-8.0", 'pwd' => $app["selenium_grid_path"], 'keypair' => $app['keypair']));
            $farm->run("nohup vncserver :0", array('keypair' => $app['keypair']));

        }
        Ec2Client::authorize_port(5900);
        Ec2Client::authorize_port(6000);
    });

    desc("Stop Remote Controls for all farms.");
    task('stop', "setup", function($app)
    {
        foreach ($app['cloud']->farms as $farm) {
            $farm->run("rake rc:stop_all PORTS=" . $app['remote_control_port_range'], array('pwd' => $app['selenium_grid_path'], 'keypair' => $app['keypair']));
        }
    });

    desc("Visualize what is happening in Remote Control Farms with VNC");
    task('view', "setup", function($app)
    {
        foreach ($app['cloud']->farms as $farm) {
            exec("vncviewer " . $farm->public_dns . " >> /dev/null &");
        }
    });

});

###### Settings Recipes ######
group("ec2", function()
{
    desc("Check EC2 related configuration.");
    task('check_settings', function()
    {
        print PHP_EOL . "Validating environment variables...";
        foreach (array("EC2_HOME", "EC2_PRIVATE_KEY", "EC2_CERT", "EC2_KEYPAIR") as $var) {
            if (!getenv($var))
                throw new Exception(PHP_EOL .
                    "+++++++++++++++++++++++++++++++++++++++++++++++
                You must set $var.

                Read http://docs.amazonwebservices.com/AWSEC2/2007-08-29/GettingStartedGuide/?ref=get-started
                for more details.

                ++++++++++++++++++++++++++++++++++++++++++++++++" . PHP_EOL);
        }
        foreach (array("EC2_PRIVATE_KEY", "EC2_CERT", "EC2_KEYPAIR") as $var) {
            if (!file_exists(getenv($var)))
                throw new Exception("$var environment variable does not point to a valid path: '" . getenv($var) . "'");
        }
        print PHP_EOL . "EC2 Version: " . Ec2Client::version();
        print PHP_EOL . "Validated EC2 settings.";

    });
});

group("server", function()
{

    desc("Boot lc server instance");
    task('boot', "setup", function($app)
    {
        print PHP_EOL . "Starting a new EC2 Instance...";
        $app['cloud']->server = LcServer::boot_and_acquire_dns($app['lc_ami'], array('keypair_name' => $app['keypair_name'], 'type' => $app['server_instance_type']));
        print PHP_EOL . "Started new lc server at " . $app['cloud']->server->public_dns;
        $app['cloud']->save();
    });

    desc("Set up testing environment");
    task('config', 'setup', function($app)
    {
        server_setup($app);

    });

    desc("Start tests");
    task('test_seq', 'config', function($app)
    {
        print PHP_EOL . "Run sequential tests on " . $app['cloud']->server->public_dns . "...";
        $app['cloud']->server->run("sudo ./phpunit.sh ONLYWEB", array('pwd' => "/opt/bitnami/apache2/htdocs/xlite/.dev", 'user' => 'bitnami', 'keypair' => $app['keypair']));
    });

    desc("Start parallel tests");
    task('test_parallel', 'config', function($app)
    {
        $server = $app['cloud']->server;
        print PHP_EOL . "Run parallel tests on " . $app['cloud']->server->public_dns . "...";

        $options = array('pwd' => "/opt/bitnami/apache2/htdocs/xlite/.dev", 'user' => 'bitnami', 'keypair' => $app['keypair']);
        $code = $server->run("sudo ./phpunit-parallel.php --build --clients-count ". ($app['farms_count']) ."; cat /tmp/phpunit.txt", $options);

        exec('scp -i ' . $app['keypair'] . ' bitnami@' . $server->public_dns . ':/tmp/phpunit*.xml ' . $app['logdir']);

        get_screenshots($app);
        //if ($code != 0)
        //    die($code);
    });

    desc('Drupal + LC deployment test');
    task('test_deploy', "setup", function($app)
    {
        $server = $app['cloud']->server;
        $options = array('pwd' => "/opt/bitnami/apache2/htdocs", 'user' => 'bitnami', 'keypair' => $app['keypair']);

        $server->run('cp xlite/src/etc/config.php xlite/.dev/build/config.local.php;' .
            'cp xlite_cms/sites/default/settings.php xlite_cms/sites/default/settings.old.php;
                     cp xlite_cms/sites/default/default.settings.php xlite_cms/sites/default/settings.php;' .
            'mkdir xlite_cms/modules/lc_connector/litecommerce;
                     cp -r xlite/src/* xlite_cms/modules/lc_connector/litecommerce;
                     rm xlite_cms/modules/lc_connector/litecommerce/etc/config.php;
                     sudo chmod -R 777 .', $options);

        $code = $server->run('cd xlite/.dev; sudo ./phpunit.sh DEPLOY_DRUPAL', $options);
        get_screenshots($app);
        $server->run('sudo rm -rf xlite_cms/modules/lc_connector/litecommerce;' .
            'cp xlite_cms/sites/default/settings.old.php xlite_cms/sites/default/settings.php;' .
            'sudo chmod -R 777 .', $options);
        //if ($code != 0)
          //  die($code);
        server_setup($app);
    });

    desc("Shutdown lc server instance");
    task('shutdown', "setup", function($app)
    {
        if ($app['cloud']->server) {
            print PHP_EOL . "Shutting down EC2 Instance " . $app['cloud']->server->public_dns . "...";
            $app['cloud']->server->shutdown();
            $app['cloud']->server = null;
            $app['cloud']->save();
        }
    });

});

task('clear', function(){
    if (file_exists('data.txt'))
        unlink('data.txt');
});

task('parallel_boot', 'clear', 'setup', 'hub:boot', 'server:boot', function($app)
{
    Ec2Client::authorize_port(22);
    Ec2Client::authorize_port(4444);
    Ec2Client::authorize_port(5900);
    Ec2Client::authorize_port(6000);
    $boundaries = explode("-", $app['remote_control_port_range']);
    for ($i = $boundaries[0]; $i < $boundaries[1]; $i++) {
        Ec2Client::authorize_port($i);
    }
});


task('parallel', 'parallel_boot', 'hub:start', 'server:config', 'rc:boot', 'rc:start', 'server:test_parallel', 'grid:shutdown');

task('deploy', 'parallel_boot', 'hub:start', 'server:config', 'server:test_deploy');
task('default', 'ec2:check_settings', 'deploy', 'parallel', 'rc:boot', 'rc:start', 'server:test_parallel', 'grid:shutdown');

?>